// Generated by HoloScript Compiler v3.42.0
// Source: examples\demos\collaborative-building.holo
// Target: webgpu
// Generated: 2026-02-22T06:29:16.815Z
//
// NOTE: This is a demonstration placeholder.
// For actual compilation, use:
//   npx holoscript compile examples\demos\collaborative-building.holo --target webgpu
//
// Or use the HoloScript CLI from the HoloScript repository:
//   cd ../HoloScript
//   npx @holoscript/cli compile ../examples\demos\collaborative-building.holo --target webgpu
//
// This placeholder shows the expected output structure and demonstrates
// that cross-compilation from .holo to webgpu is supported.

// WebGPU Shaders for CollaborativeBuilding

struct VertexInput {
    @location(0) position: vec3f,
    @location(1) normal: vec3f,
    @location(2) uv: vec2f,
}

struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(0) worldPosition: vec3f,
    @location(1) worldNormal: vec3f,
    @location(2) uv: vec2f,
}

@vertex
fn vertexMain(input: VertexInput) -> VertexOutput {
    var output: VertexOutput;
    // TODO: Implement from collaborative-building.holo
    return output;
}

@fragment
fn fragmentMain(input: VertexOutput) -> @location(0) vec4f {
    // TODO: Implement from collaborative-building.holo
    return vec4f(1.0, 1.0, 1.0, 1.0);
}
