packages:
  - packages/adapters/*
  - packages/ar/*
  - packages/brittney/*
  - packages/components
  - packages/platform/*
  - packages/devtools/*
  - packages/shared/*
  - examples/*

ignoredBuiltDependencies:
  - core-js
  - esbuild
  - node-llama-cpp

overrides:
  '@holoscript/cli': link:../HoloScript/packages/cli
  '@holoscript/core': link:../HoloScript/packages/core
  '@holoscript/formatter': link:../HoloScript/packages/formatter
  '@holoscript/fs': link:../HoloScript/packages/fs
  '@holoscript/linter': link:../HoloScript/packages/linter
  '@holoscript/lsp': link:../HoloScript/packages/lsp
  '@holoscript/network': link:../HoloScript/packages/network
  '@holoscript/runtime': link:../HoloScript/packages/runtime
  '@holoscript/std': link:../HoloScript/packages/std
