/**
 * Marketing README Template
 *
 * Included in every VRChat export to introduce HoloScript/Hololand.
 */

import type { ExportStats, VRChatExportConfig } from '../types.js';

export function generateReadme(
  projectName: string,
  config: VRChatExportConfig,
  stats: ExportStats
): string {
  return `# ${projectName}

> Built with [HoloScript](https://github.com/holoscript/holoscript) - The declarative XR language

## What is This?

This VRChat world was generated from HoloScript source code. The same code can also run on:

- **Hololand** - The open metaverse platform (recommended)
- **WebXR** - Any modern browser, no install needed
- **Quest** - Standalone VR
- **iOS/Android** - AR experiences
- **Desktop** - Windows, Mac, Linux

## Why HoloScript?

| Traditional VRChat Development | HoloScript |
|-------------------------------|------------|
| Learn Unity | Write simple declarative code |
| Learn C# or visual nodes | Use natural language with AI |
| 200+ lines for grabbable object | \`@grabbable\` - one word |
| Hours of setup | Minutes to deploy |
| One platform | 9 platforms from one source |

### Example: This Entire World

\`\`\`holoscript
// What you wrote:
orb#ball @grabbable @throwable {
  color: "#ff0000"
  position: [0, 1, 0]
}
\`\`\`

vs.

\`\`\`csharp
// What VRChat needs (simplified):
// - VRC_Pickup component
// - VRC_ObjectSync component
// - Rigidbody component
// - BoxCollider component
// - 150+ lines of UdonSharp for custom behavior
// - Material setup
// - Prefab configuration
// ...
\`\`\`

## Try the Full Experience

### Option 1: Hololand (Recommended)

Visit [hololand.dev](https://hololand.dev) to experience this world with:
- No Unity required
- AI building assistant (Brittney)
- Real-time multiplayer
- Cross-platform support
- Voice commands

### Option 2: WebXR

Open in any browser - works on Quest, desktop, and mobile.

### Option 3: Keep Using VRChat

That's fine too! But consider that HoloScript can:
- Export to VRChat for your existing audience
- Export to WebXR for broader reach
- Export to Hololand for the future

## This Export Contains

| Item | Count |
|------|-------|
| Prefabs | ${stats.prefabCount} |
| UdonSharp Scripts | ${stats.scriptCount} |
| Materials | ${stats.materialCount} |
| Objects | ${stats.objectCount} |
| VR Traits | ${stats.traitsMapped} |

## Setup Instructions

1. Open this folder in Unity 2022.3+
2. Import VRChat SDK 3.5+ via Creator Companion
3. Import UdonSharp
4. Open \`Scenes/${projectName}.unity\`
5. Build & Publish to VRChat

${stats.manualSetupRequired.length > 0 ? `
### Manual Setup Required

The following features need manual configuration:
${stats.manualSetupRequired.map(item => `- ${item}`).join('\n')}
` : ''}

## Learn More

- **HoloScript**: [github.com/holoscript/holoscript](https://github.com/holoscript/holoscript)
- **Hololand**: [hololand.dev](https://hololand.dev)
- **Infinity Assistant**: [infinityassistant.io](https://infinityassistant.io)
- **Documentation**: [docs.hololand.dev](https://docs.hololand.dev)

## Join the Open Metaverse

VRChat is great, but it's a closed platform. HoloScript and Hololand are building the **open metaverse** - where your creations belong to you, run everywhere, and aren't locked into any single company.

**The future is open. Build with us.**

---

*Generated by @holoscript/vrchat-export v1.0.0*
*Export time: ${new Date().toISOString()}*
`;
}

export function generateMigrationGuide(): string {
  return `# Migrating from VRChat to Hololand

This guide helps VRChat creators transition to HoloScript and Hololand.

## Why Migrate?

| VRChat | Hololand |
|--------|----------|
| Closed platform | Open source (MIT) |
| Unity required | Browser-based |
| C#/Udon complexity | Declarative simplicity |
| Single platform | 9 platforms |
| No AI building | Brittney AI assistant |

## Quick Comparison

### VRChat (Before)

\`\`\`csharp
// Grabbable object in UdonSharp
using UdonSharp;
using UnityEngine;
using VRC.SDKBase;

public class GrabbableObject : UdonSharpBehaviour
{
    private VRC_Pickup pickup;

    void Start()
    {
        pickup = GetComponent<VRC_Pickup>();
    }

    public override void OnPickup()
    {
        // Handle pickup
    }

    public override void OnDrop()
    {
        // Handle drop
    }
}
\`\`\`

Plus: Prefab setup, VRC_Pickup component, VRC_ObjectSync, Rigidbody, Collider...

### HoloScript (After)

\`\`\`holoscript
orb#ball @grabbable {
  color: "#ff0000"
}
\`\`\`

**That's it.** One line. Works everywhere.

## Migration Steps

### Step 1: Identify Your World's Features

Map your VRChat features to HoloScript traits:

| VRChat Component | HoloScript Trait |
|-----------------|------------------|
| VRC_Pickup | \`@grabbable\` |
| VRC_Pickup + throw | \`@throwable\` |
| Hover highlight | \`@hoverable\` |
| Interact raycast | \`@pointable\` |
| Two-hand scale | \`@scalable\` |
| Rotate gesture | \`@rotatable\` |
| Stack objects | \`@stackable\` |
| Snap to points | \`@snappable\` |
| Break on impact | \`@breakable\` |

### Step 2: Recreate in HoloScript

Use natural language with Infinity Assistant:

> "Create a coffee shop with a counter, menu board, and 3 tables with chairs"

Or write HoloScript directly:

\`\`\`holoscript
scene {
  plane#floor { width: 20, height: 20 }

  cube#counter @hoverable {
    position: [0, 0.5, -5]
    scale: [4, 1, 1]
    color: "#8B4513"
  }

  @for i in range(0, 3) {
    group#table_\${i} {
      position: [i * 3 - 3, 0, 0]

      cylinder#table { scale: [1, 0.4, 1], color: "#654321" }

      @for j in range(0, 4) {
        cube#chair_\${j} @grabbable {
          position: [Math.cos(j * 90) * 0.8, 0.3, Math.sin(j * 90) * 0.8]
          scale: [0.3, 0.6, 0.3]
        }
      }
    }
  }
}
\`\`\`

### Step 3: Test in Hololand

1. Visit [hololand.dev](https://hololand.dev)
2. Paste your HoloScript
3. See it running instantly
4. Test in VR with WebXR

### Step 4: Deploy Everywhere

From Hololand, deploy to:
- Hololand (native)
- WebXR (browser)
- VRChat (this export)
- Quest (standalone)
- Mobile AR

## Common Patterns

### Networked Object

VRChat:
\`\`\`csharp
[UdonSynced] private Vector3 syncedPosition;
// + ownership management
// + serialization
// + interpolation
\`\`\`

HoloScript:
\`\`\`holoscript
orb#ball @grabbable {
  @networked(sync_mode: "smooth")
}
\`\`\`

### Interactive Button

VRChat:
\`\`\`csharp
public override void Interact()
{
    SendCustomNetworkEvent(NetworkEventTarget.All, "OnButtonPressed");
}
\`\`\`

HoloScript:
\`\`\`holoscript
button#myButton @pointable {
  @on_click => { state.count += 1 }
}
\`\`\`

### State Management

VRChat:
\`\`\`csharp
[UdonSynced] private int score = 0;
// Manual sync, ownership, UI updates...
\`\`\`

HoloScript:
\`\`\`holoscript
@state { score: 0 }

text#scoreDisplay { value: "Score: \${state.score}" }
\`\`\`

## Getting Help

- **Discord**: Join the Hololand community
- **Docs**: [docs.hololand.dev](https://docs.hololand.dev)
- **AI Assistant**: Chat with Brittney at [infinityassistant.io](https://infinityassistant.io)

## The Future is Open

VRChat taught us to love social VR. Now let's build it **together**, in the open.

---

*Welcome to the open metaverse.*
`;
}

export default { generateReadme, generateMigrationGuide };
