#!/usr/bin/env node
/**
 * HoloShell — compile the chat surface to standalone HTML
 * @generated by HoloScript source-contract compile bridge
 *
 * Usage: node packages/holoshell/compile.mjs  (from Hololand root)
 * Output: packages/holoshell/dist/operate-room.html
 *
 * Source: packages/holoshell/scenes/operate-room.holo
 * Runtime data tier: serve.mjs (localhost:8747)
 *
 * SURFACE = CHAT (founder 2026-06-16: "I don't want data, I just want to chat
 * with the LLM; the data gets processed by the agents"). HoloShell is the
 * assistant/management surface — you TALK to Brittney (and the Daimon, D.053,
 * which manifests THROUGH her via the rehydration channel, not as a panel). The
 * machine-local data (worktree health, stale processes, consents, substrate
 * pressure) is still collected by serve.mjs's /api/* endpoints for AGENTS to
 * process in the background — it is no longer rendered to the founder as
 * dashboard panels. Brittney surfaces only what matters, conversationally.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(__dirname, 'dist');

// ── AST helpers ───────────────────────────────────────────────────────────────

function t(name, config) {
  return { type: 'ObjectTrait', name, config };
}

function obj(name, traits, children = []) {
  return { type: 'Object', name, properties: [], traits, children };
}

// ── Composition: one full-height chat with Brittney ─────────────────────────────
// Header (who you're talking to) + a chat panel that fills the viewport. The
// interactive DOM (messages / input / send) is built by the injected runtime
// helper; this compile bridge renders the shell + the mount point.

const composition = {
  type: 'Composition',
  name: 'OperateRoom',
  objects: [
    obj('root', [
      t('theme', {
        tag: 'div',
        id: 'holoshell-root',
        style: 'height:100vh;display:flex;flex-direction:column;max-width:900px;margin:0 auto;padding:20px;box-sizing:border-box',
      }),
      t('layout', { flex: 'column', gap: 14 }),
    ], [
      obj('header', [
        t('theme', {
          tag: 'header',
          style: 'display:flex;align-items:baseline;gap:12px;padding-bottom:14px;border-bottom:1px solid #30363d;flex:0 0 auto',
        }),
      ], [
        obj('title', [t('text', { variant: 'h1', content: 'HoloShell' })]),
        obj('subtitle', [
          t('theme', { tag: 'span', style: 'color:#6e7681;font-size:13px;font-family:system-ui,sans-serif' }),
          t('text', { content: 'chat with Brittney & Daimon — agents handle the data' }),
        ]),
      ]),
      // The chat fills everything below the header.
      obj('chat', [
        t('theme', { tag: 'main', id: 'brittney-chat-mount', style: 'flex:1 1 auto;display:flex;flex-direction:column;min-height:0' }),
      ]),
    ]),
  ],
  templates: [],
  spatialGroups: [],
  lights: [],
  imports: [],
  timelines: [],
  audio: [],
  zones: [],
  transitions: [],
  conditionals: [],
  iterators: [],
  npcs: [],
  quests: [],
  abilities: [],
  dialogues: [],
  stateMachines: [],
  achievements: [],
  talentTrees: [],
  shapes: [],
  state: { type: 'State', properties: [] },
  environment: {
    properties: [
      { key: 'theme', value: 'dark' },
      { key: 'backgroundColor', value: '#0d1117' },
    ],
  },
};

// ── Compile ───────────────────────────────────────────────────────────────────

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (char) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[char]));
}

function compileOperateRoomShell(holoComposition) {
  const title = escapeHtml(holoComposition?.name || 'OperateRoom');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title} - HoloShell</title>
  <style>
    :root {
      color-scheme: dark;
      background: #0d1117;
      color: #c9d1d9;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }
    * { box-sizing: border-box; }
    html, body { margin: 0; min-height: 100%; background: #0d1117; }
    #holoshell-root {
      height: 100vh;
      display: flex;
      flex-direction: column;
      max-width: 900px;
      margin: 0 auto;
      padding: 20px;
    }
    header {
      display: flex;
      align-items: baseline;
      gap: 12px;
      padding-bottom: 14px;
      border-bottom: 1px solid #30363d;
      flex: 0 0 auto;
    }
    h1 {
      margin: 0;
      font-size: 26px;
      font-weight: 700;
      line-height: 1.15;
    }
    header span {
      color: #6e7681;
      font-size: 13px;
    }
    #brittney-chat-mount {
      flex: 1 1 auto;
      display: flex;
      flex-direction: column;
      min-height: 0;
    }
  </style>
</head>
<body>
  <div id="holoshell-root">
    <header>
      <h1>HoloShell</h1>
      <span>chat with Brittney &amp; Daimon - agents handle the data</span>
    </header>
    <main id="brittney-chat-mount"></main>
  </div>
</body>
</html>`;
}

let html = compileOperateRoomShell(composition);

// Inject the chat runtime before </body>. Brittney routes through
// POST /api/brittney/chat (the real operator loop, fleet-routed across both
// owned GPUs, $0). Action proposals come back inline — Brittney proposes,
// you read them in the conversation; no dashboard.
const runtimeScript = `  <script>
    /* HoloShell — Brittney chat (the whole surface) */
    var _lastImprovementRunId = null;
    function _bMsg(who, text, color) {
      var box = document.getElementById('brittney-messages'); if (!box) return null;
      var row = document.createElement('div');
      row.style.cssText = 'margin-bottom:12px;font-size:14px;line-height:1.55;font-family:system-ui,sans-serif';
      var label = document.createElement('span');
      label.style.cssText = 'color:' + color + ';font-weight:600'; label.textContent = who + ': ';
      var span = document.createElement('span');
      span.style.cssText = 'color:#c9d1d9;white-space:pre-wrap'; span.textContent = text;
      row.appendChild(label); row.appendChild(span);
      box.appendChild(row); box.scrollTop = box.scrollHeight; return row;
    }
    function sendBrittneyChat() {
      var inp = document.getElementById('brittney-input'); if (!inp) return;
      var msg = inp.value.trim(); if (!msg) return;
      inp.value = ''; _bMsg('You', msg, '#58a6ff');
      var pending = _bMsg('Brittney', 'thinking…', '#bc8cff');
      fetch('/api/brittney/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: msg }) })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (pending && pending.parentNode) pending.parentNode.removeChild(pending);
          if (d.error) { _bMsg('Brittney', 'error: ' + d.error, '#f85149'); return; }
          _bMsg('Brittney', d.reply, '#bc8cff');
          if (d.desktopControl) {
            _bMsg('Desktop control', d.desktopControl.status + ' via ' + d.desktopControl.modelLane + ' (' + d.desktopControl.recommendedModel + ')\\n' + d.desktopControl.permissionEnvelope + ' - ' + d.desktopControl.nextSafeStep, '#3fb950');
          }
          if (d.proposals && d.proposals.length) {
            var lines = d.proposals.map(function(x) { return '• ' + x.operation + (x.lane ? ' [' + x.lane + ']' : ''); }).join('\\n');
            _bMsg('Proposed actions', lines, '#3fb950');
          }
        })
        .catch(function(e) { if (pending && pending.parentNode) pending.parentNode.removeChild(pending); _bMsg('Brittney', 'network error: ' + e.message, '#f85149'); });
    }
    function _setImprovementStatus(text, color) {
      var el = document.getElementById('improvement-status'); if (!el) return;
      el.textContent = text; el.style.color = color || '#8b949e';
    }
    function _renderImprovementHistory(items) {
      var box = document.getElementById('improvement-history'); if (!box) return;
      if (!items || !items.length) { box.textContent = 'No runs yet'; return; }
      box.textContent = items.slice(0, 3).map(function(item) {
        return item.runId + ' - ' + item.totalExecutedRunCount + '/' + item.queuedRunCount + ' measured' + (item.remainingRunCount ? ' (' + item.remainingRunCount + ' left)' : '');
      }).join('\\n');
    }
    function _setDesktopBridgeStatus(text) {
      var el = document.getElementById('desktop-bridge-status'); if (!el) return;
      el.textContent = text;
    }
    function _reportLaptopDesktopBridge(report) {
      fetch('/api/desktop-control/bridge/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ report: report })
      }).catch(function() {});
    }
    function _loadServerDesktopBridgeStatus() {
      fetch('/api/desktop-control/bridge')
        .then(function(r) { return r.json(); })
        .then(function(d) {
          _setDesktopBridgeStatus('Bridge: ' + d.status);
        })
        .catch(function() {
          _setDesktopBridgeStatus('Bridge: not reported');
        });
    }
    function _probeLaptopDesktopBridgeAt(urls, index) {
      if (index >= urls.length) { _loadServerDesktopBridgeStatus(); return; }
      fetch(urls[index], { cache: 'no-store' })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.schemaVersion !== 'hololand.holoshell.laptop-desktop-bridge.v0.1.0') {
            _probeLaptopDesktopBridgeAt(urls, index + 1);
            return;
          }
          _setDesktopBridgeStatus('Bridge: ' + d.status + ' (laptop)');
          _reportLaptopDesktopBridge(d);
        })
        .catch(function() {
          _probeLaptopDesktopBridgeAt(urls, index + 1);
        });
    }
    function probeLaptopDesktopBridge() {
      _probeLaptopDesktopBridgeAt([
        'http://127.0.0.1:8751/api/desktop-control/bridge',
        'http://127.0.0.1:8752/api/desktop-control/bridge',
        'http://127.0.0.1:8753/api/desktop-control/bridge'
      ], 0);
    }
    function loadImprovementRuns() {
      fetch('/api/improvement-runs')
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.error) { _setImprovementStatus('History error: ' + d.error, '#f85149'); return; }
          if (d.items && d.items.length) _lastImprovementRunId = d.items[0].runId;
          _renderImprovementHistory(d.items || []);
        })
        .catch(function(e) { _setImprovementStatus('History network error: ' + e.message, '#f85149'); });
      probeLaptopDesktopBridge();
    }
    function executeLatestImprovementRun() {
      if (!_lastImprovementRunId) { _setImprovementStatus('Queue or refresh a run first', '#d29922'); return; }
      _setImprovementStatus('Executing shakedown...', '#d29922');
      fetch('/api/improvement-runs/' + encodeURIComponent(_lastImprovementRunId) + '/execute', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ shakedownCount: 10 })
      })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.error) { _setImprovementStatus('Execute error: ' + d.error, '#f85149'); return; }
          _setImprovementStatus('Measured ' + d.totalExecutedRunCount + ' run(s); ' + d.remainingRunCount + ' left', '#3fb950');
          _bMsg('Improvement execution', d.status + ' - ' + d.executedRunCount + ' measured in this batch; ' + d.remainingRunCount + ' left\\nVision/GPU: ' + d.gpuBalancePlan.localGpu.summary + '\\nDesktop bridge: ' + d.desktopBridge.status + '\\nNext: ' + d.nextSafeStep, '#3fb950');
          if (d.lessons && d.lessons.length) _bMsg('Lessons', d.lessons.slice(0, 4).join('\\n'), '#3fb950');
          loadImprovementRuns();
        })
        .catch(function(e) { _setImprovementStatus('Execute network error: ' + e.message, '#f85149'); });
    }
    function queueImprovementRun() {
      var objectiveInput = document.getElementById('improvement-objective');
      var countInput = document.getElementById('improvement-count');
      if (!objectiveInput || !countInput) return;
      var objective = objectiveInput.value.trim() || 'Improve HoloShell through the native Brittney run loop';
      var runCount = parseInt(countInput.value || '10', 10);
      if (!Number.isFinite(runCount)) runCount = 10;
      runCount = Math.max(1, Math.min(128, runCount));
      _setImprovementStatus('Queueing...', '#d29922');
      fetch('/api/improvement-runs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ objective: objective, runCount: runCount })
      })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.error) { _setImprovementStatus('Error: ' + d.error, '#f85149'); return; }
          _lastImprovementRunId = d.runId;
          _setImprovementStatus('Queued ' + d.queuedRunCount + ' run(s): ' + d.runId, '#3fb950');
          _bMsg('Improvement run', 'Queued ' + d.queuedRunCount + ' run(s) for: ' + d.objective + '\\n' + d.routingSummary + '\\nNext: ' + d.nextSafeStep, '#3fb950');
          if (d.proposals && d.proposals.length) {
            var lines = d.proposals.map(function(x) { return '- ' + x.operation + (x.lane ? ' [' + x.lane + ']' : ''); }).join('\\n');
            _bMsg('Run proposals', lines, '#3fb950');
          }
          loadImprovementRuns();
        })
        .catch(function(e) { _setImprovementStatus('Network error: ' + e.message, '#f85149'); });
    }
    function initBrittneyChat() {
      var mount = document.getElementById('brittney-chat-mount'); if (!mount) return;
      mount.innerHTML =
        '<div id="improvement-run-panel" style="flex:0 0 auto;margin:14px 0 0 0;padding:12px;border:1px solid #30363d;border-radius:8px;background:#0d1117">' +
        '<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px">' +
        '<strong style="font-size:13px;color:#c9d1d9;font-weight:650">Improvement Runs</strong>' +
        '<span id="improvement-status" style="font-size:12px;color:#8b949e;text-align:right">Idle</span>' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:minmax(180px,1fr) 78px 86px 86px 78px;gap:8px">' +
        '<input id="improvement-objective" placeholder="Objective" style="min-width:0;padding:10px 11px;border-radius:8px;border:1px solid #30363d;background:#161b22;color:#c9d1d9;font-size:13px" />' +
        '<input id="improvement-count" type="number" min="1" max="128" value="10" aria-label="Run count" style="width:78px;padding:10px 9px;border-radius:8px;border:1px solid #30363d;background:#161b22;color:#c9d1d9;font-size:13px" />' +
        '<button id="improvement-queue" style="min-width:86px;padding:10px 12px;border-radius:8px;border:none;background:#1f6feb;color:#fff;font-weight:650;cursor:pointer">Queue</button>' +
        '<button id="improvement-execute" style="min-width:86px;padding:10px 12px;border-radius:8px;border:none;background:#238636;color:#fff;font-weight:650;cursor:pointer">Run 10</button>' +
        '<button id="improvement-refresh" style="min-width:78px;padding:10px 10px;border-radius:8px;border:1px solid #30363d;background:#161b22;color:#c9d1d9;font-weight:650;cursor:pointer">Refresh</button>' +
        '</div>' +
        '<div id="desktop-bridge-status" style="margin-top:8px;font-size:12px;color:#8b949e">Bridge: checking...</div>' +
        '<pre id="improvement-history" style="margin:8px 0 0 0;min-height:36px;white-space:pre-wrap;color:#8b949e;font-size:12px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace">No runs yet</pre>' +
        '</div>' +
        '<div id="brittney-messages" style="flex:1 1 auto;min-height:0;overflow-y:auto;padding:16px;background:#0d1117;border:1px solid #30363d;border-radius:12px;margin:14px 0"></div>' +
        '<div style="display:flex;gap:8px;flex:0 0 auto">' +
        '<input id="brittney-input" placeholder="Talk to Brittney — she manages the system, agents do the data work…" style="flex:1;padding:13px 14px;border-radius:10px;border:1px solid #30363d;background:#161b22;color:#c9d1d9;font-size:14px" />' +
        '<button id="brittney-send" style="padding:13px 22px;border-radius:10px;border:none;background:#238636;color:#fff;font-weight:600;cursor:pointer">Send</button>' +
        '</div>';
      document.getElementById('brittney-send').addEventListener('click', sendBrittneyChat);
      document.getElementById('improvement-queue').addEventListener('click', queueImprovementRun);
      document.getElementById('improvement-execute').addEventListener('click', executeLatestImprovementRun);
      document.getElementById('improvement-refresh').addEventListener('click', loadImprovementRuns);
      document.getElementById('brittney-input').addEventListener('keydown', function(e) { if (e.key === 'Enter') sendBrittneyChat(); });
      document.getElementById('improvement-objective').addEventListener('keydown', function(e) { if (e.key === 'Enter') queueImprovementRun(); });
      document.getElementById('brittney-input').focus();
      _bMsg('Brittney', 'Online — routed across both owned GPUs ($0). Just talk to me; I manage the system and hand the data work to the agents. The Daimon\\u2019s remembered context rides along when it has emerged (D.053).', '#bc8cff');
      loadImprovementRuns();
    }
    document.addEventListener('DOMContentLoaded', initBrittneyChat);
  </script>`;

html = html.replace('</body>', runtimeScript + '\n</body>');

mkdirSync(DIST_DIR, { recursive: true });
const outPath = join(DIST_DIR, 'operate-room.html');
writeFileSync(outPath, html, 'utf8');
console.log('Compiled (chat surface):', outPath);
