#!/usr/bin/env node
/**
 * HoloShell — compile the chat surface to standalone HTML
 * @generated by HoloScript source-contract compile bridge
 *
 * Usage: node packages/holoshell/compile.mjs  (from Hololand root)
 * Output: packages/holoshell/dist/operate-room.html
 *
 * Source: packages/holoshell/scenes/operate-room.holo
 * Runtime data tier: serve.mjs (localhost:8747)
 *
 * SURFACE = CHAT + COMPACT COCKPIT (founder 2026-06-16: "I don't want data, I just want to chat
 * with the LLM; the data gets processed by the agents"). HoloShell is the
 * assistant/management surface — you TALK to Brittney (and the Daimon, D.053,
 * which manifests THROUGH her via the rehydration channel, not as a panel). The
 * machine-local data (worktree health, stale processes, consents, substrate
 * pressure) is still collected by serve.mjs's /api/* endpoints for AGENTS to
 * process in the background — it is no longer rendered to the founder as
 * dashboard panels. Brittney surfaces only what matters, conversationally.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(__dirname, 'dist');

// ── AST helpers ───────────────────────────────────────────────────────────────

function t(name, config) {
  return { type: 'ObjectTrait', name, config };
}

function obj(name, traits, children = []) {
  return { type: 'Object', name, properties: [], traits, children };
}

// ── Composition: compact cockpit plus full-height chat with Brittney ────────────
// Header (who you're talking to) + a compact cockpit and chat panel. The
// interactive DOM is built by the injected runtime helper; this compile bridge
// renders the shell + the mount point.

const composition = {
  type: 'Composition',
  name: 'OperateRoom',
  objects: [
    obj('root', [
      t('theme', {
        tag: 'div',
        id: 'holoshell-root',
        style: 'height:100vh;display:flex;flex-direction:column;max-width:1120px;margin:0 auto;padding:20px;box-sizing:border-box',
      }),
      t('layout', { flex: 'column', gap: 14 }),
    ], [
      obj('header', [
        t('theme', {
          tag: 'header',
          style: 'display:flex;align-items:baseline;gap:12px;padding-bottom:14px;border-bottom:1px solid #30363d;flex:0 0 auto',
        }),
      ], [
        obj('title', [t('text', { variant: 'h1', content: 'HoloShell' })]),
        obj('subtitle', [
          t('theme', { tag: 'span', style: 'color:#6e7681;font-size:13px;font-family:system-ui,sans-serif' }),
          t('text', { content: 'chat with Brittney & Daimon — agents handle the data' }),
        ]),
      ]),
      // The chat fills everything below the header.
      obj('chat', [
        t('theme', { tag: 'main', id: 'brittney-chat-mount', style: 'flex:1 1 auto;display:flex;flex-direction:column;min-height:0' }),
      ]),
    ]),
  ],
  templates: [],
  spatialGroups: [],
  lights: [],
  imports: [],
  timelines: [],
  audio: [],
  zones: [],
  transitions: [],
  conditionals: [],
  iterators: [],
  npcs: [],
  quests: [],
  abilities: [],
  dialogues: [],
  stateMachines: [],
  achievements: [],
  talentTrees: [],
  shapes: [],
  state: { type: 'State', properties: [] },
  environment: {
    properties: [
      { key: 'theme', value: 'dark' },
      { key: 'backgroundColor', value: '#0d1117' },
    ],
  },
};

// ── Compile ───────────────────────────────────────────────────────────────────

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (char) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[char]));
}

function compileOperateRoomShell(holoComposition) {
  const title = escapeHtml(holoComposition?.name || 'OperateRoom');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title} - HoloShell</title>
  <style>
    :root {
      color-scheme: dark;
      background: #0d1117;
      color: #c9d1d9;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }
    * { box-sizing: border-box; }
    html, body { margin: 0; min-height: 100%; background: #0d1117; }
    #holoshell-root {
      height: 100vh;
      display: flex;
      flex-direction: column;
      max-width: 1120px;
      margin: 0 auto;
      padding: 20px;
    }
    header {
      display: flex;
      align-items: baseline;
      gap: 12px;
      padding-bottom: 14px;
      border-bottom: 1px solid #30363d;
      flex: 0 0 auto;
    }
    h1 {
      margin: 0;
      font-size: 26px;
      font-weight: 700;
      line-height: 1.15;
    }
    header span {
      color: #6e7681;
      font-size: 13px;
    }
    .cockpit-grid {
      flex: 0 0 auto;
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 8px;
      margin-top: 14px;
    }
    .cockpit-card {
      min-height: 76px;
      padding: 10px;
      border: 1px solid #30363d;
      border-radius: 8px;
      background: #0d1117;
      overflow: hidden;
    }
    .cockpit-card strong {
      display: block;
      margin-bottom: 5px;
      color: #f0f6fc;
      font-size: 12px;
      line-height: 1.2;
      font-weight: 650;
    }
    .cockpit-card span {
      display: block;
      color: #8b949e;
      font-size: 12px;
      line-height: 1.35;
      overflow-wrap: anywhere;
    }
    .cockpit-action-grid {
      flex: 0 0 auto;
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 8px;
      margin-top: 8px;
    }
    .cockpit-action-card {
      min-height: 42px;
      padding: 8px 10px;
      border-radius: 8px;
      border: 1px solid #30363d;
      background: #161b22;
      color: #c9d1d9;
      font-size: 12px;
      font-weight: 650;
      line-height: 1.2;
      text-align: left;
      cursor: pointer;
      overflow-wrap: anywhere;
    }
    .cockpit-action-card[data-hologate="true"] {
      border-color: #8957e5;
    }
    .cockpit-action-card:disabled {
      cursor: wait;
      opacity: 0.72;
    }
    .operator-state-rail,
    .operator-alerts,
    .operator-card-grid,
    .context-capsule-grid {
      display: grid;
      gap: 8px;
    }
    .operator-state-rail {
      flex: 0 0 auto;
      grid-template-columns: repeat(5, minmax(0, 1fr));
      margin-top: 14px;
    }
    .operator-pill,
    .operator-alert-card,
    .operator-turn-card,
    .context-capsule-panel {
      border: 1px solid #30363d;
      border-radius: 8px;
      background: #0d1117;
    }
    .operator-pill {
      min-height: 66px;
      padding: 10px;
      overflow: hidden;
    }
    .operator-pill[data-tone="ready"],
    .operator-turn-card[data-tone="ready"] {
      border-color: color-mix(in srgb, #3fb950 62%, #30363d);
      background: color-mix(in srgb, #3fb950 8%, #0d1117);
    }
    .operator-pill[data-tone="attention"],
    .operator-alert-card,
    .operator-turn-card[data-tone="attention"] {
      border-color: color-mix(in srgb, #d29922 68%, #30363d);
      background: color-mix(in srgb, #d29922 9%, #0d1117);
    }
    .operator-pill[data-tone="blocked"],
    .operator-turn-card[data-tone="blocked"] {
      border-color: color-mix(in srgb, #f85149 72%, #30363d);
      background: color-mix(in srgb, #f85149 8%, #0d1117);
    }
    .operator-pill strong,
    .operator-alert-card strong,
    .operator-turn-card strong,
    .context-capsule-panel strong {
      display: block;
      color: #f0f6fc;
      font-size: 12px;
      line-height: 1.2;
      font-weight: 700;
    }
    .operator-pill span,
    .operator-alert-card span,
    .operator-turn-card span,
    .context-capsule-panel span {
      display: block;
      margin-top: 4px;
      color: #8b949e;
      font-size: 12px;
      line-height: 1.35;
      overflow-wrap: anywhere;
    }
    .operator-alerts {
      flex: 0 0 auto;
      grid-template-columns: repeat(3, minmax(0, 1fr));
      margin-top: 8px;
    }
    .operator-alerts:empty {
      display: none;
    }
    .operator-alert-card {
      min-height: 74px;
      padding: 10px;
    }
    .operator-alert-card button,
    .operator-turn-card button {
      margin-top: 8px;
      min-height: 30px;
      padding: 0 10px;
      border-radius: 8px;
      border: 1px solid #d29922;
      background: #161b22;
      color: #f0f6fc;
      font-size: 12px;
      font-weight: 700;
      cursor: pointer;
    }
    .context-capsule-panel {
      flex: 0 0 auto;
      margin-top: 8px;
      padding: 10px;
    }
    .context-capsule-grid {
      grid-template-columns: repeat(3, minmax(0, 1fr));
      margin-top: 8px;
    }
    .operator-card-grid {
      grid-template-columns: repeat(2, minmax(0, 1fr));
      margin-top: 8px;
    }
    .operator-turn-card {
      margin: 0 0 12px 0;
      padding: 12px;
      font-family: system-ui, sans-serif;
    }
    .operator-turn-card[data-variant="receipt"] {
      border-style: dashed;
    }
    .operator-card-grid .operator-turn-card {
      margin-bottom: 0;
    }
    .chat-message-row {
      margin-bottom: 12px;
      font-size: 14px;
      line-height: 1.55;
      font-family: system-ui, sans-serif;
    }
    .chat-message-row[data-speaker="You"] {
      margin-left: auto;
      max-width: 86%;
      padding: 10px 12px;
      border: 1px solid color-mix(in srgb, #58a6ff 32%, #30363d);
      border-radius: 8px;
      background: color-mix(in srgb, #58a6ff 9%, #0d1117);
    }
    .improvement-grid {
      display: grid;
      grid-template-columns: minmax(180px, 1fr) 78px 86px 86px 78px;
      gap: 8px;
    }
    @media (max-width: 720px) {
      #holoshell-root {
        padding: 14px;
      }
      header {
        align-items: flex-start;
        flex-direction: column;
        gap: 4px;
      }
      .cockpit-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
      .cockpit-action-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
      .operator-state-rail,
      .operator-alerts,
      .operator-card-grid,
      .context-capsule-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
      .improvement-grid {
        grid-template-columns: minmax(0, 1fr) 76px;
      }
      #improvement-queue,
      #improvement-execute,
      #improvement-refresh {
        min-width: 0;
      }
    }
    #brittney-chat-mount {
      flex: 1 1 auto;
      display: flex;
      flex-direction: column;
      min-height: 0;
    }
  </style>
</head>
<body>
  <div id="holoshell-root">
    <header>
      <h1>HoloShell</h1>
      <span>chat with Brittney &amp; Daimon - agents handle the data</span>
    </header>
    <main id="brittney-chat-mount"></main>
  </div>
</body>
</html>`;
}

let html = compileOperateRoomShell(composition);

// Inject the chat runtime before </body>. Brittney routes through
// POST /api/brittney/chat (the real operator loop, fleet-routed across both
// owned GPUs, $0). Action proposals come back inline — Brittney proposes,
// you read them in the conversation; no dashboard.
const runtimeScript = `  <script>
    /* HoloShell — Brittney chat (the whole surface) */
    var _lastImprovementRunId = null;
    var _lastLaptopDesktopBridgeBaseUrl = null;
    var _laptopDesktopBridgeBases = ['http://127.0.0.1:8751', 'http://127.0.0.1:8752', 'http://127.0.0.1:8753'];
    var _lastCockpitCapsule = null;
    function _bMsg(who, text, color) {
      var box = document.getElementById('brittney-messages'); if (!box) return null;
      var row = document.createElement('div');
      row.className = 'chat-message-row';
      row.dataset.speaker = who;
      var label = document.createElement('span');
      label.style.cssText = 'color:' + color + ';font-weight:600'; label.textContent = who + ': ';
      var span = document.createElement('span');
      span.style.cssText = 'color:#c9d1d9;white-space:pre-wrap'; span.textContent = text;
      row.appendChild(label); row.appendChild(span);
      box.appendChild(row); box.scrollTop = box.scrollHeight; return row;
    }
    function _bActionButton(row, label, onClick) {
      if (!row) return null;
      var spacer = document.createElement('div');
      spacer.style.cssText = 'height:8px';
      var button = document.createElement('button');
      button.type = 'button';
      button.textContent = label;
      button.style.cssText = 'height:34px;padding:0 12px;border-radius:8px;border:1px solid #2ea043;background:#238636;color:#fff;font-weight:700;cursor:pointer';
      button.onclick = function() {
        button.disabled = true;
        button.style.cursor = 'wait';
        onClick(button);
      };
      row.appendChild(spacer);
      row.appendChild(button);
      return button;
    }
    function _shortText(value, fallback) {
      var text = String(value == null || value === '' ? (fallback || 'unknown') : value);
      return text.length > 180 ? text.slice(0, 177) + '...' : text;
    }
    function _toneForStatus(status) {
      var text = String(status || '').toLowerCase();
      if (/(blocked|error|failed|refused|missing|unavailable|critical)/.test(text)) return 'blocked';
      if (/(attention|stale|waiting|pending|partial|not_reported|unknown|needs_refresh)/.test(text)) return 'attention';
      if (/(ready|online|completed|coupled|windows_visible|reported|available|pass|window_preflights_ready|cards_ready)/.test(text)) return 'ready';
      return 'neutral';
    }
    function _makeTextBlock(label, value, detail, tone) {
      var card = document.createElement('div');
      card.className = 'operator-pill';
      card.dataset.tone = tone || _toneForStatus(value);
      var strong = document.createElement('strong');
      strong.textContent = label;
      var span = document.createElement('span');
      span.textContent = _shortText(value);
      card.appendChild(strong);
      card.appendChild(span);
      if (detail) {
        var detailSpan = document.createElement('span');
        detailSpan.textContent = _shortText(detail);
        card.appendChild(detailSpan);
      }
      return card;
    }
    function _makeTurnCard(title, lines, tone, variant) {
      var card = document.createElement('div');
      card.className = 'operator-turn-card';
      card.dataset.tone = tone || 'neutral';
      if (variant) card.dataset.variant = variant;
      var strong = document.createElement('strong');
      strong.textContent = title;
      card.appendChild(strong);
      (lines || []).filter(Boolean).forEach(function(line) {
        var span = document.createElement('span');
        span.textContent = line;
        card.appendChild(span);
      });
      return card;
    }
    function _appendTurnCard(title, lines, tone, variant) {
      var box = document.getElementById('brittney-messages');
      if (!box) return null;
      var card = _makeTurnCard(title, lines, tone, variant);
      box.appendChild(card);
      box.scrollTop = box.scrollHeight;
      return card;
    }
    function _appendCardGrid(cards) {
      var box = document.getElementById('brittney-messages');
      if (!box || !cards || !cards.length) return;
      var grid = document.createElement('div');
      grid.className = 'operator-card-grid';
      cards.forEach(function(card) { grid.appendChild(card); });
      box.appendChild(grid);
      box.scrollTop = box.scrollHeight;
    }
    function _setText(id, text) {
      var el = document.getElementById(id);
      if (el) el.textContent = text;
    }
    function _lane(capsule, id) {
      var lanes = (capsule && capsule.cockpitLanes) || [];
      for (var i = 0; i < lanes.length; i += 1) {
        if (lanes[i].id === id) return lanes[i];
      }
      return null;
    }
    function _laneText(lane) {
      if (!lane) return 'not reported';
      var value = lane.value || lane.status || 'unknown';
      var detail = lane.detail ? ' - ' + lane.detail : '';
      return value + detail;
    }
    function _renderOperatorTruth(capsule) {
      var mount = document.getElementById('operator-state-rail');
      if (!mount) return;
      mount.textContent = '';
      var summary = (capsule && capsule.summary) || {};
      var route = (capsule && capsule.route) || {};
      var avatar = (capsule && capsule.avatar) || {};
      var receipts = (capsule && capsule.receipts) || {};
      var reasoningDetail = [
        'GPU ' + (summary.laptopReasoningGpuStatus || 'unknown'),
        summary.laptopReasoningModelInvocationPerformed ? 'model invoked' : 'receipt-only/model not invoked'
      ].join('; ');
      var facts = [
        {
          label: 'Brittney',
          value: (avatar.name || 'Brittney') + ' ' + (avatar.status || capsule?.status || 'unknown'),
          detail: avatar.runtime || 'runtime not reported',
          tone: _toneForStatus(avatar.status || capsule?.status)
        },
        {
          label: 'Jetson Route',
          value: route.url || 'route not reported',
          detail: route.chatEndpoint || 'chat endpoint not reported',
          tone: _toneForStatus(summary.routeStatus)
        },
        {
          label: 'Reasoning',
          value: summary.laptopReasoningLane || 'laptop-hardware',
          detail: (summary.laptopReasoningStatus || 'unknown') + '; ' + reasoningDetail,
          tone: _toneForStatus(summary.laptopReasoningStatus || summary.laptopReasoningGpuStatus)
        },
        {
          label: 'Receipts',
          value: 'terminal ' + (receipts.operatorTerminalReceiptStatus || summary.operatorTerminalStatus || 'unknown'),
          detail: 'pending ' + (receipts.pendingConsentCount || 0) + '; recent ' + (receipts.recentExecutionCount || 0),
          tone: _toneForStatus(receipts.operatorTerminalReceiptStatus || summary.operatorTerminalStatus)
        },
        {
          label: 'Desktop/Windows',
          value: (summary.desktopBridgeStatus || 'desktop unknown') + ' / ' + (summary.windowAwarenessStatus || 'windows unknown'),
          detail: (summary.toolActionStatus || 'tools unknown'),
          tone: _toneForStatus(summary.desktopBridgeStatus === 'ready' ? summary.windowAwarenessStatus : summary.desktopBridgeStatus)
        }
      ];
      facts.forEach(function(fact) {
        mount.appendChild(_makeTextBlock(fact.label, fact.value, fact.detail, fact.tone));
      });
    }
    function _renderEvidencePrompts(capsule) {
      var mount = document.getElementById('operator-alerts');
      if (!mount) return;
      mount.textContent = '';
      var summary = (capsule && capsule.summary) || {};
      var lanes = {
        desktop: _lane(capsule, 'desktop_bridge') || {},
        terminal: _lane(capsule, 'operator_terminal') || {},
        reasoning: _lane(capsule, 'laptop_reasoning') || {}
      };
      var prompts = [];
      if (_toneForStatus(summary.desktopBridgeStatus || lanes.desktop.status) !== 'ready') {
        prompts.push({
          label: 'Desktop bridge',
          value: lanes.desktop.value || summary.desktopBridgeStatus || 'attention',
          detail: 'Probe the laptop bridge and report the receipt back to Jetson.',
          button: 'Probe bridge',
          action: function() { probeLaptopDesktopBridge(); _bMsg('Evidence refresh', 'Desktop bridge probe requested from the browser surface.', '#d29922'); }
        });
      }
      if (_toneForStatus(summary.operatorTerminalStatus || lanes.terminal.status) !== 'ready') {
        prompts.push({
          label: 'Terminal receipt',
          value: lanes.terminal.value || summary.operatorTerminalStatus || 'attention',
          detail: 'Endpoint inspection is read-only; command refresh remains terminal-side.',
          button: 'Inspect receipt',
          action: _inspectOperatorTerminalSession
        });
      }
      if (_toneForStatus(summary.laptopReasoningStatus || lanes.reasoning.status) !== 'ready') {
        prompts.push({
          label: 'Laptop reasoning',
          value: lanes.reasoning.value || summary.laptopReasoningStatus || 'attention',
          detail: 'Check the current live-status envelope before claiming GPU inference.',
          button: 'Inspect lane',
          action: _inspectLiveStatusForChat
        });
      }
      prompts.slice(0, 3).forEach(function(prompt) {
        var card = document.createElement('div');
        card.className = 'operator-alert-card';
        var strong = document.createElement('strong');
        strong.textContent = prompt.label + ': ' + prompt.value;
        var span = document.createElement('span');
        span.textContent = prompt.detail;
        var button = document.createElement('button');
        button.type = 'button';
        button.textContent = prompt.button;
        button.onclick = prompt.action;
        card.append(strong, span, button);
        mount.appendChild(card);
      });
    }
    function _renderContextCapsule(capsule) {
      var panel = document.getElementById('context-capsule-panel');
      if (!panel) return;
      var template = (capsule && capsule.contextCapsuleTemplate) || {};
      var required = (template.requiredFields || []).join(', ') || 'not reported';
      var identity = (template.identityCarry || []).join(', ') || 'not reported';
      var memory = (template.memoryInputs || []).join(', ') || 'not reported';
      _setText('context-capsule-required', required);
      _setText('context-capsule-identity', identity);
      _setText('context-capsule-memory', memory);
    }
    function _inspectOperatorTerminalSession() {
      fetch('/api/operator-terminal/session', { cache: 'no-store' })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          _appendTurnCard('Terminal evidence', [
            'status: ' + (d.status || 'unknown'),
            'receipt: ' + (d.terminal?.receiptStatus || 'unknown') + (d.terminal?.receiptHash ? ' / ' + d.terminal.receiptHash.slice(0, 12) : ''),
            'next: ' + (d.nextSafeStep || 'not reported')
          ], _toneForStatus(d.status || d.terminal?.receiptStatus), 'receipt');
        })
        .catch(function(e) { _bMsg('Terminal evidence', 'network error: ' + e.message, '#f85149'); });
    }
    function _inspectLiveStatusForChat() {
      fetch('/api/live-status', { cache: 'no-store' })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          var reasoning = d.laptopReasoning || {};
          _appendTurnCard('Laptop reasoning lane', [
            'lane: ' + (reasoning.lane || 'laptop-hardware'),
            'status: ' + (reasoning.status || 'unknown'),
            'gpu: ' + (reasoning.gpuSummary || reasoning.gpuStatus || 'not reported'),
            'model invocation: ' + (reasoning.modelInvocationPerformed ? 'performed' : 'not performed')
          ], _toneForStatus(reasoning.status || reasoning.gpuStatus), 'receipt');
        })
        .catch(function(e) { _bMsg('Laptop reasoning', 'network error: ' + e.message, '#f85149'); });
    }
    function _cardText(card) {
      var action = card.primaryAction || card.lane || card.method || 'action';
      var gate = card.holoGateRequired ? 'HoloGate' : card.permissionEnvelope;
      return card.label + ' - ' + action + ' / ' + gate;
    }
    function _runCockpitActionCard(card, button) {
      var original = button.textContent;
      button.disabled = true;
      button.textContent = 'Planning...';
      var request = card.method === 'POST'
        ? fetch(card.href, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              intent: card.intent || card.label,
              sourceCardId: card.id,
              planOnly: true
            })
          })
        : fetch(card.href, { cache: 'no-store' });
      request
        .then(function(r) { return r.json().then(function(d) { return { ok: r.ok, data: d }; }); })
        .then(function(result) {
          if (!result.ok || result.data.error) throw new Error(result.data.error || 'request_failed');
          var data = result.data;
          var receipt = data.planId || data.receipt?.planId || data.status || 'receipt ready';
          button.textContent = 'Receipt';
          _bMsg('Cockpit card', card.label + '\\n' + receipt + '\\n' + (card.preflightPath ? card.preflightPath.requiredSequence.join(' -> ') : card.permissionEnvelope), '#3fb950');
        })
        .catch(function(e) {
          button.textContent = 'Blocked';
          _bMsg('Cockpit card', card.label + ' blocked: ' + e.message, '#f85149');
        })
        .finally(function() {
          setTimeout(function() {
            button.disabled = false;
            button.textContent = original;
          }, 1200);
        });
    }
    function _renderCockpitActionCards(capsule) {
      var mount = document.getElementById('cockpit-action-cards');
      if (!mount) return;
      mount.textContent = '';
      var cards = ((capsule && capsule.actionCards) || []).filter(function(card) {
        return card && (card.primaryAction || card.id === 'desktop_control_plan' || card.id === 'context_capsule' || card.id === 'laptop_reasoning_status');
      }).slice(0, 8);
      if (!cards.length) {
        mount.textContent = 'no cards reported';
        return;
      }
      cards.forEach(function(card) {
        var button = document.createElement('button');
        button.type = 'button';
        button.className = 'cockpit-action-card';
        button.dataset.cardId = card.id || '';
        button.dataset.hologate = card.holoGateRequired ? 'true' : 'false';
        button.title = _cardText(card);
        button.textContent = card.label || card.id || 'Action';
        button.onclick = function() { _runCockpitActionCard(card, button); };
        mount.appendChild(button);
      });
    }
    function _renderCockpitCapsule(capsule) {
      _lastCockpitCapsule = capsule;
      _renderOperatorTruth(capsule);
      _renderEvidencePrompts(capsule);
      _renderContextCapsule(capsule);
      _setText('cockpit-runtime', _laneText(_lane(capsule, 'runtime_truth')));
      _setText('cockpit-routes', _laneText(_lane(capsule, 'route_health')));
      _setText('cockpit-context', _laneText(_lane(capsule, 'context_carry')));
      _setText('cockpit-desktop', _laneText(_lane(capsule, 'desktop_bridge')));
      _setText('cockpit-reasoning', _laneText(_lane(capsule, 'laptop_reasoning')));
      _setText('cockpit-windows', _laneText(_lane(capsule, 'window_awareness')));
      _setText('cockpit-terminal', _laneText(_lane(capsule, 'operator_terminal')));
      var cards = (capsule && capsule.actionCards) || [];
      _setText('cockpit-actions', cards.slice(0, 4).map(function(card) { return card.label + ' [' + card.permissionEnvelope + ']'; }).join(' | ') || 'no cards reported');
      _renderCockpitActionCards(capsule);
    }
    function loadCockpitCapsule() {
      fetch('/api/cockpit/capsule', { cache: 'no-store' })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.error) {
            _setText('cockpit-runtime', 'error: ' + d.error);
            return;
          }
          _renderCockpitCapsule(d);
        })
        .catch(function(e) {
          _setText('cockpit-runtime', 'network error: ' + e.message);
        });
    }
    function _bridgeUrls(path) {
      var bases = _laptopDesktopBridgeBases.slice();
      if (_lastLaptopDesktopBridgeBaseUrl) bases.unshift(_lastLaptopDesktopBridgeBaseUrl);
      var seen = {};
      return bases.map(function(base) {
        return String(base).replace(/\\/$/, '') + path;
      }).filter(function(url) {
        if (seen[url]) return false;
        seen[url] = true;
        return true;
      });
    }
    function _postLaptopBridge(path, body, index) {
      var urls = _bridgeUrls(path);
      var offset = index || 0;
      if (offset >= urls.length) return Promise.reject(new Error('laptop_desktop_bridge_unavailable'));
      return fetch(urls[offset], {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'X-HoloShell-Bridge': 'browser' },
        body: JSON.stringify(body || {})
      }).then(function(r) {
        return r.text().then(function(text) {
          var data = {};
          try { data = text ? JSON.parse(text) : {}; } catch (e) { data = { raw: text }; }
          if (r.ok) {
            _lastLaptopDesktopBridgeBaseUrl = urls[offset].slice(0, -path.length);
            return data;
          }
          if (r.status === 404) return _postLaptopBridge(path, body, offset + 1);
          var err = new Error(data.error || data.reason || data.blockedReason || ('http_' + r.status));
          err.holoshellNoRetry = true;
          throw err;
        });
      }).catch(function(e) {
        if (e && e.holoshellNoRetry) throw e;
        return _postLaptopBridge(path, body, offset + 1);
      });
    }
    function _extractPublicOpenUrl(text) {
      var match = String(text || '').match(/https?:\\/\\/[^\\s<>"')]+/i);
      if (!match) return { status: 'missing_url' };
      var raw = match[0].replace(/[.,;:!?]+$/, '');
      var parsed;
      try { parsed = new URL(raw); } catch (e) { return { status: 'invalid_url' }; }
      if (!/^https?:$/i.test(parsed.protocol)) return { status: 'blocked_scheme' };
      var combined = (parsed.hostname + ' ' + parsed.pathname + ' ' + parsed.search).toLowerCase();
      if (/(checkout|payment|billing|purchase|subscribe|transfer|wallet|bank)/i.test(combined)) return { status: 'break_glass_payment' };
      if (/(login|signin|sign-in|account|settings|profile|admin|oauth|auth|password|security|2fa|mfa|upload|download|export|import|delete|remove|submit|compose|send)/i.test(combined)) return { status: 'credential_adjacent' };
      return { status: 'public_web', url: parsed.href, host: parsed.host };
    }
    function _offerDesktopOpenUrl(intent, desktopControl) {
      if (!desktopControl || desktopControl.primaryAction !== 'open_url') return;
      var target = _extractPublicOpenUrl(String(intent || '') + ' ' + String(desktopControl.intent || ''));
      if (target.status !== 'public_web') {
        _bMsg('Desktop execution', 'open_url blocked before approval: ' + target.status, '#f85149');
        return;
      }
      if (desktopControl.permissionEnvelope === 'break_glass') {
        _bMsg('Desktop execution', 'open_url requires founder review before approval.', '#f85149');
        return;
      }
      var row = _bMsg('Desktop approval', 'Public URL ready: ' + target.url + '\\nRequires approval: click here, then press F8 for the challenge-bound gesture proof.', '#d29922');
      _bActionButton(row, 'Approve open URL', function(button) {
        var preflightReceipt = null;
        button.textContent = 'Preflighting...';
        _postLaptopBridge('/api/desktop-control/preflight', {
          intent: desktopControl.intent || intent,
          actor: 'brittney'
        }).then(function(preflight) {
          preflightReceipt = preflight;
          if (preflight.intent && preflight.intent.primaryAction && preflight.intent.primaryAction !== 'open_url') {
            throw new Error('preflight_action_mismatch:' + preflight.intent.primaryAction);
          }
          button.textContent = 'Press F8...';
          return _postLaptopBridge('/api/desktop-control/gesture-proof', {
            preflight: preflight,
            operation: 'open_url',
            key: (preflight.consentGesture && preflight.consentGesture.key) || 'F8',
            ttlMs: (preflight.consentGesture && preflight.consentGesture.ttlMs) || 30000
          });
        }).then(function(gestureProof) {
          button.textContent = 'Opening...';
          return _postLaptopBridge('/api/desktop-control/consent-token', {
            preflight: preflightReceipt,
            operation: 'open_url',
            gestureProof: gestureProof
          });
        }).then(function(consentToken) {
          return _postLaptopBridge('/api/desktop-control/execute', {
            preflight: preflightReceipt,
            operation: 'open_url',
            consentToken: consentToken,
            url: target.url,
            executeApprovedAction: true
          });
        }).then(function(execution) {
          button.textContent = 'Opened';
          button.style.cursor = 'default';
          var receipt = execution.receiptPath || execution.executionId || 'receipt unavailable';
          _bMsg('Desktop execution', (execution.status || 'completed') + '\\n' + (execution.executionMode || 'admitted_open_url_executor') + '\\nReceipt: ' + receipt, '#3fb950');
        }).catch(function(e) {
          button.disabled = false;
          button.style.cursor = 'pointer';
          button.textContent = 'Retry open URL';
          _bMsg('Desktop execution', 'refused: ' + e.message, '#f85149');
        });
      });
    }
    function _renderSystemStatusCard(systemStatus) {
      if (!systemStatus) return;
      var reasoning = systemStatus.laptopReasoning || {};
      _appendTurnCard('Runtime truth', [
        'status: ' + (systemStatus.status || 'unknown') + '; capabilities: ' + (systemStatus.capabilityCount || 0),
        'route: ' + (systemStatus.route?.chatEndpoint || 'chat route unknown'),
        'reasoning: ' + (reasoning.lane || 'laptop-hardware') + '; ' + (reasoning.gpuStatus || 'gpu unknown') + '; model ' + (reasoning.modelInvocationPerformed ? 'invoked' : 'not invoked'),
        'receipts: pending ' + (systemStatus.pendingConsentCount || 0) + '; recent ' + (systemStatus.recentExecutionCount || 0)
      ], _toneForStatus(systemStatus.status));
    }
    function _renderDesktopControlCard(desktopControl) {
      if (!desktopControl) return;
      _appendTurnCard('Desktop control plan', [
        'action: ' + (desktopControl.primaryAction || 'unknown'),
        'lane: ' + (desktopControl.modelLane || 'unknown') + '; model: ' + (desktopControl.recommendedModel || 'unknown'),
        'permission: ' + (desktopControl.permissionEnvelope || 'unknown') + '; approval: ' + (desktopControl.approvalRequired ? 'required' : 'not required'),
        'next: ' + (desktopControl.nextSafeStep || 'not reported')
      ], _toneForStatus(desktopControl.status || desktopControl.permissionEnvelope));
    }
    function _renderProposalCards(proposals) {
      if (!proposals || !proposals.length) return;
      var cards = proposals.slice(0, 6).map(function(proposal) {
        return _makeTurnCard('Proposal: ' + (proposal.operation || 'action'), [
          'lane: ' + (proposal.lane || 'not specified'),
          'permission: ' + (proposal.permissionEnvelope || proposal.approvalRequired || 'classified by intent'),
          'receipt: ' + (proposal.receiptRequired === false ? 'not required' : 'required')
        ], proposal.receiptRequired === false ? 'attention' : 'ready');
      });
      _appendCardGrid(cards);
    }
    function _renderAgentHandoffCards(proposals) {
      var handoffs = (proposals || []).filter(function(proposal) {
        var text = String((proposal.operation || '') + ' ' + (proposal.lane || '')).toLowerCase();
        return /(dispatch|agent|laptop|reasoning|codex|grok|claude|gemini)/.test(text);
      });
      if (!handoffs.length) return;
      _appendTurnCard('Agent handoff', handoffs.slice(0, 3).map(function(proposal) {
        return (proposal.operation || 'agent work') + ' -> ' + (proposal.lane || 'lane not specified') + '; receipt required';
      }), 'ready');
    }
    function _renderReceiptNarration(response) {
      var lines = [];
      if (response.turnId) lines.push('turn: ' + response.turnId);
      if (response.receiptType) lines.push('receipt type: ' + response.receiptType);
      if (response.desktopControl?.planId) lines.push('desktop plan: ' + response.desktopControl.planId);
      if (response.systemStatus?.route?.cockpitCapsuleEndpoint) lines.push('capsule: ' + response.systemStatus.route.cockpitCapsuleEndpoint);
      if (!lines.length) lines.push('turn completed; receipt metadata not reported by this response');
      _appendTurnCard('Receipt narration', lines, response.receiptType ? 'ready' : 'attention', 'receipt');
    }
    function _renderTurnOperatorCards(response) {
      _renderSystemStatusCard(response.systemStatus);
      _renderDesktopControlCard(response.desktopControl);
      _renderProposalCards(response.proposals || []);
      _renderAgentHandoffCards(response.proposals || []);
      _renderReceiptNarration(response);
    }
    function sendBrittneyChat() {
      var inp = document.getElementById('brittney-input'); if (!inp) return;
      var msg = inp.value.trim(); if (!msg) return;
      inp.value = ''; _bMsg('You', msg, '#58a6ff');
      var pending = _bMsg('Brittney', 'thinking…', '#bc8cff');
      fetch('/api/brittney/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: msg }) })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (pending && pending.parentNode) pending.parentNode.removeChild(pending);
          if (d.error) { _bMsg('Brittney', 'error: ' + d.error, '#f85149'); return; }
          _bMsg('Brittney', d.reply, '#bc8cff');
          _renderTurnOperatorCards(d);
          if (d.desktopControl) {
            _offerDesktopOpenUrl(msg, d.desktopControl);
          }
          if (d.proposals && d.proposals.length) {
            var lines = d.proposals.map(function(x) { return '• ' + x.operation + (x.lane ? ' [' + x.lane + ']' : ''); }).join('\\n');
            _bMsg('Proposed actions', lines, '#3fb950');
          }
          loadCockpitCapsule();
        })
        .catch(function(e) { if (pending && pending.parentNode) pending.parentNode.removeChild(pending); _bMsg('Brittney', 'network error: ' + e.message, '#f85149'); });
    }
    function _setImprovementStatus(text, color) {
      var el = document.getElementById('improvement-status'); if (!el) return;
      el.textContent = text; el.style.color = color || '#8b949e';
    }
    function _renderImprovementHistory(items) {
      var box = document.getElementById('improvement-history'); if (!box) return;
      if (!items || !items.length) { box.textContent = 'No runs yet'; return; }
      box.textContent = items.slice(0, 3).map(function(item) {
        return item.runId + ' - ' + item.totalExecutedRunCount + '/' + item.queuedRunCount + ' measured' + (item.remainingRunCount ? ' (' + item.remainingRunCount + ' left)' : '');
      }).join('\\n');
    }
    function _setDesktopBridgeStatus(text) {
      var el = document.getElementById('desktop-bridge-status'); if (!el) return;
      el.textContent = text;
    }
    function _reportLaptopDesktopBridge(report) {
      fetch('/api/desktop-control/bridge/report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ report: report })
      }).catch(function() {});
    }
    function _loadServerDesktopBridgeStatus() {
      fetch('/api/desktop-control/bridge')
        .then(function(r) { return r.json(); })
        .then(function(d) {
          _setDesktopBridgeStatus('Bridge: ' + d.status);
        })
        .catch(function() {
          _setDesktopBridgeStatus('Bridge: not reported');
        });
    }
    function _probeLaptopDesktopBridgeAt(urls, index) {
      if (index >= urls.length) { _loadServerDesktopBridgeStatus(); return; }
      fetch(urls[index], { cache: 'no-store' })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.schemaVersion !== 'hololand.holoshell.laptop-desktop-bridge.v0.1.0') {
            _probeLaptopDesktopBridgeAt(urls, index + 1);
            return;
          }
          _setDesktopBridgeStatus('Bridge: ' + d.status + ' (laptop)');
          _lastLaptopDesktopBridgeBaseUrl = urls[index].replace('/api/desktop-control/bridge', '');
          _reportLaptopDesktopBridge(d);
        })
        .catch(function() {
          _probeLaptopDesktopBridgeAt(urls, index + 1);
        });
    }
    function probeLaptopDesktopBridge() {
      _probeLaptopDesktopBridgeAt([
        'http://127.0.0.1:8751/api/desktop-control/bridge',
        'http://127.0.0.1:8752/api/desktop-control/bridge',
        'http://127.0.0.1:8753/api/desktop-control/bridge'
      ], 0);
    }
    function loadImprovementRuns() {
      fetch('/api/improvement-runs')
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.error) { _setImprovementStatus('History error: ' + d.error, '#f85149'); return; }
          if (d.items && d.items.length) _lastImprovementRunId = d.items[0].runId;
          _renderImprovementHistory(d.items || []);
        })
        .catch(function(e) { _setImprovementStatus('History network error: ' + e.message, '#f85149'); });
      probeLaptopDesktopBridge();
      loadCockpitCapsule();
    }
    function executeLatestImprovementRun() {
      if (!_lastImprovementRunId) { _setImprovementStatus('Queue or refresh a run first', '#d29922'); return; }
      _setImprovementStatus('Checking codebase-fix evidence...', '#d29922');
      fetch('/api/improvement-runs/' + encodeURIComponent(_lastImprovementRunId) + '/execute', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ shakedownCount: 10 })
      })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.error) { _setImprovementStatus('Execute error: ' + d.error, '#f85149'); return; }
          _setImprovementStatus('Counted ' + d.totalExecutedRunCount + ' fix(es); ' + d.remainingRunCount + ' left', d.executedRunCount ? '#3fb950' : '#d29922');
          var traceLine = d.holotuneTrace ? '\\nHoloTune: ' + d.holotuneTrace.status + ' (' + d.holotuneTrace.emittedRows + ' rows)' : '';
          _bMsg('Codebase-fix shakedown', d.status + ' - ' + d.executedRunCount + ' fix(es) counted in this batch; ' + d.remainingRunCount + ' left\\nVision/GPU: ' + d.gpuBalancePlan.localGpu.summary + '\\nDesktop bridge: ' + d.desktopBridge.status + traceLine + '\\nNext: ' + d.nextSafeStep, d.executedRunCount ? '#3fb950' : '#d29922');
          if (d.lessons && d.lessons.length) _bMsg('Lessons', d.lessons.slice(0, 4).join('\\n'), '#3fb950');
          loadImprovementRuns();
        })
        .catch(function(e) { _setImprovementStatus('Execute network error: ' + e.message, '#f85149'); });
    }
    function queueImprovementRun() {
      var objectiveInput = document.getElementById('improvement-objective');
      var countInput = document.getElementById('improvement-count');
      if (!objectiveInput || !countInput) return;
      var objective = objectiveInput.value.trim() || 'Land actual codebase fixes through the native Brittney run loop';
      var runCount = parseInt(countInput.value || '10', 10);
      if (!Number.isFinite(runCount)) runCount = 10;
      runCount = Math.max(1, Math.min(128, runCount));
      _setImprovementStatus('Queueing...', '#d29922');
      fetch('/api/improvement-runs', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ objective: objective, runCount: runCount })
      })
        .then(function(r) { return r.json(); })
        .then(function(d) {
          if (d.error) { _setImprovementStatus('Error: ' + d.error, '#f85149'); return; }
          _lastImprovementRunId = d.runId;
          _setImprovementStatus('Queued ' + d.queuedRunCount + ' run(s): ' + d.runId, '#3fb950');
          _bMsg('Improvement run', 'Queued ' + d.queuedRunCount + ' run(s) for: ' + d.objective + '\\n' + d.routingSummary + '\\nNext: ' + d.nextSafeStep, '#3fb950');
          if (d.proposals && d.proposals.length) {
            var lines = d.proposals.map(function(x) { return '- ' + x.operation + (x.lane ? ' [' + x.lane + ']' : ''); }).join('\\n');
            _bMsg('Run proposals', lines, '#3fb950');
          }
          loadImprovementRuns();
        })
        .catch(function(e) { _setImprovementStatus('Network error: ' + e.message, '#f85149'); });
    }
    function initBrittneyChat() {
      var mount = document.getElementById('brittney-chat-mount'); if (!mount) return;
      mount.innerHTML =
        '<section id="operator-state-rail" class="operator-state-rail" aria-label="Brittney operator truth"></section>' +
        '<section id="operator-alerts" class="operator-alerts" aria-label="Brittney evidence prompts"></section>' +
        '<section id="brittney-cockpit" class="cockpit-grid" aria-live="polite">' +
        '<div class="cockpit-card"><strong>Runtime</strong><span id="cockpit-runtime">checking</span></div>' +
        '<div class="cockpit-card"><strong>Routes</strong><span id="cockpit-routes">checking</span></div>' +
        '<div class="cockpit-card"><strong>Context</strong><span id="cockpit-context">checking</span></div>' +
        '<div class="cockpit-card"><strong>Desktop</strong><span id="cockpit-desktop">checking</span></div>' +
        '<div class="cockpit-card"><strong>Reasoning</strong><span id="cockpit-reasoning">checking</span></div>' +
        '<div class="cockpit-card"><strong>Terminal</strong><span id="cockpit-terminal">checking</span></div>' +
        '<div class="cockpit-card"><strong>Windows</strong><span id="cockpit-windows">checking</span></div>' +
        '<div class="cockpit-card"><strong>Tools</strong><span id="cockpit-actions">checking</span></div>' +
        '</section>' +
        '<section id="cockpit-action-cards" class="cockpit-action-grid" aria-label="Brittney action cards"></section>' +
        '<section id="context-capsule-panel" class="context-capsule-panel" aria-label="Context capsule">' +
        '<strong>Context Capsule</strong>' +
        '<div class="context-capsule-grid">' +
        '<span><b>Carry</b><br><span id="context-capsule-required">checking</span></span>' +
        '<span><b>Identity</b><br><span id="context-capsule-identity">checking</span></span>' +
        '<span><b>Memory</b><br><span id="context-capsule-memory">checking</span></span>' +
        '</div>' +
        '</section>' +
        '<div id="improvement-run-panel" style="flex:0 0 auto;margin:14px 0 0 0;padding:12px;border:1px solid #30363d;border-radius:8px;background:#0d1117">' +
        '<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px">' +
        '<strong style="font-size:13px;color:#c9d1d9;font-weight:650">Codebase Fix Shakedown</strong>' +
        '<span id="improvement-status" style="font-size:12px;color:#8b949e;text-align:right">Idle</span>' +
        '</div>' +
        '<div class="improvement-grid">' +
        '<input id="improvement-objective" placeholder="Objective" style="min-width:0;padding:10px 11px;border-radius:8px;border:1px solid #30363d;background:#161b22;color:#c9d1d9;font-size:13px" />' +
        '<input id="improvement-count" type="number" min="1" max="128" value="10" aria-label="Run count" style="width:78px;padding:10px 9px;border-radius:8px;border:1px solid #30363d;background:#161b22;color:#c9d1d9;font-size:13px" />' +
        '<button id="improvement-queue" style="min-width:86px;padding:10px 12px;border-radius:8px;border:none;background:#1f6feb;color:#fff;font-weight:650;cursor:pointer">Queue</button>' +
        '<button id="improvement-execute" style="min-width:86px;padding:10px 12px;border-radius:8px;border:none;background:#238636;color:#fff;font-weight:650;cursor:pointer">Check 10</button>' +
        '<button id="improvement-refresh" style="min-width:78px;padding:10px 10px;border-radius:8px;border:1px solid #30363d;background:#161b22;color:#c9d1d9;font-weight:650;cursor:pointer">Refresh</button>' +
        '</div>' +
        '<div id="desktop-bridge-status" style="margin-top:8px;font-size:12px;color:#8b949e">Bridge: checking...</div>' +
        '<pre id="improvement-history" style="margin:8px 0 0 0;min-height:36px;white-space:pre-wrap;color:#8b949e;font-size:12px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace">No runs yet</pre>' +
        '</div>' +
        '<div id="brittney-messages" style="flex:1 1 auto;min-height:0;overflow-y:auto;padding:16px;background:#0d1117;border:1px solid #30363d;border-radius:12px;margin:14px 0"></div>' +
        '<div style="display:flex;gap:8px;flex:0 0 auto">' +
        '<input id="brittney-input" placeholder="Talk to Brittney — she manages the system, agents do the data work…" style="flex:1;padding:13px 14px;border-radius:10px;border:1px solid #30363d;background:#161b22;color:#c9d1d9;font-size:14px" />' +
        '<button id="brittney-send" style="padding:13px 22px;border-radius:10px;border:none;background:#238636;color:#fff;font-weight:600;cursor:pointer">Send</button>' +
        '</div>';
      document.getElementById('brittney-send').addEventListener('click', sendBrittneyChat);
      document.getElementById('improvement-queue').addEventListener('click', queueImprovementRun);
      document.getElementById('improvement-execute').addEventListener('click', executeLatestImprovementRun);
      document.getElementById('improvement-refresh').addEventListener('click', loadImprovementRuns);
      document.getElementById('brittney-input').addEventListener('keydown', function(e) { if (e.key === 'Enter') sendBrittneyChat(); });
      document.getElementById('improvement-objective').addEventListener('keydown', function(e) { if (e.key === 'Enter') queueImprovementRun(); });
      document.getElementById('brittney-input').focus();
      _bMsg('Brittney', 'Online - owned GPU routes are available ($0), and receipts show when the laptop GPU is actually used. Just talk to me; I manage the system and hand the data work to the agents. The Daimon\\u2019s remembered context rides along when it has emerged (D.053).', '#bc8cff');
      loadImprovementRuns();
    }
    document.addEventListener('DOMContentLoaded', initBrittneyChat);
  </script>`;

html = html.replace('</body>', runtimeScript + '\n</body>');

mkdirSync(DIST_DIR, { recursive: true });
const outPath = join(DIST_DIR, 'operate-room.html');
writeFileSync(outPath, html, 'utf8');
console.log('Compiled (chat surface):', outPath);
