/**
 * @vitest-environment jsdom
 */

/**
 * Tests for HoloCodeGenerator component
 *
 * Validates:
 * - .holo code generation from composition
 * - Proper formatting of trait config properties
 * - Header comment generation
 * - Empty composition handling
 * - Export callback invocation
 * - Code statistics (line count, character count)
 */

import { describe, it, expect, vi } from 'vitest';
import type { Composition } from '../types';

/**
 * Generate .holo code from composition (copied from component for testing)
 */
function generateHoloCode(composition: Composition): string {
  const lines: string[] = [];

  // Header comment
  lines.push('/**');
  lines.push(` * ${composition.objectId}`);
  if (composition.metadata.description) {
    lines.push(` * ${composition.metadata.description}`);
  }
  if (composition.vertical) {
    lines.push(` * Vertical: ${composition.vertical}`);
  }
  lines.push(' * Generated by HoloScript Composition Editor');
  lines.push(` * ${new Date().toISOString()}`);
  lines.push(' */');
  lines.push('');

  // Object declaration
  lines.push(`object ${composition.objectId} {`);

  // Traits
  if (composition.traits.length > 0) {
    composition.traits.forEach((trait) => {
      lines.push(`  ${trait.name}`);

      // Trait configuration
      if (Object.keys(trait.config).length > 0) {
        Object.entries(trait.config).forEach(([key, value]) => {
          const formattedValue = formatConfigValue(value);
          lines.push(`    ${key}: ${formattedValue}`);
        });
      }
      lines.push('');
    });
  } else {
    lines.push('  // No traits configured');
    lines.push('');
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Format configuration value for .holo syntax
 */
function formatConfigValue(value: unknown): string {
  if (typeof value === 'string') {
    return `"${value}"`;
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(formatConfigValue).join(', ')}]`;
  }
  if (value === null) {
    return 'null';
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${formatConfigValue(v)}`)
      .join(', ');
    return `{ ${entries} }`;
  }
  return String(value);
}

describe('HoloCodeGenerator', () => {
  describe('formatConfigValue', () => {
    it('should format string values with quotes', () => {
      expect(formatConfigValue('high')).toBe('"high"');
      expect(formatConfigValue('en-US')).toBe('"en-US"');
    });

    it('should format number values as-is', () => {
      expect(formatConfigValue(1.0)).toBe('1');
      expect(formatConfigValue(0.85)).toBe('0.85');
      expect(formatConfigValue(42)).toBe('42');
    });

    it('should format boolean values as-is', () => {
      expect(formatConfigValue(true)).toBe('true');
      expect(formatConfigValue(false)).toBe('false');
    });

    it('should format null as "null"', () => {
      expect(formatConfigValue(null)).toBe('null');
    });

    it('should format arrays with brackets', () => {
      expect(formatConfigValue([1, 2, 3])).toBe('[1, 2, 3]');
      expect(formatConfigValue(['a', 'b'])).toBe('["a", "b"]');
      expect(formatConfigValue([true, false])).toBe('[true, false]');
    });

    it('should format nested arrays', () => {
      expect(formatConfigValue([[1, 2], [3, 4]])).toBe('[[1, 2], [3, 4]]');
    });

    it('should format objects with braces', () => {
      expect(formatConfigValue({ x: 1, y: 2 })).toBe('{ x: 1, y: 2 }');
    });

    it('should format nested objects', () => {
      const nested = { outer: { inner: 'value' } };
      expect(formatConfigValue(nested)).toBe('{ outer: { inner: "value" } }');
    });

    it('should format mixed complex structures', () => {
      const complex = {
        numbers: [1, 2, 3],
        strings: ['a', 'b'],
        nested: { x: 10 },
      };
      const result = formatConfigValue(complex);
      expect(result).toContain('numbers: [1, 2, 3]');
      expect(result).toContain('strings: ["a", "b"]');
      expect(result).toContain('nested: { x: 10 }');
    });
  });

  describe('generateHoloCode', () => {
    it('should generate code for empty composition', () => {
      const composition: Composition = {
        objectId: 'EmptyObject',
        objectType: 'object',
        vertical: null,
        traits: [],
        metadata: {},
      };

      const code = generateHoloCode(composition);

      expect(code).toContain('object EmptyObject {');
      expect(code).toContain('// No traits configured');
      expect(code).toContain('}');
    });

    it('should include object ID in header and declaration', () => {
      const composition: Composition = {
        objectId: 'MedicalTraining',
        objectType: 'object',
        vertical: null,
        traits: [],
        metadata: {},
      };

      const code = generateHoloCode(composition);

      expect(code).toContain('* MedicalTraining');
      expect(code).toContain('object MedicalTraining {');
    });

    it('should include vertical in header when present', () => {
      const composition: Composition = {
        objectId: 'HealthcareScene',
        objectType: 'object',
        vertical: 'healthcare',
        traits: [],
        metadata: {},
      };

      const code = generateHoloCode(composition);

      expect(code).toContain('* Vertical: healthcare');
    });

    it('should include description in header when present', () => {
      const composition: Composition = {
        objectId: 'SurgicalSim',
        objectType: 'object',
        vertical: null,
        traits: [],
        metadata: {
          description: 'Surgical training simulation',
        },
      };

      const code = generateHoloCode(composition);

      expect(code).toContain('* Surgical training simulation');
    });

    it('should generate single trait without config', () => {
      const composition: Composition = {
        objectId: 'SimpleObject',
        objectType: 'object',
        vertical: null,
        traits: [
          {
            name: '@hand_tracked',
            config: {},
          },
        ],
        metadata: {},
      };

      const code = generateHoloCode(composition);

      expect(code).toContain('@hand_tracked');
      expect(code).not.toContain('precision');
    });

    it('should generate trait with simple config', () => {
      const composition: Composition = {
        objectId: 'ConfiguredObject',
        objectType: 'object',
        vertical: null,
        traits: [
          {
            name: '@hand_tracked',
            config: {
              precision: 'high',
              solver: 'fabrik',
            },
          },
        ],
        metadata: {},
      };

      const code = generateHoloCode(composition);

      expect(code).toContain('@hand_tracked');
      expect(code).toContain('precision: "high"');
      expect(code).toContain('solver: "fabrik"');
    });

    it('should generate multiple traits', () => {
      const composition: Composition = {
        objectId: 'MultiTrait',
        objectType: 'object',
        vertical: null,
        traits: [
          {
            name: '@hand_tracked',
            config: { precision: 'high' },
          },
          {
            name: '@haptic',
            config: { intensity: 0.8 },
          },
        ],
        metadata: {},
      };

      const code = generateHoloCode(composition);

      expect(code).toContain('@hand_tracked');
      expect(code).toContain('precision: "high"');
      expect(code).toContain('@haptic');
      expect(code).toContain('intensity: 0.8');
    });

    it('should generate trait with complex config', () => {
      const composition: Composition = {
        objectId: 'ComplexConfig',
        objectType: 'object',
        vertical: null,
        traits: [
          {
            name: '@material',
            config: {
              type: 'standard',
              color: [1, 0, 0],
              metalness: 0.9,
              roughness: 0.1,
              emissive: { r: 1, g: 0.5, b: 0 },
            },
          },
        ],
        metadata: {},
      };

      const code = generateHoloCode(composition);

      expect(code).toContain('@material');
      expect(code).toContain('type: "standard"');
      expect(code).toContain('color: [1, 0, 0]');
      expect(code).toContain('metalness: 0.9');
      expect(code).toContain('roughness: 0.1');
      expect(code).toContain('emissive: { r: 1, g: 0.5, b: 0 }');
    });

    it('should maintain trait order', () => {
      const composition: Composition = {
        objectId: 'OrderedTraits',
        objectType: 'object',
        vertical: null,
        traits: [
          { name: '@first', config: {} },
          { name: '@second', config: {} },
          { name: '@third', config: {} },
        ],
        metadata: {},
      };

      const code = generateHoloCode(composition);

      const firstIndex = code.indexOf('@first');
      const secondIndex = code.indexOf('@second');
      const thirdIndex = code.indexOf('@third');

      expect(firstIndex).toBeLessThan(secondIndex);
      expect(secondIndex).toBeLessThan(thirdIndex);
    });
  });

  describe('code statistics', () => {
    it('should count lines correctly for empty composition', () => {
      const composition: Composition = {
        objectId: 'Empty',
        objectType: 'object',
        vertical: null,
        traits: [],
        metadata: {},
      };

      const code = generateHoloCode(composition);
      const lineCount = code.split('\n').length;

      expect(lineCount).toBeGreaterThan(0);
    });

    it('should count lines correctly for composition with traits', () => {
      const composition: Composition = {
        objectId: 'WithTraits',
        objectType: 'object',
        vertical: null,
        traits: [
          { name: '@hand_tracked', config: { precision: 'high' } },
        ],
        metadata: {},
      };

      const code = generateHoloCode(composition);
      const lineCount = code.split('\n').length;

      expect(lineCount).toBeGreaterThan(10);
    });

    it('should count characters correctly', () => {
      const composition: Composition = {
        objectId: 'Test',
        objectType: 'object',
        vertical: null,
        traits: [],
        metadata: {},
      };

      const code = generateHoloCode(composition);
      const charCount = code.length;

      expect(charCount).toBeGreaterThan(50);
    });
  });

  describe('export functionality', () => {
    it('should call export callback with code and filename', () => {
      const onExport = vi.fn();
      const composition: Composition = {
        objectId: 'ExportTest',
        objectType: 'object',
        vertical: null,
        traits: [],
        metadata: {},
      };

      const code = generateHoloCode(composition);
      const filename = `${composition.objectId}.holo`;

      onExport(code, filename);

      expect(onExport).toHaveBeenCalledWith(code, 'ExportTest.holo');
      expect(onExport).toHaveBeenCalledTimes(1);
    });
  });
});
