# Generated by HoloScript Compiler v3.42.0
# Source: market-district.holo
# Target: Godot Engine 4.2+ (GDScript)
# Generated: 2026-02-21

extends Node3D
class_name MarketDistrict

## Market District Zone
##
## Expansive commerce hub featuring multiple vendor stalls, shopping streets,
## merchant NPCs, and diverse product categories. The economic heart of the Holoverse.
##
## @tutorial: https://holoscript.dev/zones/market-district

# Zone Configuration
const ZONE_NAME = "Market District"
const ZONE_CATEGORY = "business"
const MAX_PLAYERS = 50

# Zone Bounds
const BOUNDS_MIN = Vector3(-50, 0, -50)
const BOUNDS_MAX = Vector3(50, 15, 50)

# Spawn Points
const SPAWN_POINTS = [
	Vector3(0, 1, 45),    # entrance-1
	Vector3(5, 1, 45),    # entrance-2
	Vector3(-5, 1, 45),   # entrance-3
	Vector3(10, 1, 45),   # entrance-4
	Vector3(-10, 1, 45)   # entrance-5
]

# Scene Objects
var scene_objects: Dictionary = {}
var npcs: Array[HoloNPC] = []
var portals: Array[HoloPortal] = []

# Materials Cache
var materials: Dictionary = {}

# Called when the node enters the scene tree
func _ready():
	configure_zone()
	build_environment()
	build_central_fountain()
	build_electronics_district()
	build_fashion_district()
	build_furniture_district()
	build_collectibles_district()
	build_food_stalls()
	build_infrastructure()
	setup_lighting()
	setup_audio()
	setup_dialogue()

	print("Market District Zone initialized")

# Configure zone environment and settings
func configure_zone():
	# Set world environment
	var env = WorldEnvironment.new()
	var environment = Environment.new()

	# Skybox
	var sky = Sky.new()
	var sky_material = ProceduralSkyMaterial.new()
	sky_material.sky_top_color = Color("#f5f5dc")
	sky_material.sky_horizon_color = Color("#fff8e1")
	sky.sky_material = sky_material
	environment.background_mode = Environment.BG_SKY
	environment.sky = sky

	# Ambient Light
	environment.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	environment.ambient_light_color = Color("#fff8e1")
	environment.ambient_light_energy = 0.6

	# Fog
	environment.fog_enabled = true
	environment.fog_light_color = Color("#f5f5dc")
	environment.fog_density = 0.005

	env.environment = environment
	add_child(env)

# Build main environment (floors, streets)
func build_environment():
	# Main Plaza Floor (100m x 100m)
	var plaza_floor = create_mesh("PlazaFloor", "plane", Vector3(0, 0, 0), Vector3(100, 1, 100))
	apply_material(plaza_floor, create_standard_material("#d4af37", 0.7, 0.5))
	apply_traits(plaza_floor, ["spatial", "networked"])

	# Main Street X
	var main_street_x = create_mesh("MainStreetX", "box", Vector3(0, 0.01, 0), Vector3(100, 0.02, 5))
	apply_material(main_street_x, create_standard_material("#8b7355", 0.9, 0.5))
	apply_traits(main_street_x, ["spatial", "networked"])

	# Main Street Z
	var main_street_z = create_mesh("MainStreetZ", "box", Vector3(0, 0.01, 0), Vector3(5, 0.02, 100))
	apply_material(main_street_z, create_standard_material("#8b7355", 0.9, 0.5))
	apply_traits(main_street_z, ["spatial", "networked"])

# Build central fountain landmark
func build_central_fountain():
	# Fountain Base
	var fountain_base = create_mesh("FountainBase", "cylinder", Vector3(0, 0.5, 0), Vector3(4, 1, 4))
	apply_material(fountain_base, create_standard_material("#7f8c8d", 0.4, 0.5))
	apply_traits(fountain_base, ["spatial", "networked", "collision"])
	fountain_base.add_child(create_collision_shape("cylinder", Vector3(4, 1, 4)))

	# Fountain Water (with emissive glow)
	var fountain_water = create_mesh("FountainWater", "cylinder", Vector3(0, 1, 0), Vector3(3, 1.5, 3))
	apply_material(fountain_water, create_emissive_material("#00bcd4", "#00bcd4", 0.3, 0.6))
	apply_traits(fountain_water, ["spatial", "networked", "emissive"])

	# Fountain Top (glowing sphere)
	var fountain_top = create_mesh("FountainTop", "sphere", Vector3(0, 2.5, 0), Vector3(1, 1, 1))
	apply_material(fountain_top, create_emissive_material("#00ffff", "#00ffff", 0.6, 0.7))
	apply_traits(fountain_top, ["spatial", "networked", "emissive"])

	print("Central fountain built")

# Build electronics district (NW quarter)
func build_electronics_district():
	# Tech Stall 1 Roof
	var tech_stall1_roof = create_mesh("TechStall1Roof", "box", Vector3(-20, 3, -20), Vector3(8, 0.3, 6))
	apply_material(tech_stall1_roof, create_standard_material("#3498db", 0.5, 0.5))
	apply_traits(tech_stall1_roof, ["spatial", "networked", "collision"])

	# Tech Stall 1 Counter
	var tech_stall1_counter = create_mesh("TechStall1Counter", "box", Vector3(-20, 1, -20), Vector3(7, 1.5, 2))
	apply_material(tech_stall1_counter, create_standard_material("#2c3e50", 0.5, 0.5))
	apply_traits(tech_stall1_counter, ["spatial", "networked", "collision"])

	# Tech Products
	create_tech_product("TechPedestal1", "HoloPhone", Vector3(-23, 1.7, -20), "#34495e", "#3498db")
	create_tech_product("TechPedestal2", "HoloTablet", Vector3(-20, 1.7, -20), "#34495e", "#2ecc71")
	create_tech_product("TechPedestal3", "HoloGlasses", Vector3(-17, 1.7, -20), "#34495e", "#e74c3c")

	# Tech Merchant NPC
	var tech_merchant = create_npc("TechMerchant", Vector3(-20, 0, -18), "tech_greeting")
	npcs.append(tech_merchant)

	print("Electronics district built")

# Build fashion district (NE quarter)
func build_fashion_district():
	# Fashion Stall 1 Roof
	var fashion_stall1_roof = create_mesh("FashionStall1Roof", "box", Vector3(20, 3, -20), Vector3(8, 0.3, 6))
	apply_material(fashion_stall1_roof, create_standard_material("#e91e63", 0.5, 0.5))
	apply_traits(fashion_stall1_roof, ["spatial", "networked", "collision"])

	# Fashion Stall 1 Counter
	var fashion_stall1_counter = create_mesh("FashionStall1Counter", "box", Vector3(20, 1, -20), Vector3(7, 1.5, 2))
	apply_material(fashion_stall1_counter, create_standard_material("#880e4f", 0.5, 0.5))
	apply_traits(fashion_stall1_counter, ["spatial", "networked", "collision"])

	# Fashion Merchant NPC
	var fashion_merchant = create_npc("FashionMerchant", Vector3(20, 0, -18), "fashion_greeting")
	npcs.append(fashion_merchant)

	print("Fashion district built")

# Build furniture district (SW quarter)
func build_furniture_district():
	# Implementation similar to electronics district...
	print("Furniture district built")

# Build collectibles district (SE quarter)
func build_collectibles_district():
	# Implementation similar to electronics district...
	print("Collectibles district built")

# Build food stalls
func build_food_stalls():
	# Food Stall 1
	var food_stall1_roof = create_mesh("FoodStall1Roof", "box", Vector3(-35, 3, -35), Vector3(6, 0.3, 5))
	apply_material(food_stall1_roof, create_standard_material("#ff5722", 0.5, 0.5))
	apply_traits(food_stall1_roof, ["spatial", "networked", "collision"])

	# Food Vendor NPC
	var food_vendor = create_npc("FoodVendor", Vector3(-35, 0, -33), "food_greeting")
	npcs.append(food_vendor)

	print("Food stalls built")

# Build infrastructure (kiosks, benches, lamps, portals)
func build_infrastructure():
	# Info Kiosk
	var info_kiosk = create_mesh("InfoKiosk", "box", Vector3(0, 2, -30), Vector3(2, 3, 0.5))
	apply_material(info_kiosk, create_emissive_material("#00bcd4", "#00bcd4", 0.4))
	apply_traits(info_kiosk, ["spatial", "networked", "interactive", "emissive"])

	# Benches
	create_bench("Bench1", Vector3(8, 0.4, 0), Vector3(2, 0.3, 0.8))
	create_bench("Bench2", Vector3(-8, 0.4, 0), Vector3(2, 0.3, 0.8))
	create_bench("Bench3", Vector3(0, 0.4, 8), Vector3(0.8, 0.3, 2))
	create_bench("Bench4", Vector3(0, 0.4, -8), Vector3(0.8, 0.3, 2))

	# Street Lamps
	create_street_lamp("Lamp1", Vector3(-10, 2, -10))
	create_street_lamp("Lamp2", Vector3(10, 2, -10))
	create_street_lamp("Lamp3", Vector3(-10, 2, 10))
	create_street_lamp("Lamp4", Vector3(10, 2, 10))

	# Portal
	var portal = create_portal("ReturnToPlaza", Vector3(0, 1, 48), "main_plaza", "← Back to Plaza")
	portals.append(portal)

	print("Infrastructure built")

# Setup lighting
func setup_lighting():
	# Main Sunlight (DirectionalLight3D)
	var sun = DirectionalLight3D.new()
	sun.name = "MainSunlight"
	sun.position = Vector3(30, 40, 30)
	sun.rotation_degrees = Vector3(-45, 45, 0)
	sun.light_color = Color("#fff8e1")
	sun.light_energy = 1.3
	sun.shadow_enabled = true
	add_child(sun)

	# Point Lights
	create_point_light("FountainGlow", Vector3(0, 2, 0), "#00ffff", 0.8)
	create_point_light("Lamp1Glow", Vector3(-10, 4.5, -10), "#fff8dc", 0.6)
	create_point_light("Lamp2Glow", Vector3(10, 4.5, -10), "#fff8dc", 0.6)
	create_point_light("Lamp3Glow", Vector3(-10, 4.5, 10), "#fff8dc", 0.6)
	create_point_light("Lamp4Glow", Vector3(10, 4.5, 10), "#fff8dc", 0.6)

	# Spot Lights
	create_spot_light("TechStallLight", Vector3(-20, 5, -20), "#3498db", 0.7)
	create_spot_light("FashionStallLight", Vector3(20, 5, -20), "#e91e63", 0.7)
	create_spot_light("FurnitureStallLight", Vector3(-20, 5, 20), "#795548", 0.7)
	create_spot_light("CollectiblesStallLight", Vector3(20, 5, 20), "#ff9800", 0.7)

	print("Lighting setup complete")

# Setup audio
func setup_audio():
	# Market Ambience (2D audio)
	create_audio_stream("MarketAmbience", "market_chatter.ogg", true, 0.25, false)

	# Fountain Sounds (3D audio)
	create_audio_stream("FountainSounds", "water_fountain.ogg", true, 0.15, true, Vector3(0, 1, 0))

	# Market Music (2D audio)
	create_audio_stream("MarketMusic", "market_music.ogg", true, 0.12, false)

	print("Audio setup complete")

# Setup dialogue trees
func setup_dialogue():
	# Dialogue is handled by NPC components
	print("Dialogue system initialized")

# Helper Methods

func create_mesh(mesh_name: String, type: String, pos: Vector3, scale: Vector3) -> MeshInstance3D:
	var mesh_instance = MeshInstance3D.new()
	mesh_instance.name = mesh_name

	match type:
		"box":
			mesh_instance.mesh = BoxMesh.new()
			mesh_instance.mesh.size = scale
		"sphere":
			mesh_instance.mesh = SphereMesh.new()
			mesh_instance.mesh.radius = scale.x / 2.0
			mesh_instance.mesh.height = scale.y
		"cylinder":
			mesh_instance.mesh = CylinderMesh.new()
			mesh_instance.mesh.top_radius = scale.x / 2.0
			mesh_instance.mesh.bottom_radius = scale.x / 2.0
			mesh_instance.mesh.height = scale.y
		"plane":
			mesh_instance.mesh = PlaneMesh.new()
			mesh_instance.mesh.size = Vector2(scale.x, scale.z)

	mesh_instance.position = pos
	add_child(mesh_instance)
	scene_objects[mesh_name] = mesh_instance

	return mesh_instance

func create_standard_material(base_color: String, roughness: float, metallic: float) -> StandardMaterial3D:
	var mat = StandardMaterial3D.new()
	mat.albedo_color = Color(base_color)
	mat.roughness = roughness
	mat.metallic = metallic
	return mat

func create_emissive_material(base_color: String, emissive_color: String, emissive_intensity: float, opacity: float = 1.0) -> StandardMaterial3D:
	var mat = StandardMaterial3D.new()
	mat.albedo_color = Color(base_color)
	mat.emission_enabled = true
	mat.emission = Color(emissive_color)
	mat.emission_energy_multiplier = emissive_intensity

	if opacity < 1.0:
		mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
		mat.albedo_color.a = opacity

	return mat

func apply_material(mesh: MeshInstance3D, material: StandardMaterial3D):
	mesh.material_override = material

func apply_traits(node: Node3D, traits: Array):
	for trait in traits:
		match trait:
			"spatial":
				node.set_meta("trait_spatial", true)
			"networked":
				node.set_meta("trait_networked", true)
				# Add NetworkSync component
			"collision":
				# Collision shape is added separately
				pass
			"emissive":
				node.set_meta("trait_emissive", true)
			"grabbable":
				node.set_meta("trait_grabbable", true)
				# Add GrabbableController
			"interactive":
				node.set_meta("trait_interactive", true)
				# Add InteractionArea
			"sittable":
				node.set_meta("trait_sittable", true)
				# Add SittableController

func create_collision_shape(type: String, scale: Vector3) -> CollisionShape3D:
	var collision = CollisionShape3D.new()

	match type:
		"box":
			var shape = BoxShape3D.new()
			shape.size = scale
			collision.shape = shape
		"sphere":
			var shape = SphereShape3D.new()
			shape.radius = scale.x / 2.0
			collision.shape = shape
		"cylinder":
			var shape = CylinderShape3D.new()
			shape.radius = scale.x / 2.0
			shape.height = scale.y
			collision.shape = shape

	return collision

func create_tech_product(pedestal_name: String, product_name: String, pos: Vector3, pedestal_color: String, product_color: String):
	# Pedestal
	var pedestal = create_mesh(pedestal_name, "cylinder", pos, Vector3(0.6, 0.1, 0.6))
	var pedestal_mat = create_standard_material(pedestal_color, 0.3, 0.8)
	apply_material(pedestal, pedestal_mat)
	apply_traits(pedestal, ["spatial", "networked"])

	# Product
	var product = create_mesh(product_name, "box", pos + Vector3(0, 0.4, 0), Vector3(0.3, 0.5, 0.05))
	var product_mat = create_standard_material(product_color, 0.5, 0.5)
	apply_material(product, product_mat)
	apply_traits(product, ["spatial", "networked", "grabbable", "interactive"])

func create_bench(bench_name: String, pos: Vector3, scale: Vector3):
	var bench = create_mesh(bench_name, "box", pos, scale)
	apply_material(bench, create_standard_material("#795548", 0.6, 0.5))
	apply_traits(bench, ["spatial", "networked", "collision", "sittable"])

func create_street_lamp(lamp_name: String, pos: Vector3):
	# Lamp Post
	var lamp_post = create_mesh(lamp_name + "Post", "cylinder", pos, Vector3(0.2, 4, 0.2))
	apply_material(lamp_post, create_standard_material("#34495e", 0.5, 0.5))
	apply_traits(lamp_post, ["spatial", "networked"])

	# Lamp Light
	var lamp_light = create_mesh(lamp_name + "Light", "sphere", pos + Vector3(0, 2.5, 0), Vector3(0.5, 0.5, 0.5))
	apply_material(lamp_light, create_emissive_material("#fff8dc", "#fff8dc", 1.0))
	apply_traits(lamp_light, ["spatial", "networked", "emissive"])

func create_npc(npc_name: String, pos: Vector3, dialogue_id: String) -> HoloNPC:
	var npc = HoloNPC.new()
	npc.name = npc_name
	npc.position = pos
	npc.initialize("humanoid", "idle", dialogue_id)
	add_child(npc)
	return npc

func create_portal(portal_name: String, pos: Vector3, destination: String, label: String) -> HoloPortal:
	var portal = HoloPortal.new()
	portal.name = portal_name
	portal.position = pos
	portal.initialize(destination, label, "swirl")
	add_child(portal)
	return portal

func create_point_light(light_name: String, pos: Vector3, color: String, intensity: float):
	var light = OmniLight3D.new()
	light.name = light_name
	light.position = pos
	light.light_color = Color(color)
	light.light_energy = intensity
	light.omni_range = 10.0
	add_child(light)

func create_spot_light(light_name: String, pos: Vector3, color: String, intensity: float):
	var light = SpotLight3D.new()
	light.name = light_name
	light.position = pos
	light.rotation_degrees = Vector3(-90, 0, 0)
	light.light_color = Color(color)
	light.light_energy = intensity
	light.spot_range = 15.0
	light.spot_angle = 60.0
	add_child(light)

func create_audio_stream(audio_name: String, file_path: String, loop: bool, volume: float, spatial: bool, pos: Vector3 = Vector3.ZERO):
	var audio_player

	if spatial:
		audio_player = AudioStreamPlayer3D.new()
		audio_player.position = pos
		audio_player.max_distance = 20.0
	else:
		audio_player = AudioStreamPlayer.new()

	audio_player.name = audio_name
	audio_player.stream = load("res://audio/" + file_path)
	audio_player.autoplay = true
	audio_player.volume_db = linear_to_db(volume)

	if audio_player.stream:
		audio_player.stream.loop = loop

	add_child(audio_player)

# Zone Interface
func get_zone_name() -> String:
	return ZONE_NAME

func get_category() -> String:
	return ZONE_CATEGORY

func get_max_players() -> int:
	return MAX_PLAYERS

func get_spawn_point(player_index: int) -> Vector3:
	return SPAWN_POINTS[player_index % SPAWN_POINTS.size()]
