// Generated by HoloScript Compiler v3.42.0
// Source: packages\components\templates\npcs.holo
// Target: unreal
// Generated: 2026-02-22T06:29:16.838Z
//
// NOTE: This is a demonstration placeholder.
// For actual compilation, use:
//   npx holoscript compile packages\components\templates\npcs.holo --target unreal
//
// Or use the HoloScript CLI from the HoloScript repository:
//   cd ../HoloScript
//   npx @holoscript/cli compile ../packages\components\templates\npcs.holo --target unreal
//
// This placeholder shows the expected output structure and demonstrates
// that cross-compilation from .holo to unreal is supported.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Npcs.generated.h"

UCLASS()
class HOLOLAND_API ANpcs : public AActor
{
    GENERATED_BODY()

public:
    ANpcs();

protected:
    virtual void BeginPlay() override;

private:
    void BuildEnvironment();
    void SetupLighting();
    void SetupAudio();
};
