import React from "react";
import { AbsoluteFill, Sequence, useVideoConfig } from "remotion";
import { TitleCard } from "../components/TitleCard";
import { CodeStep } from "../components/CodeStep";

const STEPS = [
  {
    title: "What is Brittney?",
    description: "Brittney is a local AI service built on Ollama + Llama 3.2 — no API key, no cloud, runs entirely on your machine.",
    lines: [
      { content: "// Brittney AI — fully local, no cloud required", annotation: "private by default" },
      { content: "Runtime:  Ollama (localhost:11434)", highlight: true },
      { content: "Model:    llama3.2:3b  (runs on 8GB VRAM)", highlight: true },
      { content: "Protocol: MCP (Model Context Protocol)", highlight: true },
      { content: "" },
      { content: "// What Brittney can do:", annotation: "capabilities" },
      { content: '  ✓ "Generate a forest scene with 50 trees"', type: "added" as const },
      { content: '  ✓ "Suggest traits for a door object"', type: "added" as const },
      { content: '  ✓ "Fix the physics on my crate stack"', type: "added" as const },
      { content: '  ✓ "Scan my project and find errors"', type: "added" as const },
      { content: "" },
      { content: "// Zero data leaves your machine", type: "added" as const, annotation: "enterprise-safe" },
    ],
  },
  {
    title: "Start the Service",
    description: "Start the Brittney service with a single npm command — it spins up Ollama and registers MCP tools.",
    lines: [
      { content: "# Prerequisites: Ollama installed", annotation: "ollama.ai" },
      { content: "$ ollama pull llama3.2:3b", highlight: true },
      { content: "  pulling manifest..." },
      { content: "  ✓ llama3.2:3b downloaded (2.0 GB)" },
      { content: "" },
      { content: "# Start Brittney from your HoloLand project", annotation: "from package root" },
      { content: "$ npm run brittney:dev", highlight: true },
      { content: "  ✓ Ollama connection verified" },
      { content: "  ✓ MCP tools registered (8 tools)" },
      { content: "  ✓ Brittney service ready on :11435", type: "added" as const, annotation: "MCP port" },
      { content: '  → Try: "Generate a VR room scene"', type: "added" as const },
    ],
  },
  {
    title: "Natural Language → Scene",
    description: "Call brittney.generateScene() with a text prompt — it returns a complete, valid .holo scene string.",
    lines: [
      { content: 'import { Brittney } from "@hololand/brittney-service"', highlight: true },
      { content: "" },
      { content: "const brittney = new Brittney({", type: "added" as const },
      { content: '  endpoint: "http://localhost:11435",', type: "added" as const },
      { content: '  model: "llama3.2:3b",', type: "added" as const },
      { content: "})", type: "added" as const },
      { content: "" },
      { content: "const holoSource = await brittney.generateScene(", type: "added" as const },
      { content: '  "Create a magical forest with tall oak trees, fireflies, and a stone path"', type: "added" as const, annotation: "your prompt" },
      { content: ")", type: "added" as const },
      { content: "" },
      { content: "// Returns validated .holo source code", annotation: "ready to use" },
      { content: "await app.loadSceneFromSource(holoSource)", type: "added" as const },
    ],
  },
  {
    title: "Generated Scene Preview",
    description: "Here is what Brittney generates from the forest prompt — a complete, valid HoloScript scene.",
    lines: [
      { content: "// Generated by Brittney AI — forest prompt", annotation: "auto-generated" },
      { content: "scene MagicalForest {", highlight: true },
      { content: "  environment: Outdoor" },
      { content: "  fog: { density: 0.04, color: '#2d5a27' }" },
      { content: "" },
      { content: "  object Ground {", type: "added" as const },
      { content: "    mesh: Plane  scale: [50, 1, 50]", type: "added" as const },
      { content: "    material: PBRMaterial { albedo: '#3d5a2a', roughness: 0.95 }", type: "added" as const },
      { content: "  }", type: "added" as const },
      { content: "" },
      { content: "  scatter OakTree 200 {", type: "added" as const, annotation: "200 random trees" },
      { content: "    area: [40, 40]", type: "added" as const },
      { content: "    scale: random(0.8, 1.4)", type: "added" as const },
      { content: "  }", type: "added" as const },
      { content: "" },
      { content: "  // + StonePath, Fireflies particle system...", dim: true },
    ],
  },
  {
    title: "MCP Tools",
    description: "Brittney exposes 8 MCP tools — use them from any MCP client like Claude Code or Cursor.",
    lines: [
      { content: "// Available Brittney MCP tools:", annotation: "8 total" },
      { content: "generate_scene(prompt, options?)", highlight: true, annotation: "NL → .holo" },
      { content: "suggest_traits(objectDesc)", highlight: true, annotation: "trait suggestions" },
      { content: "brittney_scan_project(path)", highlight: true, annotation: "find errors" },
      { content: "optimize_scene(holoSource)", type: "added" as const, annotation: "performance hints" },
      { content: "explain_trait(traitName)", type: "added" as const, annotation: "docs lookup" },
      { content: "generate_npc_dialogue(npcDesc)", type: "added" as const, annotation: "NPC writing" },
      { content: "convert_to_holo(format, source)", type: "added" as const, annotation: "GLTF/OBJ import" },
      { content: "test_scene_validity(holoSource)", type: "added" as const, annotation: "lint + validate" },
      { content: "" },
      { content: "// Call from Claude Code:", annotation: "MCP client" },
      { content: '> "Use Brittney to generate a spooky dungeon"', type: "added" as const },
      { content: "  → Calls generate_scene({ theme: 'dungeon', mood: 'spooky' })", type: "added" as const },
    ],
  },
];

export const BrittneyAIDemo: React.FC = () => {
  const { fps } = useVideoConfig();
  const TITLE_FRAMES = fps * 3;
  const STEP_FRAMES = fps * 5;
  return (
    <AbsoluteFill>
      <Sequence from={0} durationInFrames={TITLE_FRAMES}>
        <TitleCard
          title="Brittney AI Demo"
          subtitle="Generate entire .holo scenes from natural language with the Brittney AI"
          tag="Brittney AI"
          packageName="@hololand/brittney-service"
        />
      </Sequence>
      {STEPS.map((step, i) => (
        <Sequence key={i} from={TITLE_FRAMES + i * STEP_FRAMES} durationInFrames={STEP_FRAMES}>
          <CodeStep
            title={step.title}
            description={step.description}
            language={i === 3 ? "holo" : "typescript"}
            lines={step.lines}
            stepNumber={i + 1}
            totalSteps={STEPS.length}
          />
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};
