import React from "react";
import { AbsoluteFill, Sequence, useVideoConfig } from "remotion";
import { TitleCard } from "../components/TitleCard";
import { CodeStep } from "../components/CodeStep";

const STEPS = [
  {
    title: "Install & Setup",
    description: "The Three.js adapter gives you lightweight WebGL rendering — ideal for React-based apps and smaller bundles.",
    lines: [
      { content: "# Install the adapter + peer deps", annotation: "React Three Fiber included" },
      { content: "$ npm install @hololand/three-adapter three @react-three/fiber", highlight: true },
      { content: "" },
      { content: 'import { ThreeAdapter } from "@hololand/three-adapter"', type: "added" as const },
      { content: 'import { HoloLandApp } from "@hololand/core"', type: "added" as const },
      { content: "" },
      { content: "const adapter = new ThreeAdapter({", type: "added" as const },
      { content: '  canvas: document.getElementById("canvas") as HTMLCanvasElement,', type: "added" as const },
      { content: "  shadows: true,", type: "added" as const, annotation: "PCFSoft shadows" },
      { content: "  toneMapping: THREE.ACESFilmicToneMapping,", type: "added" as const },
      { content: "})", type: "added" as const },
    ],
  },
  {
    title: "Scene Graph Mapping",
    description: "Every .holo object maps directly to a Three.js Object3D — the adapter maintains the hierarchy automatically.",
    lines: [
      { content: "// .holo source", annotation: "your scene" },
      { content: "group Environment {", highlight: true },
      { content: "  object Tree { mesh: Cone  position: [2, 0, 0] }" },
      { content: "  object Rock { mesh: Sphere  position: [-1, 0, 1] }" },
      { content: "}" },
      { content: "" },
      { content: "// Three.js output (generated by adapter)", annotation: "auto-built" },
      { content: "const group = new THREE.Group()  // Environment", type: "added" as const },
      { content: "group.add(treeMesh)  // Tree at [2, 0, 0]", type: "added" as const },
      { content: "group.add(rockMesh)  // Rock at [-1, 0, 1]", type: "added" as const },
      { content: "scene.add(group)", type: "added" as const, annotation: "full hierarchy preserved" },
    ],
  },
  {
    title: "Physics with Rapier",
    description: "Wire up @react-three/rapier for physics — ThreeAdapter exposes Rapier body handles for each .holo PhysicsBody.",
    lines: [
      { content: 'import { Physics, RigidBody } from "@react-three/rapier"', highlight: true },
      { content: 'import { useHoloBody } from "@hololand/three-adapter/rapier"', highlight: true },
      { content: "" },
      { content: "function PhysicsScene() {", type: "added" as const },
      { content: "  const bodies = useHoloBody('Crate')  // from .holo PhysicsBody trait", type: "added" as const },
      { content: "  return (", type: "added" as const },
      { content: "    <Physics gravity={[0, -9.8, 0]}>", type: "added" as const, annotation: "Rapier world" },
      { content: "      {bodies.map(b => (", type: "added" as const },
      { content: "        <RigidBody key={b.id} {...b.rapierProps}>", type: "added" as const },
      { content: "          <mesh geometry={b.geometry} />", type: "added" as const },
      { content: "        </RigidBody>", type: "added" as const },
      { content: "      ))}", type: "added" as const },
      { content: "    </Physics>", type: "added" as const },
      { content: "  )", type: "added" as const },
    ],
  },
  {
    title: "React Three Fiber",
    description: "Use @hololand/react-three components to mix .holo scenes with your existing React component tree.",
    lines: [
      { content: 'import { HoloCanvas, HoloScene } from "@hololand/react-three"', highlight: true },
      { content: "" },
      { content: "function App() {", type: "added" as const },
      { content: "  return (", type: "added" as const },
      { content: "    <HoloCanvas adapter={ThreeAdapter}>", type: "added" as const, annotation: "R3F canvas" },
      { content: '      <HoloScene src="./scenes/lobby.holo" />', type: "added" as const, annotation: "your scene" },
      { content: "      <MyUIOverlay />  {/* regular React */}", type: "added" as const },
      { content: "      <ambientLight intensity={0.5} />", type: "added" as const },
      { content: "    </HoloCanvas>", type: "added" as const },
      { content: "  )", type: "added" as const },
      { content: "}", type: "added" as const },
    ],
  },
  {
    title: "Shadows & PostFX",
    description: "Enable PCF shadow maps, bloom, and SSAO for cinematic quality — all configurable through ThreeAdapter options.",
    lines: [
      { content: "const adapter = new ThreeAdapter({", highlight: true },
      { content: "  canvas,", highlight: true },
      { content: "  shadows: {", type: "added" as const },
      { content: "    enabled: true,", type: "added" as const },
      { content: "    type: THREE.PCFSoftShadowMap,", type: "added" as const, annotation: "soft edges" },
      { content: "    mapSize: 2048,", type: "added" as const },
      { content: "  },", type: "added" as const },
      { content: "  postProcessing: {", type: "added" as const },
      { content: "    bloom: { strength: 0.4, threshold: 0.85 },", type: "added" as const, annotation: "glow effect" },
      { content: "    ssao: { radius: 0.5, intensity: 1.5 },", type: "added" as const, annotation: "ambient occlusion" },
      { content: "    fxaa: true,", type: "added" as const, annotation: "anti-aliasing" },
      { content: "  },", type: "added" as const },
      { content: "})", type: "added" as const },
    ],
  },
];

export const ThreeAdapterDemo: React.FC = () => {
  const { fps } = useVideoConfig();
  const TITLE_FRAMES = fps * 3;
  const STEP_FRAMES = fps * 5;
  return (
    <AbsoluteFill>
      <Sequence from={0} durationInFrames={TITLE_FRAMES}>
        <TitleCard
          title="Three.js Adapter"
          subtitle="Lightweight WebGL rendering with Three.js and React Three Fiber"
          tag="Adapters"
          packageName="@hololand/three-adapter"
        />
      </Sequence>
      {STEPS.map((step, i) => (
        <Sequence key={i} from={TITLE_FRAMES + i * STEP_FRAMES} durationInFrames={STEP_FRAMES}>
          <CodeStep
            title={step.title}
            description={step.description}
            language="typescript"
            lines={step.lines}
            stepNumber={i + 1}
            totalSteps={STEPS.length}
          />
        </Sequence>
      ))}
    </AbsoluteFill>
  );
};
