/**
 * @pointable Trait Generator
 *
 * Converts HoloScript @pointable trait to VRChat interaction with ray/pointer.
 * Responds to VR controller pointing and desktop mouse hover.
 */

import type { HSPlusNode } from '../types.js';
import type {
  TraitMapping,
  ExportContext,
  UdonSharpScript,
} from '../types.js';

interface PointableConfig {
  highlight_on_point?: boolean;
  highlight_color?: string;
  cursor_style?: 'default' | 'pointer' | 'grab' | 'crosshair';
}

function hexToUnityColor(hex: string): string {
  const cleanHex = hex.replace('#', '');
  const r = parseInt(cleanHex.substring(0, 2), 16) / 255;
  const g = parseInt(cleanHex.substring(2, 4), 16) / 255;
  const b = parseInt(cleanHex.substring(4, 6), 16) / 255;
  return `new Color(${r.toFixed(3)}f, ${g.toFixed(3)}f, ${b.toFixed(3)}f, 1f)`;
}

export function generatePointable(
  node: HSPlusNode,
  config: PointableConfig,
  context: ExportContext
): TraitMapping {
  const objectName = node.id || 'PointableObject';
  const scriptName = `${objectName}_Pointable`;

  const udonScript: UdonSharpScript = {
    name: scriptName,
    source: generatePointableUdonSharp(objectName, config, context),
    trait: 'pointable',
    requiredComponents: ['Collider'],
    syncedVariables: [],
    networkEvents: [],
    dependencies: [],
  };

  return {
    trait: 'pointable',
    components: ['BoxCollider'],
    udonScript,
    prefabModifications: {
      'BoxCollider': {
        isTrigger: false,
      },
    },
    requiredFeatures: ['VRC_Interactable', 'UdonBehaviour'],
  };
}

function generatePointableUdonSharp(
  objectName: string,
  config: PointableConfig,
  context: ExportContext
): string {
  const className = `${objectName.replace(/[^a-zA-Z0-9]/g, '')}_Pointable`;
  const highlightOnPoint = config.highlight_on_point ?? true;
  const highlightColor = config.highlight_color
    ? hexToUnityColor(config.highlight_color)
    : 'new Color(0.8f, 0.9f, 1f, 1f)';
  const debug = context.config.debug;

  return `/*
 * Generated by @holoscript/vrchat-export
 * Original HoloScript: ${objectName} @pointable
 *
 * This object responds to VR controller pointing/raycasting.
 * Try the full HoloScript experience at https://hololand.dev
 */

using UdonSharp;
using UnityEngine;
using VRC.SDKBase;
using VRC.Udon;

public class ${className} : UdonSharpBehaviour
{
    [Header("HoloScript @pointable Configuration")]
    [Tooltip("Highlight when pointed at")]
    public bool highlightOnPoint = ${highlightOnPoint};

    [Tooltip("Highlight color")]
    public Color highlightColor = ${highlightColor};

    [Header("Interaction Settings")]
    [Tooltip("Interaction text shown to user")]
    public string interactionText = "Point";

    // State
    private bool _isPointed = false;
    private MeshRenderer _renderer;
    private Color _originalColor;
    private MaterialPropertyBlock _propertyBlock;

    void Start()
    {
        _renderer = GetComponent<MeshRenderer>();
        _propertyBlock = new MaterialPropertyBlock();

        if (_renderer != null && _renderer.material != null)
        {
            _originalColor = _renderer.material.color;
        }

        ${debug ? 'Debug.Log($"[HoloScript] {gameObject.name} @pointable initialized");' : ''}
    }

    // VRChat calls this when user looks at/points at object
    public override void Interact()
    {
        ${debug ? 'Debug.Log($"[HoloScript] {gameObject.name} interacted via point");' : ''}
        OnPointed();
    }

    public void OnPointed()
    {
        // Override in derived classes for custom behavior
        SendCustomNetworkEvent(VRC.Udon.Common.Interfaces.NetworkEventTarget.All, nameof(OnPointedNetwork));
    }

    public void OnPointedNetwork()
    {
        // Network callback for point interaction
    }

    // For highlighting - call from external raycast system
    public void SetPointed(bool pointed)
    {
        if (_isPointed == pointed) return;

        _isPointed = pointed;

        if (highlightOnPoint && _renderer != null)
        {
            _renderer.GetPropertyBlock(_propertyBlock);
            _propertyBlock.SetColor("_Color", pointed ? highlightColor : _originalColor);
            _renderer.SetPropertyBlock(_propertyBlock);
        }

        ${debug ? 'Debug.Log($"[HoloScript] {gameObject.name} pointed: {pointed}");' : ''}
    }

    public bool IsPointed()
    {
        return _isPointed;
    }
}
`;
}

export default generatePointable;
