/**
 * VR Performance Dashboard - Shared Types
 *
 * Type definitions for the VR performance monitoring dashboard that
 * visualizes Gaussian splat budget utilization and frame time waterfall.
 *
 * Integrates with:
 *   - GaussianBudgetManager: Layer-level budget (120K+30K+10K=160K Quest 3)
 *   - FoveatedGaussianRenderer: Per-frame render timings
 *   - QualityManager: Adaptive quality state
 *
 * Target: Quest 3 at 90Hz (11.1ms frame budget, ~5.5ms for splat rendering)
 *
 * @module vr-performance-dashboard/types
 */

import type {
  GaussianLayerType,
  GaussianBudgetMetrics,
  LayerBudgetState,
} from '../../GaussianBudgetManager';

import type {
  GaussianRenderTimings,
  GaussianRenderStats,
} from '../../FoveatedGaussianTypes';

// =============================================================================
// DASHBOARD DISPLAY MODES
// =============================================================================

/**
 * Display mode for the VR Performance Dashboard.
 */
export type VRPerfDisplayMode =
  | 'dashboard'     // Full dashboard with all panels
  | 'compact'       // Compact HUD bar for VR overlay
  | 'budget-only'   // Only Gaussian budget panel
  | 'waterfall-only' // Only frame time waterfall
  | 'overlay';      // Semi-transparent overlay for VR HUD

/**
 * Panels that can be shown/hidden in the dashboard.
 */
export type VRPerfPanel =
  | 'budget'         // Gaussian budget utilization per-layer
  | 'waterfall'      // Frame time waterfall chart
  | 'summary'        // Performance summary metrics
  | 'memory'         // VRAM usage per layer
  | 'history'        // Frame time history line chart
  | 'alerts';        // Performance alerts (emergency shed, etc.)

// =============================================================================
// PERFORMANCE STATE
// =============================================================================

/**
 * A single frame time sample with full waterfall breakdown.
 */
export interface FrameTimeSample {
  /** Frame number (monotonically increasing) */
  frameNumber: number;
  /** Timestamp when this frame was recorded */
  timestamp: number;
  /** Full render timing breakdown for this frame */
  timings: GaussianRenderTimings;
}

/**
 * Performance alert generated by the dashboard.
 */
export interface PerformanceAlert {
  /** Unique alert ID */
  id: string;
  /** Alert timestamp */
  timestamp: number;
  /** Alert severity */
  severity: 'info' | 'warning' | 'critical';
  /** Alert category */
  category: 'budget' | 'frame_time' | 'memory' | 'emergency';
  /** Human-readable message */
  message: string;
  /** Whether the alert has been dismissed */
  dismissed: boolean;
}

/**
 * Overall VR performance state consumed by the dashboard.
 */
export interface VRPerformanceState {
  /** Current Gaussian budget metrics (from GaussianBudgetManager.getMetrics()) */
  budgetMetrics: GaussianBudgetMetrics | null;
  /** Current render stats (rolling aggregates from FoveatedGaussianRenderer) */
  renderStats: GaussianRenderStats | null;
  /** Recent frame time samples for waterfall visualization */
  frameSamples: FrameTimeSample[];
  /** Target frame time in ms (11.1ms for 90Hz VR) */
  targetFrameTimeMs: number;
  /** Target Gaussian budget (e.g., 5.5ms for splat rendering) */
  targetSplatBudgetMs: number;
  /** Active performance alerts */
  alerts: PerformanceAlert[];
  /** Whether the dashboard is connected to live data */
  isLive: boolean;
  /** Device preset name */
  devicePreset: string;
  /** Current frames per second */
  currentFps: number;
}

/**
 * Actions available from the useVRPerformance hook.
 */
export interface VRPerformanceActions {
  /** Push new budget metrics (called by GaussianBudgetManager listener) */
  updateBudgetMetrics: (metrics: GaussianBudgetMetrics) => void;
  /** Push a new frame timing sample */
  pushFrameSample: (timings: GaussianRenderTimings, frameNumber: number) => void;
  /** Push updated render stats */
  updateRenderStats: (stats: GaussianRenderStats) => void;
  /** Dismiss a performance alert */
  dismissAlert: (id: string) => void;
  /** Clear all alerts */
  clearAlerts: () => void;
  /** Set target frame time */
  setTargetFrameTimeMs: (ms: number) => void;
  /** Toggle live/paused data feed */
  toggleLive: () => void;
}

// =============================================================================
// THEME
// =============================================================================

/**
 * Theme for the VR Performance Dashboard components.
 * Follows the same pattern as SpatialInferenceTheme for consistency.
 */
export interface VRPerfTheme {
  /** Base font family */
  fontFamily: string;
  /** Font size scale factor (1.0 = default) */
  fontScale: number;
  /** Border radius for panels */
  borderRadius: string;
  /** Background color for the dashboard container */
  containerBackground: string;
  /** Card/panel background */
  cardBackground: string;
  /** Primary text color */
  textPrimary: string;
  /** Secondary text color */
  textSecondary: string;
  /** Muted text color (labels, axes) */
  textMuted: string;
  /** Border/separator color */
  borderColor: string;
  /** Nominal/good performance color */
  nominalColor: string;
  /** Pressure/warning color */
  pressureColor: string;
  /** Critical/error color */
  criticalColor: string;
  /** Emergency color */
  emergencyColor: string;
  /** Baked layer color */
  bakedLayerColor: string;
  /** Relightable layer color */
  relightableLayerColor: string;
  /** Interactive layer color */
  interactiveLayerColor: string;
  /** Accent color for highlights */
  accentColor: string;
  /** Frame budget line color */
  budgetLineColor: string;

  // Waterfall phase colors
  /** Frustum culling phase color */
  waterfallCullColor: string;
  /** Tile assignment phase color */
  waterfallTileColor: string;
  /** Sorting phase color */
  waterfallSortColor: string;
  /** Hierarchical re-sort phase color */
  waterfallResortColor: string;
  /** Rasterization phase color */
  waterfallRasterColor: string;
  /** Blend zone phase color */
  waterfallBlendColor: string;
  /** GPU sync phase color */
  waterfallSyncColor: string;
}

/**
 * Default dark theme for VR performance dashboard.
 * Designed for high-contrast readability in VR overlay context.
 * All foreground colors meet WCAG 2.1 AA contrast against the backgrounds.
 */
export const DEFAULT_VR_PERF_THEME: VRPerfTheme = {
  fontFamily: 'system-ui, -apple-system, sans-serif',
  fontScale: 1.0,
  borderRadius: '8px',
  containerBackground: '#0a0a1a',
  cardBackground: '#12122a',
  textPrimary: '#e0e0f0',       // 12.2:1 ratio against #0a0a1a
  textSecondary: '#9898c0',     // 5.7:1 ratio against #0a0a1a
  textMuted: '#7878a0',         // 4.5:1 ratio against #0a0a1a (AA minimum)
  borderColor: '#2a2a4a',
  nominalColor: '#22c55e',      // Green - nominal performance
  pressureColor: '#eab308',     // Yellow - under pressure
  criticalColor: '#f97316',     // Orange - critical
  emergencyColor: '#ef4444',    // Red - emergency
  bakedLayerColor: '#3b82f6',   // Blue - baked Gaussians
  relightableLayerColor: '#a855f7', // Purple - relightable Gaussians
  interactiveLayerColor: '#06b6d4', // Cyan - interactive Gaussians
  accentColor: '#6366f1',       // Indigo
  budgetLineColor: '#ef4444',   // Red dashed budget line

  waterfallCullColor: '#94a3b8',    // Slate - frustum cull
  waterfallTileColor: '#a78bfa',    // Violet - tile assign
  waterfallSortColor: '#fbbf24',    // Amber - sort
  waterfallResortColor: '#f97316',  // Orange - hierarchical re-sort
  waterfallRasterColor: '#22c55e',  // Green - rasterization
  waterfallBlendColor: '#06b6d4',   // Cyan - blend zone
  waterfallSyncColor: '#64748b',    // Gray - GPU sync
};

// =============================================================================
// LAYER DISPLAY METADATA
// =============================================================================

/**
 * Display metadata for each Gaussian layer type.
 */
export interface LayerDisplayMeta {
  /** Layer type */
  layer: GaussianLayerType;
  /** Human-readable label */
  label: string;
  /** Short description */
  description: string;
  /** Theme color key */
  colorKey: keyof VRPerfTheme;
}

/**
 * Layer display configuration.
 */
export const LAYER_DISPLAY_CONFIG: Record<GaussianLayerType, LayerDisplayMeta> = {
  baked: {
    layer: 'baked',
    label: 'Baked',
    description: 'Pre-lit SH-baked radiance, cheapest per-splat',
    colorKey: 'bakedLayerColor',
  },
  relightable: {
    layer: 'relightable',
    label: 'Relightable',
    description: 'Deferred PBR shading with dynamic lights',
    colorKey: 'relightableLayerColor',
  },
  interactive: {
    layer: 'interactive',
    label: 'Interactive',
    description: 'XPBD physics-coupled, grabbable/deformable',
    colorKey: 'interactiveLayerColor',
  },
};

// =============================================================================
// WATERFALL PHASE DEFINITIONS
// =============================================================================

/**
 * A phase in the frame time waterfall.
 */
export interface WaterfallPhase {
  /** Phase identifier (maps to GaussianRenderTimings field) */
  id: string;
  /** Human-readable label */
  label: string;
  /** Theme color key */
  colorKey: keyof VRPerfTheme;
  /** Field name in GaussianRenderTimings */
  timingsField: keyof GaussianRenderTimings;
}

/**
 * Ordered waterfall phases matching the Gaussian render pipeline.
 */
export const WATERFALL_PHASES: WaterfallPhase[] = [
  {
    id: 'frustumCull',
    label: 'Frustum Cull',
    colorKey: 'waterfallCullColor',
    timingsField: 'frustumCullMs',
  },
  {
    id: 'tileAssign',
    label: 'Tile Assign',
    colorKey: 'waterfallTileColor',
    timingsField: 'tileAssignMs',
  },
  {
    id: 'sort',
    label: 'Depth Sort',
    colorKey: 'waterfallSortColor',
    timingsField: 'sortMs',
  },
  {
    id: 'hierarchicalResort',
    label: 'StopThePop Re-Sort',
    colorKey: 'waterfallResortColor',
    timingsField: 'hierarchicalResortMs',
  },
  {
    id: 'rasterize',
    label: 'Rasterize',
    colorKey: 'waterfallRasterColor',
    timingsField: 'rasterizeMs',
  },
  {
    id: 'blendZone',
    label: 'Blend Zone',
    colorKey: 'waterfallBlendColor',
    timingsField: 'blendZoneMs',
  },
  {
    id: 'sync',
    label: 'GPU Sync',
    colorKey: 'waterfallSyncColor',
    timingsField: 'syncMs',
  },
];

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/**
 * Get the theme color for a performance state.
 */
export function getPerformanceStateColor(
  state: 'nominal' | 'pressure' | 'critical' | 'emergency',
  theme: VRPerfTheme,
): string {
  switch (state) {
    case 'nominal': return theme.nominalColor;
    case 'pressure': return theme.pressureColor;
    case 'critical': return theme.criticalColor;
    case 'emergency': return theme.emergencyColor;
    default: return theme.textMuted;
  }
}

/**
 * Get the theme color for a Gaussian layer type.
 */
export function getLayerColor(layer: GaussianLayerType, theme: VRPerfTheme): string {
  return theme[LAYER_DISPLAY_CONFIG[layer].colorKey] as string;
}

/**
 * Format a splat count for display (e.g., 120000 -> "120K").
 */
export function formatSplatCount(count: number): string {
  if (count >= 1_000_000) return `${(count / 1_000_000).toFixed(1)}M`;
  if (count >= 1_000) return `${(count / 1_000).toFixed(1)}K`;
  return count.toString();
}

/**
 * Format milliseconds for display.
 */
export function formatMs(ms: number): string {
  if (ms < 1) {
    const us = ms * 1000;
    if (us < 1) return '<0.01ms';
    return `${us.toFixed(0)}us`;
  }
  if (ms < 100) return `${ms.toFixed(2)}ms`;
  return `${ms.toFixed(0)}ms`;
}

/**
 * Format bytes for display.
 */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)}MB`;
}

/**
 * Create a unique alert ID.
 */
export function createAlertId(): string {
  return `alert-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;
}
