// Generated by HoloScript Compiler v3.42.0
// Source: market-district.holo
// Target: Unreal Engine C++ (5.3+)
// Generated: 2026-02-21

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "HoloScript/HoloZone.h"
#include "HoloScript/Networking/NetworkedZone.h"
#include "HoloScript/Traits/SpatialTrait.h"
#include "HoloScript/Traits/NetworkedTrait.h"
#include "HoloScript/Traits/InteractiveTrait.h"
#include "HoloScript/NPCs/HoloNPC.h"
#include "HoloScript/Portals/HoloPortal.h"
#include "Sound/AmbientSound.h"
#include "MarketDistrict.generated.h"

/**
 * Market District Zone
 *
 * Expansive commerce hub featuring multiple vendor stalls, shopping streets,
 * merchant NPCs, and diverse product categories. The economic heart of the Holoverse.
 *
 * @note Generated from market-district.holo
 * @see https://holoscript.dev/zones/market-district
 */
UCLASS(BlueprintType, Blueprintable)
class HOLOLAND_API AMarketDistrict : public AActor, public IHoloZone
{
    GENERATED_BODY()

public:
    AMarketDistrict();

protected:
    virtual void BeginPlay() override;
    virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

public:
    virtual void Tick(float DeltaTime) override;

    // IHoloZone Interface
    virtual FString GetZoneName() const override { return TEXT("Market District"); }
    virtual FString GetCategory() const override { return TEXT("business"); }
    virtual int32 GetMaxPlayers() const override { return 50; }
    virtual FVector GetSpawnPoint(int32 PlayerIndex) const override;

private:
    // Zone Configuration
    UPROPERTY(EditAnywhere, Category = "Zone Config")
    FVector BoundsMin = FVector(-5000.0f, -5000.0f, 0.0f); // -50m in Unreal units (cm)

    UPROPERTY(EditAnywhere, Category = "Zone Config")
    FVector BoundsMax = FVector(5000.0f, 5000.0f, 1500.0f); // 50m x 50m x 15m

    UPROPERTY(EditAnywhere, Category = "Zone Config")
    int32 MaxPlayers = 50;

    // Spawn Points (Unreal uses cm, so multiply by 100)
    UPROPERTY(EditAnywhere, Category = "Spawning")
    TArray<FVector> SpawnPoints = {
        FVector(0.0f, 4500.0f, 100.0f),      // entrance-1
        FVector(500.0f, 4500.0f, 100.0f),    // entrance-2
        FVector(-500.0f, 4500.0f, 100.0f),   // entrance-3
        FVector(1000.0f, 4500.0f, 100.0f),   // entrance-4
        FVector(-1000.0f, 4500.0f, 100.0f)   // entrance-5
    };

    // Scene Objects
    UPROPERTY()
    TMap<FString, AActor*> SceneObjects;

    UPROPERTY()
    TArray<AHoloNPC*> NPCs;

    UPROPERTY()
    TArray<AHoloPortal*> Portals;

    // Audio
    UPROPERTY()
    TArray<UAmbientSound*> AmbientSounds;

    // Lighting
    UPROPERTY()
    class ADirectionalLight* MainSunlight;

    UPROPERTY()
    TArray<class APointLight*> PointLights;

    UPROPERTY()
    TArray<class ASpotLight*> SpotLights;

    // Materials
    UPROPERTY()
    TMap<FString, UMaterialInstanceDynamic*> DynamicMaterials;

private:
    // Setup Methods
    void ConfigureZone();
    void BuildEnvironment();
    void BuildCentralFountain();
    void BuildElectronicsDistrict();
    void BuildFashionDistrict();
    void BuildFurnitureDistrict();
    void BuildCollectiblesDistrict();
    void BuildFoodStalls();
    void BuildInfrastructure();
    void SetupLighting();
    void SetupAudio();
    void SetupDialogue();

    // Helper Methods
    AActor* CreateStaticMeshActor(const FString& Name, const FString& MeshPath, const FVector& Location, const FVector& Scale = FVector(1.0f));
    AActor* CreateProceduralMeshActor(const FString& Name, EPrimitiveType Type, const FVector& Location, const FVector& Scale);

    UMaterialInstanceDynamic* CreateMaterial(const FLinearColor& BaseColor, float Roughness, float Metallic);
    UMaterialInstanceDynamic* CreateEmissiveMaterial(const FLinearColor& BaseColor, const FLinearColor& EmissiveColor, float EmissiveIntensity, float Opacity = 1.0f);

    void ApplyMaterial(AActor* Actor, UMaterialInstanceDynamic* Material);
    void ApplyTraits(AActor* Actor, const TArray<FString>& Traits);

    void CreateBench(const FString& Name, const FVector& Location, const FVector& Scale);
    void CreateStreetLamp(const FString& Name, const FVector& Location);
    void CreateTechProduct(const FString& PedestalName, const FString& ProductName, const FVector& Location, const FLinearColor& PedestalColor, const FLinearColor& ProductColor);

    AHoloNPC* CreateNPC(const FString& Name, const FVector& Location, const FString& DialogueId);
    AHoloPortal* CreatePortal(const FString& Name, const FVector& Location, const FString& Destination, const FString& Label);

    void CreatePointLight(const FString& Name, const FVector& Location, const FLinearColor& Color, float Intensity);
    void CreateSpotLight(const FString& Name, const FVector& Location, const FLinearColor& Color, float Intensity);
    void CreateAmbientSound(const FString& Name, const FString& SoundCueName, bool bLoop, float VolumeMultiplier, bool bSpatialized, const FVector& Location = FVector::ZeroVector);

    FLinearColor HexToColor(const FString& Hex);
};
