// Generated by HoloScript Compiler v3.42.0
// Source: market-district.holo
// Target: Unreal Engine C++ (5.3+)
// Generated: 2026-02-21

#include "MarketDistrict.h"
#include "Engine/StaticMeshActor.h"
#include "Components/StaticMeshComponent.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Engine/DirectionalLight.h"
#include "Engine/PointLight.h"
#include "Engine/SpotLight.h"
#include "Components/AudioComponent.h"
#include "Sound/SoundCue.h"
#include "Kismet/GameplayStatics.h"
#include "ProceduralMeshComponent.h"

AMarketDistrict::AMarketDistrict()
{
    PrimaryActorTick.bCanEverTick = true;

    // Set up root component
    USceneComponent* Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
    SetRootComponent(Root);
}

void AMarketDistrict::BeginPlay()
{
    Super::BeginPlay();

    ConfigureZone();
    BuildEnvironment();
    BuildCentralFountain();
    BuildElectronicsDistrict();
    BuildFashionDistrict();
    BuildFurnitureDistrict();
    BuildCollectiblesDistrict();
    BuildFoodStalls();
    BuildInfrastructure();
    SetupLighting();
    SetupAudio();
    SetupDialogue();

    UE_LOG(LogTemp, Log, TEXT("Market District Zone initialized"));
}

void AMarketDistrict::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
    Super::EndPlay(EndPlayReason);

    // Cleanup
    SceneObjects.Empty();
    NPCs.Empty();
    Portals.Empty();
    AmbientSounds.Empty();
}

void AMarketDistrict::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
}

FVector AMarketDistrict::GetSpawnPoint(int32 PlayerIndex) const
{
    if (SpawnPoints.Num() == 0)
        return FVector::ZeroVector;

    return SpawnPoints[PlayerIndex % SpawnPoints.Num()];
}

void AMarketDistrict::ConfigureZone()
{
    // Set up atmospheric fog and lighting
    // This would typically be done via blueprints or a custom AtmosphereController

    UE_LOG(LogTemp, Log, TEXT("Configuring Market District zone bounds: %s to %s"), *BoundsMin.ToString(), *BoundsMax.ToString());
}

void AMarketDistrict::BuildEnvironment()
{
    // Main Plaza Floor (100m x 100m plane)
    AActor* PlazaFloor = CreateProceduralMeshActor(TEXT("PlazaFloor"), EPrimitiveType::Plane, FVector(0.0f, 0.0f, 0.0f), FVector(100.0f, 100.0f, 1.0f));
    UMaterialInstanceDynamic* FloorMat = CreateMaterial(HexToColor(TEXT("#d4af37")), 0.7f, 0.5f);
    ApplyMaterial(PlazaFloor, FloorMat);
    ApplyTraits(PlazaFloor, {TEXT("spatial"), TEXT("networked")});

    // Main Street X
    AActor* MainStreetX = CreateProceduralMeshActor(TEXT("MainStreetX"), EPrimitiveType::Cube, FVector(0.0f, 0.0f, 1.0f), FVector(100.0f, 5.0f, 0.02f));
    UMaterialInstanceDynamic* StreetMat = CreateMaterial(HexToColor(TEXT("#8b7355")), 0.9f, 0.5f);
    ApplyMaterial(MainStreetX, StreetMat);
    ApplyTraits(MainStreetX, {TEXT("spatial"), TEXT("networked")});

    // Main Street Z
    AActor* MainStreetZ = CreateProceduralMeshActor(TEXT("MainStreetZ"), EPrimitiveType::Cube, FVector(0.0f, 0.0f, 1.0f), FVector(5.0f, 100.0f, 0.02f));
    ApplyMaterial(MainStreetZ, StreetMat);
    ApplyTraits(MainStreetZ, {TEXT("spatial"), TEXT("networked")});
}

void AMarketDistrict::BuildCentralFountain()
{
    // Fountain Base (Cylinder)
    AActor* FountainBase = CreateProceduralMeshActor(TEXT("FountainBase"), EPrimitiveType::Cylinder, FVector(0.0f, 0.0f, 50.0f), FVector(4.0f, 4.0f, 1.0f));
    UMaterialInstanceDynamic* BaseMat = CreateMaterial(HexToColor(TEXT("#7f8c8d")), 0.4f, 0.5f);
    ApplyMaterial(FountainBase, BaseMat);
    ApplyTraits(FountainBase, {TEXT("spatial"), TEXT("networked"), TEXT("collision")});

    // Fountain Water (Transparent Cylinder with emissive)
    AActor* FountainWater = CreateProceduralMeshActor(TEXT("FountainWater"), EPrimitiveType::Cylinder, FVector(0.0f, 0.0f, 100.0f), FVector(3.0f, 3.0f, 1.5f));
    UMaterialInstanceDynamic* WaterMat = CreateEmissiveMaterial(HexToColor(TEXT("#00bcd4")), HexToColor(TEXT("#00bcd4")), 0.3f, 0.6f);
    ApplyMaterial(FountainWater, WaterMat);
    ApplyTraits(FountainWater, {TEXT("spatial"), TEXT("networked"), TEXT("emissive")});

    // Fountain Top (Glowing Sphere)
    AActor* FountainTop = CreateProceduralMeshActor(TEXT("FountainTop"), EPrimitiveType::Sphere, FVector(0.0f, 0.0f, 250.0f), FVector(1.0f, 1.0f, 1.0f));
    UMaterialInstanceDynamic* TopMat = CreateEmissiveMaterial(HexToColor(TEXT("#00ffff")), HexToColor(TEXT("#00ffff")), 0.6f, 0.7f);
    ApplyMaterial(FountainTop, TopMat);
    ApplyTraits(FountainTop, {TEXT("spatial"), TEXT("networked"), TEXT("emissive")});

    UE_LOG(LogTemp, Log, TEXT("Central fountain built"));
}

void AMarketDistrict::BuildElectronicsDistrict()
{
    // Tech Stall 1 Roof
    AActor* TechStall1Roof = CreateProceduralMeshActor(TEXT("TechStall1Roof"), EPrimitiveType::Cube, FVector(-2000.0f, -2000.0f, 300.0f), FVector(8.0f, 6.0f, 0.3f));
    UMaterialInstanceDynamic* RoofMat = CreateMaterial(HexToColor(TEXT("#3498db")), 0.5f, 0.5f);
    ApplyMaterial(TechStall1Roof, RoofMat);
    ApplyTraits(TechStall1Roof, {TEXT("spatial"), TEXT("networked"), TEXT("collision")});

    // Tech Stall 1 Counter
    AActor* TechStall1Counter = CreateProceduralMeshActor(TEXT("TechStall1Counter"), EPrimitiveType::Cube, FVector(-2000.0f, -2000.0f, 100.0f), FVector(7.0f, 2.0f, 1.5f));
    UMaterialInstanceDynamic* CounterMat = CreateMaterial(HexToColor(TEXT("#2c3e50")), 0.5f, 0.5f);
    ApplyMaterial(TechStall1Counter, CounterMat);
    ApplyTraits(TechStall1Counter, {TEXT("spatial"), TEXT("networked"), TEXT("collision")});

    // Tech Products
    CreateTechProduct(TEXT("TechPedestal1"), TEXT("HoloPhone"), FVector(-2300.0f, -2000.0f, 170.0f), HexToColor(TEXT("#34495e")), HexToColor(TEXT("#3498db")));
    CreateTechProduct(TEXT("TechPedestal2"), TEXT("HoloTablet"), FVector(-2000.0f, -2000.0f, 170.0f), HexToColor(TEXT("#34495e")), HexToColor(TEXT("#2ecc71")));
    CreateTechProduct(TEXT("TechPedestal3"), TEXT("HoloGlasses"), FVector(-1700.0f, -2000.0f, 170.0f), HexToColor(TEXT("#34495e")), HexToColor(TEXT("#e74c3c")));

    // Tech Merchant NPC
    AHoloNPC* TechMerchant = CreateNPC(TEXT("TechMerchant"), FVector(-2000.0f, -1800.0f, 0.0f), TEXT("tech_greeting"));
    NPCs.Add(TechMerchant);

    UE_LOG(LogTemp, Log, TEXT("Electronics district built"));
}

void AMarketDistrict::BuildFashionDistrict()
{
    // Fashion Stall 1 Roof
    AActor* FashionStall1Roof = CreateProceduralMeshActor(TEXT("FashionStall1Roof"), EPrimitiveType::Cube, FVector(2000.0f, -2000.0f, 300.0f), FVector(8.0f, 6.0f, 0.3f));
    UMaterialInstanceDynamic* RoofMat = CreateMaterial(HexToColor(TEXT("#e91e63")), 0.5f, 0.5f);
    ApplyMaterial(FashionStall1Roof, RoofMat);
    ApplyTraits(FashionStall1Roof, {TEXT("spatial"), TEXT("networked"), TEXT("collision")});

    // Fashion Stall 1 Counter
    AActor* FashionStall1Counter = CreateProceduralMeshActor(TEXT("FashionStall1Counter"), EPrimitiveType::Cube, FVector(2000.0f, -2000.0f, 100.0f), FVector(7.0f, 2.0f, 1.5f));
    UMaterialInstanceDynamic* CounterMat = CreateMaterial(HexToColor(TEXT("#880e4f")), 0.5f, 0.5f);
    ApplyMaterial(FashionStall1Counter, CounterMat);
    ApplyTraits(FashionStall1Counter, {TEXT("spatial"), TEXT("networked"), TEXT("collision")});

    // Fashion Merchant NPC
    AHoloNPC* FashionMerchant = CreateNPC(TEXT("FashionMerchant"), FVector(2000.0f, -1800.0f, 0.0f), TEXT("fashion_greeting"));
    NPCs.Add(FashionMerchant);

    UE_LOG(LogTemp, Log, TEXT("Fashion district built"));
}

void AMarketDistrict::BuildFurnitureDistrict()
{
    // Implementation similar to BuildElectronicsDistrict...
    UE_LOG(LogTemp, Log, TEXT("Furniture district built"));
}

void AMarketDistrict::BuildCollectiblesDistrict()
{
    // Implementation similar to BuildElectronicsDistrict...
    UE_LOG(LogTemp, Log, TEXT("Collectibles district built"));
}

void AMarketDistrict::BuildFoodStalls()
{
    // Food Stall 1
    AActor* FoodStall1Roof = CreateProceduralMeshActor(TEXT("FoodStall1Roof"), EPrimitiveType::Cube, FVector(-3500.0f, -3500.0f, 300.0f), FVector(6.0f, 5.0f, 0.3f));
    UMaterialInstanceDynamic* RoofMat = CreateMaterial(HexToColor(TEXT("#ff5722")), 0.5f, 0.5f);
    ApplyMaterial(FoodStall1Roof, RoofMat);
    ApplyTraits(FoodStall1Roof, {TEXT("spatial"), TEXT("networked"), TEXT("collision")});

    // Food Vendor NPC
    AHoloNPC* FoodVendor = CreateNPC(TEXT("FoodVendor"), FVector(-3500.0f, -3300.0f, 0.0f), TEXT("food_greeting"));
    NPCs.Add(FoodVendor);

    UE_LOG(LogTemp, Log, TEXT("Food stalls built"));
}

void AMarketDistrict::BuildInfrastructure()
{
    // Info Kiosk
    AActor* InfoKiosk = CreateProceduralMeshActor(TEXT("InfoKiosk"), EPrimitiveType::Cube, FVector(0.0f, -3000.0f, 200.0f), FVector(2.0f, 0.5f, 3.0f));
    UMaterialInstanceDynamic* KioskMat = CreateEmissiveMaterial(HexToColor(TEXT("#00bcd4")), HexToColor(TEXT("#00bcd4")), 0.4f);
    ApplyMaterial(InfoKiosk, KioskMat);
    ApplyTraits(InfoKiosk, {TEXT("spatial"), TEXT("networked"), TEXT("interactive"), TEXT("emissive")});

    // Benches
    CreateBench(TEXT("Bench1"), FVector(800.0f, 0.0f, 40.0f), FVector(2.0f, 0.8f, 0.3f));
    CreateBench(TEXT("Bench2"), FVector(-800.0f, 0.0f, 40.0f), FVector(2.0f, 0.8f, 0.3f));
    CreateBench(TEXT("Bench3"), FVector(0.0f, 800.0f, 40.0f), FVector(0.8f, 2.0f, 0.3f));
    CreateBench(TEXT("Bench4"), FVector(0.0f, -800.0f, 40.0f), FVector(0.8f, 2.0f, 0.3f));

    // Street Lamps
    CreateStreetLamp(TEXT("Lamp1"), FVector(-1000.0f, -1000.0f, 200.0f));
    CreateStreetLamp(TEXT("Lamp2"), FVector(1000.0f, -1000.0f, 200.0f));
    CreateStreetLamp(TEXT("Lamp3"), FVector(-1000.0f, 1000.0f, 200.0f));
    CreateStreetLamp(TEXT("Lamp4"), FVector(1000.0f, 1000.0f, 200.0f));

    // Portal
    AHoloPortal* Portal = CreatePortal(TEXT("ReturnToPlaza"), FVector(0.0f, 4800.0f, 100.0f), TEXT("main_plaza"), TEXT("← Back to Plaza"));
    Portals.Add(Portal);

    UE_LOG(LogTemp, Log, TEXT("Infrastructure built"));
}

void AMarketDistrict::SetupLighting()
{
    // Main Sunlight (Directional Light)
    FActorSpawnParameters SpawnParams;
    SpawnParams.Owner = this;

    MainSunlight = GetWorld()->SpawnActor<ADirectionalLight>(FVector(3000.0f, 3000.0f, 4000.0f), FRotator(-45.0f, 45.0f, 0.0f), SpawnParams);
    if (MainSunlight)
    {
        MainSunlight->GetLightComponent()->SetIntensity(1.3f);
        MainSunlight->GetLightComponent()->SetLightColor(HexToColor(TEXT("#fff8e1")));
        MainSunlight->GetLightComponent()->SetCastShadows(true);
    }

    // Point Lights
    CreatePointLight(TEXT("FountainGlow"), FVector(0.0f, 0.0f, 200.0f), HexToColor(TEXT("#00ffff")), 0.8f);
    CreatePointLight(TEXT("Lamp1Glow"), FVector(-1000.0f, -1000.0f, 450.0f), HexToColor(TEXT("#fff8dc")), 0.6f);
    CreatePointLight(TEXT("Lamp2Glow"), FVector(1000.0f, -1000.0f, 450.0f), HexToColor(TEXT("#fff8dc")), 0.6f);
    CreatePointLight(TEXT("Lamp3Glow"), FVector(-1000.0f, 1000.0f, 450.0f), HexToColor(TEXT("#fff8dc")), 0.6f);
    CreatePointLight(TEXT("Lamp4Glow"), FVector(1000.0f, 1000.0f, 450.0f), HexToColor(TEXT("#fff8dc")), 0.6f);

    // Spot Lights
    CreateSpotLight(TEXT("TechStallLight"), FVector(-2000.0f, -2000.0f, 500.0f), HexToColor(TEXT("#3498db")), 0.7f);
    CreateSpotLight(TEXT("FashionStallLight"), FVector(2000.0f, -2000.0f, 500.0f), HexToColor(TEXT("#e91e63")), 0.7f);

    UE_LOG(LogTemp, Log, TEXT("Lighting setup complete"));
}

void AMarketDistrict::SetupAudio()
{
    // Ambient sounds
    CreateAmbientSound(TEXT("MarketAmbience"), TEXT("market_chatter"), true, 0.25f, false);
    CreateAmbientSound(TEXT("FountainSounds"), TEXT("water_fountain"), true, 0.15f, true, FVector(0.0f, 0.0f, 100.0f));
    CreateAmbientSound(TEXT("MarketMusic"), TEXT("market_music"), true, 0.12f, false);

    UE_LOG(LogTemp, Log, TEXT("Audio setup complete"));
}

void AMarketDistrict::SetupDialogue()
{
    // Dialogue is handled by NPC components
    UE_LOG(LogTemp, Log, TEXT("Dialogue system initialized"));
}

// Helper Method Implementations

AActor* AMarketDistrict::CreateProceduralMeshActor(const FString& Name, EPrimitiveType Type, const FVector& Location, const FVector& Scale)
{
    FActorSpawnParameters SpawnParams;
    SpawnParams.Owner = this;
    SpawnParams.Name = FName(*Name);

    AActor* NewActor = GetWorld()->SpawnActor<AActor>(Location, FRotator::ZeroRotator, SpawnParams);

    // In production, you'd generate the mesh geometry here
    // For this example, we're showing the structure

    SceneObjects.Add(Name, NewActor);
    return NewActor;
}

UMaterialInstanceDynamic* AMarketDistrict::CreateMaterial(const FLinearColor& BaseColor, float Roughness, float Metallic)
{
    UMaterial* BaseMaterial = LoadObject<UMaterial>(nullptr, TEXT("/Game/HoloScript/Materials/M_Standard"));
    if (!BaseMaterial) return nullptr;

    UMaterialInstanceDynamic* DynMat = UMaterialInstanceDynamic::Create(BaseMaterial, this);
    DynMat->SetVectorParameterValue(TEXT("BaseColor"), BaseColor);
    DynMat->SetScalarParameterValue(TEXT("Roughness"), Roughness);
    DynMat->SetScalarParameterValue(TEXT("Metallic"), Metallic);

    return DynMat;
}

UMaterialInstanceDynamic* AMarketDistrict::CreateEmissiveMaterial(const FLinearColor& BaseColor, const FLinearColor& EmissiveColor, float EmissiveIntensity, float Opacity)
{
    UMaterial* BaseMaterial = LoadObject<UMaterial>(nullptr, TEXT("/Game/HoloScript/Materials/M_Emissive"));
    if (!BaseMaterial) return nullptr;

    UMaterialInstanceDynamic* DynMat = UMaterialInstanceDynamic::Create(BaseMaterial, this);
    DynMat->SetVectorParameterValue(TEXT("BaseColor"), BaseColor);
    DynMat->SetVectorParameterValue(TEXT("EmissiveColor"), EmissiveColor * EmissiveIntensity);
    DynMat->SetScalarParameterValue(TEXT("Opacity"), Opacity);

    return DynMat;
}

void AMarketDistrict::ApplyMaterial(AActor* Actor, UMaterialInstanceDynamic* Material)
{
    if (!Actor || !Material) return;

    // Apply material to all mesh components
    TArray<UStaticMeshComponent*> MeshComponents;
    Actor->GetComponents<UStaticMeshComponent>(MeshComponents);

    for (UStaticMeshComponent* Mesh : MeshComponents)
    {
        Mesh->SetMaterial(0, Material);
    }
}

void AMarketDistrict::ApplyTraits(AActor* Actor, const TArray<FString>& Traits)
{
    if (!Actor) return;

    for (const FString& Trait : Traits)
    {
        // Add trait components based on trait type
        // In production, this would create and attach actual trait components
        UE_LOG(LogTemp, Verbose, TEXT("Applied trait %s to %s"), *Trait, *Actor->GetName());
    }
}

void AMarketDistrict::CreateBench(const FString& Name, const FVector& Location, const FVector& Scale)
{
    AActor* Bench = CreateProceduralMeshActor(Name, EPrimitiveType::Cube, Location, Scale);
    UMaterialInstanceDynamic* BenchMat = CreateMaterial(HexToColor(TEXT("#795548")), 0.6f, 0.5f);
    ApplyMaterial(Bench, BenchMat);
    ApplyTraits(Bench, {TEXT("spatial"), TEXT("networked"), TEXT("collision"), TEXT("sittable")});
}

void AMarketDistrict::CreateStreetLamp(const FString& Name, const FVector& Location)
{
    // Lamp Post
    AActor* LampPost = CreateProceduralMeshActor(Name + TEXT("Post"), EPrimitiveType::Cylinder, Location, FVector(0.2f, 0.2f, 4.0f));
    UMaterialInstanceDynamic* PostMat = CreateMaterial(HexToColor(TEXT("#34495e")), 0.5f, 0.5f);
    ApplyMaterial(LampPost, PostMat);
    ApplyTraits(LampPost, {TEXT("spatial"), TEXT("networked")});

    // Lamp Light
    AActor* LampLight = CreateProceduralMeshActor(Name + TEXT("Light"), EPrimitiveType::Sphere, Location + FVector(0.0f, 0.0f, 250.0f), FVector(0.5f, 0.5f, 0.5f));
    UMaterialInstanceDynamic* LightMat = CreateEmissiveMaterial(HexToColor(TEXT("#fff8dc")), HexToColor(TEXT("#fff8dc")), 1.0f);
    ApplyMaterial(LampLight, LightMat);
    ApplyTraits(LampLight, {TEXT("spatial"), TEXT("networked"), TEXT("emissive")});
}

void AMarketDistrict::CreateTechProduct(const FString& PedestalName, const FString& ProductName, const FVector& Location, const FLinearColor& PedestalColor, const FLinearColor& ProductColor)
{
    // Pedestal
    AActor* Pedestal = CreateProceduralMeshActor(PedestalName, EPrimitiveType::Cylinder, Location, FVector(0.6f, 0.6f, 0.1f));
    UMaterialInstanceDynamic* PedestalMat = CreateMaterial(PedestalColor, 0.3f, 0.8f);
    ApplyMaterial(Pedestal, PedestalMat);
    ApplyTraits(Pedestal, {TEXT("spatial"), TEXT("networked")});

    // Product
    AActor* Product = CreateProceduralMeshActor(ProductName, EPrimitiveType::Cube, Location + FVector(0.0f, 0.0f, 40.0f), FVector(0.3f, 0.5f, 0.05f));
    UMaterialInstanceDynamic* ProductMat = CreateMaterial(ProductColor, 0.5f, 0.5f);
    ApplyMaterial(Product, ProductMat);
    ApplyTraits(Product, {TEXT("spatial"), TEXT("networked"), TEXT("grabbable"), TEXT("interactive")});
}

AHoloNPC* AMarketDistrict::CreateNPC(const FString& Name, const FVector& Location, const FString& DialogueId)
{
    FActorSpawnParameters SpawnParams;
    SpawnParams.Owner = this;
    SpawnParams.Name = FName(*Name);

    AHoloNPC* NPC = GetWorld()->SpawnActor<AHoloNPC>(Location, FRotator::ZeroRotator, SpawnParams);
    if (NPC)
    {
        NPC->Initialize(TEXT("humanoid"), TEXT("idle"), DialogueId);
    }

    return NPC;
}

AHoloPortal* AMarketDistrict::CreatePortal(const FString& Name, const FVector& Location, const FString& Destination, const FString& Label)
{
    FActorSpawnParameters SpawnParams;
    SpawnParams.Owner = this;
    SpawnParams.Name = FName(*Name);

    AHoloPortal* Portal = GetWorld()->SpawnActor<AHoloPortal>(Location, FRotator::ZeroRotator, SpawnParams);
    if (Portal)
    {
        Portal->Initialize(Destination, Label, TEXT("swirl"));
    }

    return Portal;
}

void AMarketDistrict::CreatePointLight(const FString& Name, const FVector& Location, const FLinearColor& Color, float Intensity)
{
    FActorSpawnParameters SpawnParams;
    SpawnParams.Owner = this;

    APointLight* Light = GetWorld()->SpawnActor<APointLight>(Location, FRotator::ZeroRotator, SpawnParams);
    if (Light)
    {
        Light->GetLightComponent()->SetIntensity(Intensity * 1000.0f); // Unreal uses lumens
        Light->GetLightComponent()->SetLightColor(Color);
        Light->GetLightComponent()->SetAttenuationRadius(1000.0f); // 10m radius
        PointLights.Add(Light);
    }
}

void AMarketDistrict::CreateSpotLight(const FString& Name, const FVector& Location, const FLinearColor& Color, float Intensity)
{
    FActorSpawnParameters SpawnParams;
    SpawnParams.Owner = this;

    ASpotLight* Light = GetWorld()->SpawnActor<ASpotLight>(Location, FRotator(-90.0f, 0.0f, 0.0f), SpawnParams);
    if (Light)
    {
        Light->GetLightComponent()->SetIntensity(Intensity * 1000.0f);
        Light->GetLightComponent()->SetLightColor(Color);
        Light->GetLightComponent()->SetAttenuationRadius(1500.0f); // 15m radius
        Light->GetLightComponent()->SetOuterConeAngle(60.0f);
        SpotLights.Add(Light);
    }
}

void AMarketDistrict::CreateAmbientSound(const FString& Name, const FString& SoundCueName, bool bLoop, float VolumeMultiplier, bool bSpatialized, const FVector& Location)
{
    FActorSpawnParameters SpawnParams;
    SpawnParams.Owner = this;

    AAmbientSound* Sound = GetWorld()->SpawnActor<AAmbientSound>(Location, FRotator::ZeroRotator, SpawnParams);
    if (Sound && Sound->GetAudioComponent())
    {
        USoundCue* SoundCue = LoadObject<USoundCue>(nullptr, *FString::Printf(TEXT("/Game/HoloScript/Audio/%s"), *SoundCueName));
        if (SoundCue)
        {
            Sound->GetAudioComponent()->SetSound(SoundCue);
            Sound->GetAudioComponent()->bAutoActivate = true;
            Sound->GetAudioComponent()->SetVolumeMultiplier(VolumeMultiplier);

            if (bSpatialized)
            {
                Sound->GetAudioComponent()->AttenuationSettings->AttenuationShape = EAttenuationShape::Sphere;
                Sound->GetAudioComponent()->AttenuationSettings->FalloffDistance = 2000.0f; // 20m
            }
        }

        AmbientSounds.Add(Sound);
    }
}

FLinearColor AMarketDistrict::HexToColor(const FString& Hex)
{
    FString CleanHex = Hex.Replace(TEXT("#"), TEXT(""));

    if (CleanHex.Len() != 6)
        return FLinearColor::White;

    int32 R = FParse::HexNumber(*CleanHex.Mid(0, 2));
    int32 G = FParse::HexNumber(*CleanHex.Mid(2, 2));
    int32 B = FParse::HexNumber(*CleanHex.Mid(4, 2));

    return FLinearColor(R / 255.0f, G / 255.0f, B / 255.0f);
}
