/**
 * HoloScript Cross-Platform Compiler
 *
 * This is a simplified demonstration compiler that generates placeholder code
 * for each target platform. In production, this would use @holoscript/compiler.
 */

type CompilationTarget = 'unity' | 'unreal' | 'godot' | 'babylon' | 'webgpu';

export function compileToTarget(holoScript: string, target: CompilationTarget): string {
  switch (target) {
    case 'unity':
      return compileToUnity(holoScript);
    case 'unreal':
      return compileToUnreal(holoScript);
    case 'godot':
      return compileToGodot(holoScript);
    case 'babylon':
      return compileToBabylon(holoScript);
    case 'webgpu':
      return compileToWebGPU(holoScript);
    default:
      return '// Unknown target';
  }
}

function compileToUnity(source: string): string {
  return `using UnityEngine;
using HoloScript.Runtime;

/// <summary>
/// Generated by HoloScript Compiler v3.42.0
/// Source: ${source.split('\n')[0]}
/// </summary>
public class DemoScene : MonoBehaviour, IHoloZone
{
    private HoloScriptRuntime runtime;

    void Start()
    {
        runtime = new HoloScriptRuntime();
        BuildScene();
    }

    void BuildScene()
    {
        // Magic Cube - Spinning with emissive glow
        var magicCube = CreateObject("MagicCube", PrimitiveType.Cube);
        magicCube.transform.position = new Vector3(0f, 2f, 0f);
        magicCube.transform.localScale = Vector3.one;

        var cubeMaterial = new Material(Shader.Find("Standard"));
        cubeMaterial.SetColor("_Color", HexToColor("#ff00ff"));
        cubeMaterial.SetColor("_EmissionColor", HexToColor("#ff00ff") * 0.5f);
        cubeMaterial.SetFloat("_Metallic", 0.7f);
        cubeMaterial.SetFloat("_Glossiness", 0.7f);
        cubeMaterial.EnableKeyword("_EMISSION");
        magicCube.GetComponent<Renderer>().material = cubeMaterial;

        // Add traits
        magicCube.AddComponent<SpatialTrait>();
        magicCube.AddComponent<NetworkedTrait>();
        magicCube.AddComponent<RotateTrait>().speed = 1f;
        magicCube.AddComponent<EmissiveTrait>();

        // Floating Sphere with pulse animation
        var floatingSphere = CreateObject("FloatingSphere", PrimitiveType.Sphere);
        floatingSphere.transform.position = new Vector3(3f, 2f, 0f);

        var sphereMaterial = new Material(Shader.Find("Standard"));
        sphereMaterial.SetColor("_Color", HexToColor("#00ffff"));
        sphereMaterial.SetFloat("_Glossiness", 0.5f);
        floatingSphere.GetComponent<Renderer>().material = sphereMaterial;

        floatingSphere.AddComponent<SpatialTrait>();
        floatingSphere.AddComponent<FloatTrait>();
        floatingSphere.AddComponent<PulseTrait>();

        // Portal
        var portal = CreateObject("ToAnotherZone", PrimitiveType.Cube);
        portal.transform.position = new Vector3(0f, 1f, -5f);
        portal.AddComponent<HoloPortal>().destination = "main_plaza";
        portal.AddComponent<InteractiveTrait>();

        // Lighting
        var sun = new GameObject("Sun").AddComponent<Light>();
        sun.type = LightType.Directional;
        sun.transform.position = new Vector3(10f, 10f, 5f);
        sun.color = HexToColor("#fff8e1");
        sun.intensity = 1.2f;

        var glowOrb = new GameObject("GlowOrb").AddComponent<Light>();
        glowOrb.type = LightType.Point;
        glowOrb.transform.position = new Vector3(0f, 3f, 0f);
        glowOrb.color = HexToColor("#ff00ff");
        glowOrb.intensity = 0.8f;
        glowOrb.range = 10f;
    }

    GameObject CreateObject(string name, PrimitiveType type)
    {
        var obj = GameObject.CreatePrimitive(type);
        obj.name = name;
        return obj;
    }

    Color HexToColor(string hex)
    {
        ColorUtility.TryParseHtmlString(hex, out Color color);
        return color;
    }

    void Update()
    {
        runtime?.Update(Time.deltaTime);
    }
}`;
}

function compileToUnreal(source: string): string {
  return `// Generated by HoloScript Compiler v3.42.0
// Source: ${source.split('\n')[0]}
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "HoloScriptRuntime.h"
#include "DemoScene.generated.h"

UCLASS()
class ADemoScene : public AActor
{
    GENERATED_BODY()

public:
    ADemoScene();

protected:
    virtual void BeginPlay() override;
    virtual void Tick(float DeltaTime) override;

private:
    void BuildScene();

    AActor* CreateProceduralMeshActor(
        const FString& Name,
        EPrimitiveType Type,
        const FVector& Position,
        const FVector& Scale
    );

    UMaterialInstanceDynamic* CreateMaterial(
        const FLinearColor& Color,
        float Roughness,
        float Metallic
    );

    FLinearColor HexToColor(const FString& Hex);

    UPROPERTY()
    UHoloScriptRuntime* Runtime;
};

// Implementation
ADemoScene::ADemoScene()
{
    PrimaryActorTick.bCanEverTick = true;
}

void ADemoScene::BeginPlay()
{
    Super::BeginPlay();
    Runtime = NewObject<UHoloScriptRuntime>();
    BuildScene();
}

void ADemoScene::BuildScene()
{
    // Magic Cube - Spinning with emissive glow
    AActor* MagicCube = CreateProceduralMeshActor(
        TEXT("MagicCube"),
        EPrimitiveType::Cube,
        FVector(0.0f, 0.0f, 200.0f), // Unreal uses centimeters
        FVector(1.0f, 1.0f, 1.0f)
    );

    UMaterialInstanceDynamic* CubeMaterial = CreateMaterial(
        HexToColor(TEXT("#ff00ff")),
        0.3f,
        0.7f
    );
    CubeMaterial->SetVectorParameterValue(TEXT("EmissiveColor"), HexToColor(TEXT("#ff00ff")) * 0.5f);

    // Apply traits
    MagicCube->AddComponentByClass(USpatialTrait::StaticClass(), false, FTransform::Identity, false);
    MagicCube->AddComponentByClass(UNetworkedTrait::StaticClass(), false, FTransform::Identity, false);
    MagicCube->AddComponentByClass(URotateTrait::StaticClass(), false, FTransform::Identity, false);
    MagicCube->AddComponentByClass(UEmissiveTrait::StaticClass(), false, FTransform::Identity, false);

    // Floating Sphere
    AActor* FloatingSphere = CreateProceduralMeshActor(
        TEXT("FloatingSphere"),
        EPrimitiveType::Sphere,
        FVector(300.0f, 0.0f, 200.0f),
        FVector(1.0f, 1.0f, 1.0f)
    );

    FloatingSphere->AddComponentByClass(UFloatTrait::StaticClass(), false, FTransform::Identity, false);
    FloatingSphere->AddComponentByClass(UPulseTrait::StaticClass(), false, FTransform::Identity, false);

    // Portal
    AActor* Portal = CreateProceduralMeshActor(
        TEXT("ToAnotherZone"),
        EPrimitiveType::Cube,
        FVector(0.0f, 0.0f, -500.0f),
        FVector(1.0f, 1.0f, 1.0f)
    );

    // Lighting
    ADirectionalLight* Sun = GetWorld()->SpawnActor<ADirectionalLight>();
    Sun->SetActorLocation(FVector(1000.0f, 1000.0f, 500.0f));
    Sun->SetLightColor(HexToColor(TEXT("#fff8e1")));
    Sun->SetIntensity(1.2f);

    APointLight* GlowOrb = GetWorld()->SpawnActor<APointLight>();
    GlowOrb->SetActorLocation(FVector(0.0f, 0.0f, 300.0f));
    GlowOrb->SetLightColor(HexToColor(TEXT("#ff00ff")));
    GlowOrb->SetIntensity(0.8f);
    GlowOrb->SetAttenuationRadius(1000.0f); // 10m = 1000cm
}

void ADemoScene::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);
    if (Runtime)
    {
        Runtime->Update(DeltaTime);
    }
}`;
}

function compileToGodot(source: string): string {
  return `# Generated by HoloScript Compiler v3.42.0
# Source: ${source.split('\n')[0]}
extends Node3D
class_name DemoScene

var runtime: HoloScriptRuntime

func _ready():
    runtime = HoloScriptRuntime.new()
    build_scene()

func build_scene():
    # Magic Cube - Spinning with emissive glow
    var magic_cube = create_mesh("MagicCube", "cube", Vector3(0, 2, 0), Vector3(1, 1, 1))

    var cube_material = StandardMaterial3D.new()
    cube_material.albedo_color = hex_to_color("#ff00ff")
    cube_material.emission_enabled = true
    cube_material.emission = hex_to_color("#ff00ff")
    cube_material.emission_energy = 0.5
    cube_material.roughness = 0.3
    cube_material.metallic = 0.7
    magic_cube.material_override = cube_material

    # Apply traits
    magic_cube.set_meta("trait_spatial", true)
    magic_cube.set_meta("trait_networked", true)
    magic_cube.set_meta("trait_rotate", true)
    magic_cube.set_meta("trait_emissive", true)

    # Floating Sphere with pulse
    var floating_sphere = create_mesh("FloatingSphere", "sphere", Vector3(3, 2, 0), Vector3(1, 1, 1))

    var sphere_material = StandardMaterial3D.new()
    sphere_material.albedo_color = hex_to_color("#00ffff")
    sphere_material.roughness = 0.5
    floating_sphere.material_override = sphere_material

    floating_sphere.set_meta("trait_spatial", true)
    floating_sphere.set_meta("trait_float", true)
    floating_sphere.set_meta("trait_pulse", true)

    # Portal
    var portal = create_mesh("ToAnotherZone", "cube", Vector3(0, 1, -5), Vector3(1, 1, 1))
    portal.set_meta("destination", "main_plaza")
    portal.set_meta("trait_interactive", true)

    # Lighting
    var sun = DirectionalLight3D.new()
    sun.name = "Sun"
    sun.position = Vector3(10, 10, 5)
    sun.light_color = hex_to_color("#fff8e1")
    sun.light_energy = 1.2
    add_child(sun)

    var glow_orb = OmniLight3D.new()
    glow_orb.name = "GlowOrb"
    glow_orb.position = Vector3(0, 3, 0)
    glow_orb.light_color = hex_to_color("#ff00ff")
    glow_orb.light_energy = 0.8
    glow_orb.omni_range = 10
    add_child(glow_orb)

func create_mesh(mesh_name: String, type: String, pos: Vector3, scale: Vector3) -> MeshInstance3D:
    var mesh_instance = MeshInstance3D.new()
    mesh_instance.name = mesh_name
    mesh_instance.position = pos
    mesh_instance.scale = scale

    match type:
        "cube":
            mesh_instance.mesh = BoxMesh.new()
        "sphere":
            mesh_instance.mesh = SphereMesh.new()
        _:
            mesh_instance.mesh = BoxMesh.new()

    add_child(mesh_instance)
    return mesh_instance

func hex_to_color(hex: String) -> Color:
    return Color(hex)

func _process(delta):
    if runtime:
        runtime.update(delta)`;
}

function compileToBabylon(source: string): string {
  return `// Generated by HoloScript Compiler v3.42.0
// Source: ${source.split('\n')[0]}
import { Scene, Engine, Vector3, MeshBuilder, StandardMaterial, Color3, DirectionalLight, PointLight, HemisphericLight } from '@babylonjs/core';
import { HoloScriptRuntime } from '@holoscript/runtime-babylon';

export class DemoScene {
    private scene: Scene;
    private runtime: HoloScriptRuntime;

    constructor(private engine: Engine) {
        this.scene = new Scene(engine);
        this.runtime = new HoloScriptRuntime(this.scene);
    }

    async initialize(): Promise<void> {
        await this.buildScene();

        // Render loop
        this.engine.runRenderLoop(() => {
            this.runtime.update(this.engine.getDeltaTime() / 1000);
            this.scene.render();
        });
    }

    private async buildScene(): Promise<void> {
        // Magic Cube - Spinning with emissive glow
        const magicCube = MeshBuilder.CreateBox("MagicCube", { size: 1 }, this.scene);
        magicCube.position = new Vector3(0, 2, 0);

        const cubeMaterial = new StandardMaterial("MagicCubeMaterial", this.scene);
        cubeMaterial.diffuseColor = this.hexToColor("#ff00ff");
        cubeMaterial.emissiveColor = this.hexToColor("#ff00ff").scale(0.5);
        cubeMaterial.specularPower = 30;
        cubeMaterial.metallic = 0.7;
        cubeMaterial.roughness = 0.3;
        magicCube.material = cubeMaterial;

        // Apply traits
        this.runtime.applyTrait(magicCube, '@spatial');
        this.runtime.applyTrait(magicCube, '@networked');
        this.runtime.applyTrait(magicCube, '@rotate', { speed: 1 });
        this.runtime.applyTrait(magicCube, '@emissive');

        // Floating Sphere with pulse
        const floatingSphere = MeshBuilder.CreateSphere("FloatingSphere", { diameter: 1 }, this.scene);
        floatingSphere.position = new Vector3(3, 2, 0);

        const sphereMaterial = new StandardMaterial("SphereMaterial", this.scene);
        sphereMaterial.diffuseColor = this.hexToColor("#00ffff");
        sphereMaterial.roughness = 0.5;
        floatingSphere.material = sphereMaterial;

        this.runtime.applyTrait(floatingSphere, '@spatial');
        this.runtime.applyTrait(floatingSphere, '@float');
        this.runtime.applyTrait(floatingSphere, '@pulse');

        // Portal
        const portal = MeshBuilder.CreateBox("ToAnotherZone", { size: 1 }, this.scene);
        portal.position = new Vector3(0, 1, -5);
        portal.metadata = { destination: "main_plaza" };
        this.runtime.applyTrait(portal, '@interactive');

        // Lighting
        const sun = new DirectionalLight("Sun", new Vector3(-10, -10, -5), this.scene);
        sun.position = new Vector3(10, 10, 5);
        sun.diffuse = this.hexToColor("#fff8e1");
        sun.intensity = 1.2;

        const glowOrb = new PointLight("GlowOrb", new Vector3(0, 3, 0), this.scene);
        glowOrb.diffuse = this.hexToColor("#ff00ff");
        glowOrb.intensity = 0.8;
        glowOrb.range = 10;
    }

    private hexToColor(hex: string): Color3 {
        const r = parseInt(hex.slice(1, 3), 16) / 255;
        const g = parseInt(hex.slice(3, 5), 16) / 255;
        const b = parseInt(hex.slice(5, 7), 16) / 255;
        return new Color3(r, g, b);
    }

    getScene(): Scene {
        return this.scene;
    }
}`;
}

function compileToWebGPU(source: string): string {
  return `// Generated by HoloScript Compiler v3.42.0
// Source: ${source.split('\n')[0]}

// ============================================================================
// Vertex Shader
// ============================================================================

struct VertexInput {
    @location(0) position: vec3f,
    @location(1) normal: vec3f,
    @location(2) uv: vec2f,
}

struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(0) worldPosition: vec3f,
    @location(1) worldNormal: vec3f,
    @location(2) uv: vec2f,
}

struct CameraUniforms {
    viewProjectionMatrix: mat4x4f,
    cameraPosition: vec3f,
    _padding: f32,
}

struct ModelUniforms {
    modelMatrix: mat4x4f,
    normalMatrix: mat4x4f,
}

struct MaterialUniforms {
    baseColor: vec4f,
    emissiveColor: vec3f,
    emissiveIntensity: f32,
    roughness: f32,
    metallic: f32,
    _padding: vec2f,
}

@group(0) @binding(0) var<uniform> camera: CameraUniforms;
@group(1) @binding(0) var<uniform> model: ModelUniforms;
@group(2) @binding(0) var<uniform> material: MaterialUniforms;

@vertex
fn vertexMain(input: VertexInput) -> VertexOutput {
    var output: VertexOutput;

    let worldPosition = model.modelMatrix * vec4f(input.position, 1.0);
    output.worldPosition = worldPosition.xyz;
    output.position = camera.viewProjectionMatrix * worldPosition;

    let worldNormal = model.normalMatrix * vec4f(input.normal, 0.0);
    output.worldNormal = normalize(worldNormal.xyz);

    output.uv = input.uv;

    return output;
}

// ============================================================================
// Fragment Shader - PBR Lighting
// ============================================================================

const PI: f32 = 3.14159265359;

fn fresnelSchlick(cosTheta: f32, F0: vec3f) -> vec3f {
    return F0 + (1.0 - F0) * pow(1.0 - cosTheta, 5.0);
}

fn distributionGGX(N: vec3f, H: vec3f, roughness: f32) -> f32 {
    let a = roughness * roughness;
    let a2 = a * a;
    let NdotH = max(dot(N, H), 0.0);
    let NdotH2 = NdotH * NdotH;

    let num = a2;
    var denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;

    return num / denom;
}

fn geometrySchlickGGX(NdotV: f32, roughness: f32) -> f32 {
    let r = (roughness + 1.0);
    let k = (r * r) / 8.0;

    let num = NdotV;
    let denom = NdotV * (1.0 - k) + k;

    return num / denom;
}

fn geometrySmith(N: vec3f, V: vec3f, L: vec3f, roughness: f32) -> f32 {
    let NdotV = max(dot(N, V), 0.0);
    let NdotL = max(dot(N, L), 0.0);
    let ggx2 = geometrySchlickGGX(NdotV, roughness);
    let ggx1 = geometrySchlickGGX(NdotL, roughness);

    return ggx1 * ggx2;
}

@fragment
fn fragmentMain(input: VertexOutput) -> @location(0) vec4f {
    let albedo = material.baseColor.rgb;
    let N = normalize(input.worldNormal);
    let V = normalize(camera.cameraPosition - input.worldPosition);

    // Fresnel reflectance at normal incidence
    var F0 = vec3f(0.04);
    F0 = mix(F0, albedo, material.metallic);

    // Light direction (simple directional light)
    let L = normalize(vec3f(10.0, 10.0, 5.0));
    let H = normalize(V + L);

    let radiance = vec3f(1.0, 0.97, 0.88) * 1.2; // Sun color #fff8e1

    // Cook-Torrance BRDF
    let NDF = distributionGGX(N, H, material.roughness);
    let G = geometrySmith(N, V, L, material.roughness);
    let F = fresnelSchlick(max(dot(H, V), 0.0), F0);

    let numerator = NDF * G * F;
    let denominator = 4.0 * max(dot(N, V), 0.0) * max(dot(N, L), 0.0) + 0.0001;
    let specular = numerator / denominator;

    let kS = F;
    var kD = vec3f(1.0) - kS;
    kD *= 1.0 - material.metallic;

    let NdotL = max(dot(N, L), 0.0);
    var Lo = (kD * albedo / PI + specular) * radiance * NdotL;

    // Add emissive
    let emissive = material.emissiveColor * material.emissiveIntensity;
    var color = Lo + emissive;

    // Tone mapping
    color = color / (color + vec3f(1.0));

    // Gamma correction
    color = pow(color, vec3f(1.0 / 2.2));

    return vec4f(color, material.baseColor.a);
}

// ============================================================================
// Demo Scene Material Configurations
// ============================================================================

// Magic Cube Material:
// baseColor: vec4f(1.0, 0.0, 1.0, 1.0)  // #ff00ff
// emissiveColor: vec3f(1.0, 0.0, 1.0)
// emissiveIntensity: 0.5
// roughness: 0.3
// metallic: 0.7

// Floating Sphere Material:
// baseColor: vec4f(0.0, 1.0, 1.0, 1.0)  // #00ffff
// roughness: 0.5
// metallic: 0.0`;
}
