// Generated by HoloScript Compiler v3.42.0
// Source: examples\demos\mobile-app.holo
// Target: unreal
// Generated: 2026-02-22T06:29:16.798Z
//
// NOTE: This is a demonstration placeholder.
// For actual compilation, use:
//   npx holoscript compile examples\demos\mobile-app.holo --target unreal
//
// Or use the HoloScript CLI from the HoloScript repository:
//   cd ../HoloScript
//   npx @holoscript/cli compile ../examples\demos\mobile-app.holo --target unreal
//
// This placeholder shows the expected output structure and demonstrates
// that cross-compilation from .holo to unreal is supported.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "MobileApp.generated.h"

UCLASS()
class HOLOLAND_API AMobileApp : public AActor
{
    GENERATED_BODY()

public:
    AMobileApp();

protected:
    virtual void BeginPlay() override;

private:
    void BuildEnvironment();
    void SetupLighting();
    void SetupAudio();
};
