/**
 * HoloScript I/O Module
 *
 * Provides import/export functionality between WorldBuilder scenes and HoloScript (.holo) format.
 * This enables seamless integration between the visual editor and the HoloScript language.
 *
 * @module HoloScriptIO
 */

import type {
  Scene,
  SceneNode,
  SceneNodeType,
  Transform,
  Vector3,
  ComponentInstance,
  VisualScript,
  VisualScriptNode,
  VisualScriptConnection,
  SceneSettings,
  AssetReference,
} from './VisualEditor';

// Import the production HoloScript parser from @holoscript/core
import {
  parse as coreParseHoloScript,
  HoloScriptParser,
  type ParseResult as CoreParseResult,
  type Program,
  type WorldDeclaration,
  type OrbDeclaration,
  type OrbProperty,
  type Expression,
  type ArrayLiteral,
  type ObjectLiteral,
  type NumberLiteral,
  type StringLiteral,
  type BooleanLiteral,
  type Vec3Literal,
  type Identifier,
} from '@holoscript/core';

// =============================================================================
// TYPES
// =============================================================================

export interface HoloScriptExportOptions {
  /** Include comments explaining the structure */
  includeComments?: boolean;
  /** Pretty print with indentation (default: 2 spaces) */
  indent?: number;
  /** Include metadata like timestamps and author */
  includeMetadata?: boolean;
  /** Export visual scripts as HoloScript logic blocks */
  exportScripts?: boolean;
  /** Export asset references */
  exportAssets?: boolean;
}

export interface HoloScriptImportOptions {
  /** Validate structure before importing */
  validate?: boolean;
  /** Merge with existing scene instead of replacing */
  merge?: boolean;
  /** Prefix for imported node IDs (to avoid conflicts) */
  idPrefix?: string;
}

export interface HoloScriptParseResult {
  success: boolean;
  scene?: Scene;
  errors: HoloScriptError[];
  warnings: string[];
}

export interface HoloScriptError {
  line: number;
  column: number;
  message: string;
  severity: 'error' | 'warning';
}

// =============================================================================
// CONSTANTS
// =============================================================================

const NODE_TYPE_TO_HOLO: Record<SceneNodeType, string> = {
  empty: 'empty',
  mesh: 'object',
  light: 'light',
  camera: 'camera',
  audio: 'audio',
  trigger: 'trigger',
  spawn: 'spawn_point',
  group: 'spatial_group',
  prefab: 'prefab',
};

const HOLO_TO_NODE_TYPE: Record<string, SceneNodeType> = {
  empty: 'empty',
  object: 'mesh',
  light: 'light',
  camera: 'camera',
  audio: 'audio',
  trigger: 'trigger',
  spawn_point: 'spawn',
  spatial_group: 'group',
  prefab: 'prefab',
  entity: 'mesh',
  npc: 'mesh',
};

// =============================================================================
// EXPORT FUNCTIONS
// =============================================================================

/**
 * Export a Scene to HoloScript (.holo) format
 *
 * @example
 * ```typescript
 * const holoScript = exportToHoloScript(scene, { includeComments: true });
 * fs.writeFileSync('scene.holo', holoScript);
 * ```
 */
export function exportToHoloScript(
  scene: Scene,
  options: HoloScriptExportOptions = {}
): string {
  const {
    includeComments = true,
    indent = 2,
    includeMetadata = true,
    exportScripts = true,
    exportAssets = true,
  } = options;

  const lines: string[] = [];
  const ind = (level: number) => ' '.repeat(indent * level);

  // Header comment
  if (includeComments) {
    lines.push('// ============================================================================');
    lines.push(`// ${scene.name}`);
    lines.push('// Generated by Hololand WorldBuilder');
    if (includeMetadata) {
      lines.push(`// Exported: ${new Date().toISOString()}`);
    }
    lines.push('// ============================================================================');
    lines.push('');
  }

  // Composition block
  lines.push(`composition "${escapeString(scene.name)}" {`);

  // Metadata
  if (includeMetadata) {
    lines.push('');
    lines.push(`${ind(1)}meta {`);
    lines.push(`${ind(2)}id: "${scene.id}"`);
    lines.push(`${ind(2)}version: "1.0.0"`);
    lines.push(`${ind(2)}generator: "hololand-builder"`);
    lines.push(`${ind(1)}}`);
  }

  // Scene settings
  lines.push('');
  lines.push(`${ind(1)}settings {`);
  lines.push(...exportSceneSettings(scene.settings, indent, 2));
  lines.push(`${ind(1)}}`);

  // Assets
  if (exportAssets && scene.assets.size > 0) {
    lines.push('');
    if (includeComments) {
      lines.push(`${ind(1)}// Assets`);
    }
    lines.push(`${ind(1)}assets {`);
    for (const [, asset] of scene.assets) {
      lines.push(...exportAsset(asset, indent, 2));
    }
    lines.push(`${ind(1)}}`);
  }

  // Export root nodes and their children
  lines.push('');
  if (includeComments) {
    lines.push(`${ind(1)}// Scene Graph`);
  }

  for (const rootId of scene.rootNodes) {
    const rootNode = scene.nodes.get(rootId);
    if (rootNode) {
      lines.push(...exportNode(rootNode, scene, indent, 1, includeComments));
    }
  }

  // Export visual scripts as logic blocks
  if (exportScripts && scene.scripts.size > 0) {
    lines.push('');
    if (includeComments) {
      lines.push(`${ind(1)}// Logic & Events`);
    }
    lines.push(`${ind(1)}logic {`);
    for (const [, script] of scene.scripts) {
      lines.push(...exportVisualScript(script, indent, 2, includeComments));
    }
    lines.push(`${ind(1)}}`);
  }

  lines.push('}');

  return lines.join('\n');
}

/**
 * Export scene settings to HoloScript
 */
function exportSceneSettings(settings: SceneSettings, indent: number, level: number): string[] {
  const lines: string[] = [];
  const ind = (l: number) => ' '.repeat(indent * l);

  // Ambient light
  lines.push(`${ind(level)}ambient_light {`);
  lines.push(`${ind(level + 1)}color: "${settings.ambientLight.color}"`);
  lines.push(`${ind(level + 1)}intensity: ${settings.ambientLight.intensity}`);
  lines.push(`${ind(level)}}`);

  // Physics
  lines.push(`${ind(level)}physics {`);
  lines.push(`${ind(level + 1)}enabled: ${settings.physics.enabled}`);
  lines.push(`${ind(level + 1)}gravity: [${settings.physics.gravity.x}, ${settings.physics.gravity.y}, ${settings.physics.gravity.z}]`);
  lines.push(`${ind(level)}}`);

  // Skybox
  if (settings.skybox) {
    lines.push(`${ind(level)}skybox: "${settings.skybox}"`);
  }

  // Fog
  if (settings.fog) {
    lines.push(`${ind(level)}fog {`);
    lines.push(`${ind(level + 1)}color: "${settings.fog.color}"`);
    lines.push(`${ind(level + 1)}near: ${settings.fog.near}`);
    lines.push(`${ind(level + 1)}far: ${settings.fog.far}`);
    lines.push(`${ind(level)}}`);
  }

  return lines;
}

/**
 * Export an asset reference
 */
function exportAsset(asset: AssetReference, indent: number, level: number): string[] {
  const lines: string[] = [];
  const ind = (l: number) => ' '.repeat(indent * l);

  lines.push(`${ind(level)}${asset.type} "${escapeString(asset.name)}" {`);
  lines.push(`${ind(level + 1)}path: "${asset.path}"`);
  if (asset.thumbnail) {
    lines.push(`${ind(level + 1)}thumbnail: "${asset.thumbnail}"`);
  }
  for (const [key, value] of Object.entries(asset.metadata)) {
    lines.push(`${ind(level + 1)}${key}: ${formatValue(value)}`);
  }
  lines.push(`${ind(level)}}`);

  return lines;
}

/**
 * Export a scene node and its children recursively
 */
function exportNode(
  node: SceneNode,
  scene: Scene,
  indent: number,
  level: number,
  includeComments: boolean
): string[] {
  const lines: string[] = [];
  const ind = (l: number) => ' '.repeat(indent * l);
  const holoType = NODE_TYPE_TO_HOLO[node.type] || 'object';

  // Determine if this is a group/container or a leaf node
  const isContainer = node.type === 'group' || node.children.length > 0;

  lines.push('');

  if (isContainer) {
    // Use spatial_group for containers
    lines.push(`${ind(level)}spatial_group "${escapeString(node.name)}" {`);
  } else {
    // Use object/specific type for leaf nodes
    lines.push(`${ind(level)}${holoType} "${escapeString(node.name)}" {`);
  }

  // Transform
  lines.push(`${ind(level + 1)}position: ${formatVector3(node.transform.position)}`);

  // Only include non-identity rotation
  if (!isIdentityRotation(node.transform.rotation)) {
    const euler = quaternionToEuler(node.transform.rotation);
    lines.push(`${ind(level + 1)}rotation: ${formatVector3(euler)}`);
  }

  // Only include non-uniform scale
  if (!isUniformScale(node.transform.scale)) {
    lines.push(`${ind(level + 1)}scale: ${formatVector3(node.transform.scale)}`);
  }

  // Visibility
  if (!node.visible) {
    lines.push(`${ind(level + 1)}visible: false`);
  }

  // Locked state
  if (node.locked) {
    lines.push(`${ind(level + 1)}locked: true`);
  }

  // Components as traits or properties
  if (node.components.length > 0) {
    lines.push('');
    if (includeComments) {
      lines.push(`${ind(level + 1)}// Components`);
    }
    lines.push(...exportComponents(node.components, indent, level + 1));
  }

  // Metadata
  if (Object.keys(node.metadata).length > 0) {
    lines.push('');
    lines.push(`${ind(level + 1)}metadata {`);
    for (const [key, value] of Object.entries(node.metadata)) {
      lines.push(`${ind(level + 2)}${key}: ${formatValue(value)}`);
    }
    lines.push(`${ind(level + 1)}}`);
  }

  // Child nodes
  for (const childId of node.children) {
    const child = scene.nodes.get(childId);
    if (child) {
      lines.push(...exportNode(child, scene, indent, level + 1, includeComments));
    }
  }

  lines.push(`${ind(level)}}`);

  return lines;
}

/**
 * Export components as HoloScript traits and properties
 */
function exportComponents(components: ComponentInstance[], indent: number, level: number): string[] {
  const lines: string[] = [];
  const ind = (l: number) => ' '.repeat(indent * l);

  // Group components by type for traits
  const traits: string[] = [];

  for (const component of components) {
    if (!component.enabled) continue;

    // Some components map directly to traits
    const traitName = componentToTrait(component.componentType);
    if (traitName) {
      traits.push(traitName);
    }

    // Export component properties
    if (Object.keys(component.properties).length > 0) {
      lines.push(`${ind(level)}${component.componentType} {`);
      for (const [key, value] of Object.entries(component.properties)) {
        lines.push(`${ind(level + 1)}${key}: ${formatValue(value)}`);
      }
      lines.push(`${ind(level)}}`);
    }
  }

  // Add traits line if any
  if (traits.length > 0) {
    lines.unshift(`${ind(level)}traits: [${traits.map(t => `"${t}"`).join(', ')}]`);
  }

  return lines;
}

/**
 * Map component types to HoloScript traits
 */
function componentToTrait(componentType: string): string | null {
  const traitMap: Record<string, string> = {
    Collider: 'collidable',
    Interactable: 'interactive',
    Talkable: 'talkable',
    Patrol: 'patrol',
    Physics: 'physics',
    Audio: 'audio',
    Animation: 'animated',
    Particle: 'particle',
    Light: 'emissive',
  };
  return traitMap[componentType] || null;
}

/**
 * Export a visual script to HoloScript logic block
 */
function exportVisualScript(
  script: VisualScript,
  indent: number,
  level: number,
  includeComments: boolean
): string[] {
  const lines: string[] = [];
  const ind = (l: number) => ' '.repeat(indent * l);

  if (includeComments) {
    lines.push(`${ind(level)}// Script: ${script.name}`);
  }

  // Export variables as state
  if (script.variables.length > 0) {
    lines.push(`${ind(level)}state {`);
    for (const variable of script.variables) {
      const value = formatValue(variable.defaultValue);
      lines.push(`${ind(level + 1)}${variable.name}: ${value}`);
    }
    lines.push(`${ind(level)}}`);
    lines.push('');
  }

  // Find event nodes and trace their execution paths
  const eventNodes = Array.from(script.nodes.values()).filter(n => n.type === 'event');

  for (const eventNode of eventNodes) {
    const eventName = (eventNode.properties.eventName as string) || 'on_event';
    lines.push(`${ind(level)}${eventName} {`);

    // Trace the execution flow from this event
    const actions = traceExecutionFlow(eventNode, script);
    for (const action of actions) {
      lines.push(`${ind(level + 1)}${action}`);
    }

    lines.push(`${ind(level)}}`);
    lines.push('');
  }

  return lines;
}

/**
 * Trace execution flow from an event node through connected action nodes
 */
function traceExecutionFlow(eventNode: VisualScriptNode, script: VisualScript): string[] {
  const actions: string[] = [];
  const visited = new Set<string>();
  const queue: string[] = [];

  // Find flow outputs from event node
  const flowOutputs = eventNode.outputs.filter(p => p.type === 'flow');
  for (const output of flowOutputs) {
    for (const connectedId of output.connected) {
      queue.push(connectedId);
    }
  }

  // BFS through connected nodes
  while (queue.length > 0) {
    const connectionId = queue.shift()!;
    if (visited.has(connectionId)) continue;
    visited.add(connectionId);

    // Find the connection
    const connection = script.connections.find(c => c.id === connectionId);
    if (!connection) continue;

    // Get the target node
    const targetNode = script.nodes.get(connection.to.nodeId);
    if (!targetNode) continue;

    // Convert node to HoloScript action
    const action = nodeToHoloScriptAction(targetNode);
    if (action) {
      actions.push(action);
    }

    // Continue tracing flow
    const nextFlowOutputs = targetNode.outputs.filter(p => p.type === 'flow');
    for (const output of nextFlowOutputs) {
      for (const nextConnectedId of output.connected) {
        queue.push(nextConnectedId);
      }
    }
  }

  return actions;
}

/**
 * Convert a visual script node to a HoloScript action statement
 */
function nodeToHoloScriptAction(node: VisualScriptNode): string | null {
  const props = node.properties;

  switch (node.type) {
    case 'action':
      const actionName = (props.action as string) || 'do_action';
      const target = (props.target as string) || 'self';
      const params = (props.params as Record<string, unknown>) || {};
      const paramStr = Object.entries(params)
        .map(([k, v]) => `${k}: ${formatValue(v)}`)
        .join(', ');
      return paramStr ? `${target}.${actionName}(${paramStr})` : `${target}.${actionName}()`;

    case 'condition':
      const condition = (props.condition as string) || 'true';
      return `if (${condition}) { /* ... */ }`;

    case 'variable':
      const varName = (props.name as string) || 'value';
      const varValue = formatValue(props.value);
      return `${varName} = ${varValue}`;

    case 'flow':
      const flowType = (props.flowType as string) || 'sequence';
      return `// ${flowType} flow`;

    default:
      return null;
  }
}

// =============================================================================
// IMPORT FUNCTIONS
// =============================================================================

/**
 * Import a HoloScript (.holo) file into a Scene using the production @holoscript/core parser
 *
 * @example
 * ```typescript
 * const holoScript = fs.readFileSync('scene.holo', 'utf-8');
 * const result = importFromHoloScript(holoScript);
 * if (result.success) {
 *   sceneManager.loadScene(result.scene);
 * } else {
 *   console.error(result.errors);
 * }
 * ```
 */
export function importFromHoloScript(
  source: string,
  options: HoloScriptImportOptions = {}
): HoloScriptParseResult {
  const { validate = true, idPrefix = '' } = options;

  const errors: HoloScriptError[] = [];
  const warnings: string[] = [];

  try {
    // Use the production @holoscript/core parser
    const coreResult = coreParseHoloScript(source);

    if (!coreResult.success) {
      // Convert core parser errors to our format
      for (const err of coreResult.errors) {
        errors.push({
          line: err.line || 0,
          column: err.column || 0,
          message: err.message,
          severity: 'error',
        });
      }
      return { success: false, errors, warnings };
    }

    // Convert warnings
    for (const warn of coreResult.warnings) {
      warnings.push(`Line ${warn.line || '?'}: ${warn.message}`);
    }

    // Convert the parsed Program AST to our internal AST format
    const ast = programToInternalAST(coreResult.program!);

    if (!ast.composition) {
      // Try fallback simplified parser for older .holo format
      const fallbackAst = parseHoloScriptSimplified(source);
      if (fallbackAst.composition) {
        const scene = internalAstToScene(fallbackAst, idPrefix);
        if (validate) {
          errors.push(...validateScene(scene));
        }
        return {
          success: errors.filter(e => e.severity === 'error').length === 0,
          scene,
          errors,
          warnings: [...warnings, 'Used fallback parser for legacy .holo format'],
        };
      }

      errors.push({
        line: 1,
        column: 1,
        message: 'No world/composition block found in HoloScript source',
        severity: 'error',
      });
      return { success: false, errors, warnings };
    }

    // Create scene from AST
    const scene = internalAstToScene(ast, idPrefix);

    // Validate if requested
    if (validate) {
      const validationErrors = validateScene(scene);
      errors.push(...validationErrors);
    }

    return {
      success: errors.filter(e => e.severity === 'error').length === 0,
      scene,
      errors,
      warnings,
    };
  } catch (error) {
    errors.push({
      line: 0,
      column: 0,
      message: error instanceof Error ? error.message : 'Unknown parse error',
      severity: 'error',
    });
    return { success: false, errors, warnings };
  }
}

// =============================================================================
// PRODUCTION PARSER - @holoscript/core AST CONVERSION
// =============================================================================

/**
 * Convert @holoscript/core Program AST to our internal AST format
 */
function programToInternalAST(program: Program): HoloScriptAST {
  const ast: HoloScriptAST = {};

  // Find WorldDeclaration nodes (HoloScript worlds map to compositions)
  for (const node of program.body) {
    if (node.type === 'WorldDeclaration') {
      const world = node as WorldDeclaration;
      ast.composition = {
        name: world.name,
        nodes: [],
        meta: {},
        settings: extractWorldSettings(world.properties),
      };

      // Convert child orbs to nodes
      for (const child of world.children) {
        if (child.type === 'OrbDeclaration') {
          ast.composition.nodes.push(orbToASTNode(child as OrbDeclaration));
        }
      }
    }
  }

  return ast;
}

/**
 * Extract world settings from OrbProperty array
 */
function extractWorldSettings(properties: OrbProperty[]): Record<string, unknown> {
  const settings: Record<string, unknown> = {};

  for (const prop of properties) {
    const value = expressionToValue(prop.value);

    switch (prop.name) {
      case 'light':
      case 'ambient':
        settings.ambient_light = { color: '#404040', intensity: 0.5 };
        break;
      case 'background':
        settings.skybox = value;
        break;
      case 'gravity':
        settings.physics = { enabled: true, gravity: value };
        break;
      default:
        settings[prop.name] = value;
    }
  }

  return settings;
}

/**
 * Convert OrbDeclaration to internal AST node
 */
function orbToASTNode(orb: OrbDeclaration): HoloScriptASTNode {
  const properties: Record<string, unknown> = {};
  let nodeType = 'object';

  for (const prop of orb.properties) {
    const value = expressionToValue(prop.value);

    switch (prop.name) {
      case 'geometry':
        properties.mesh = value;
        if (value === 'light' || value === 'spotlight' || value === 'pointlight') {
          nodeType = 'light';
        }
        break;
      case 'position':
        properties.position = value;
        break;
      case 'rotation':
        properties.rotation = value;
        break;
      case 'scale':
        properties.scale = typeof value === 'number' ? [value, value, value] : value;
        break;
      case 'color':
        properties.color = value;
        break;
      case 'traits':
        properties.traits = value;
        break;
      default:
        properties[prop.name] = value;
    }
  }

  // Convert child orbs
  const children: HoloScriptASTNode[] = [];
  if (orb.children) {
    for (const child of orb.children) {
      children.push(orbToASTNode(child));
    }
  }

  // Determine node type from properties
  if (properties.mesh === 'camera' || orb.name.toLowerCase().includes('camera')) {
    nodeType = 'camera';
  } else if (properties.mesh === 'audio' || orb.name.toLowerCase().includes('audio')) {
    nodeType = 'audio';
  } else if (children.length > 0) {
    nodeType = 'spatial_group';
  }

  return {
    type: nodeType,
    name: orb.name,
    properties,
    children,
  };
}

/**
 * Convert AST Expression to JavaScript value
 */
function expressionToValue(expr: Expression): unknown {
  switch (expr.type) {
    case 'NumberLiteral':
      return (expr as NumberLiteral).value;

    case 'StringLiteral':
      return (expr as StringLiteral).value;

    case 'BooleanLiteral':
      return (expr as BooleanLiteral).value;

    case 'NullLiteral':
      return null;

    case 'ArrayLiteral':
      return (expr as ArrayLiteral).elements.map(expressionToValue);

    case 'ObjectLiteral':
      const obj: Record<string, unknown> = {};
      for (const prop of (expr as ObjectLiteral).properties) {
        const key = prop.key.type === 'Identifier'
          ? (prop.key as Identifier).name
          : (prop.key as StringLiteral).value;
        obj[key] = expressionToValue(prop.value);
      }
      return obj;

    case 'Vec3Literal':
      const v3 = expr as Vec3Literal;
      return [
        expressionToValue(v3.x),
        expressionToValue(v3.y),
        expressionToValue(v3.z),
      ];

    case 'ColorLiteral':
      return (expr as { value: string }).value;

    case 'Identifier':
      return (expr as Identifier).name;

    default:
      return null;
  }
}

// =============================================================================
// SIMPLIFIED PARSER (Fallback for legacy .holo format)
// =============================================================================

interface HoloScriptAST {
  composition?: {
    name: string;
    meta?: Record<string, unknown>;
    settings?: Record<string, unknown>;
    assets?: Array<{ type: string; name: string; properties: Record<string, unknown> }>;
    nodes: HoloScriptASTNode[];
    logic?: HoloScriptASTLogic[];
  };
}

interface HoloScriptASTNode {
  type: string;
  name: string;
  properties: Record<string, unknown>;
  children: HoloScriptASTNode[];
}

interface HoloScriptASTLogic {
  event: string;
  actions: string[];
  state?: Record<string, unknown>;
}

/**
 * Simplified parser for legacy .holo format (fallback when core parser doesn't recognize format)
 */
function parseHoloScriptSimplified(source: string): HoloScriptAST {
  const ast: HoloScriptAST = {};

  // Remove comments
  const cleanSource = source.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');

  // Find composition block
  const compositionMatch = cleanSource.match(/composition\s+"([^"]+)"\s*\{/);
  if (!compositionMatch) {
    return ast;
  }

  const compositionName = compositionMatch[1];
  ast.composition = {
    name: compositionName,
    nodes: [],
  };

  // Parse blocks within composition
  // This is a simplified parser - just extracts top-level structure
  const blocks = extractBlocks(cleanSource);

  for (const block of blocks) {
    if (block.type === 'meta') {
      ast.composition.meta = parseProperties(block.content);
    } else if (block.type === 'settings') {
      ast.composition.settings = parseProperties(block.content);
    } else if (block.type === 'assets') {
      ast.composition.assets = parseAssetBlock(block.content);
    } else if (block.type === 'logic') {
      ast.composition.logic = parseLogicBlock(block.content);
    } else if (block.type === 'spatial_group' || block.type === 'object' || HOLO_TO_NODE_TYPE[block.type]) {
      ast.composition.nodes.push(parseNodeBlock(block));
    }
  }

  return ast;
}

interface ParsedBlock {
  type: string;
  name: string;
  content: string;
  children: ParsedBlock[];
}

/**
 * Extract top-level blocks from source
 */
function extractBlocks(source: string): ParsedBlock[] {
  const blocks: ParsedBlock[] = [];
  const blockRegex = /(\w+)\s+(?:"([^"]+)"\s*)?\{/g;
  let match;
  let depth = 0;
  let currentBlock: ParsedBlock | null = null;
  let startIndex = 0;

  // Skip the composition block header
  const compositionStart = source.indexOf('{');
  if (compositionStart === -1) return blocks;

  let i = compositionStart + 1;
  while (i < source.length) {
    const char = source[i];

    if (char === '{') {
      if (depth === 0) {
        // Find the block type and name before this brace
        const beforeBrace = source.slice(startIndex, i).trim();
        const typeMatch = beforeBrace.match(/(\w+)\s*(?:"([^"]+)")?\s*$/);
        if (typeMatch) {
          currentBlock = {
            type: typeMatch[1],
            name: typeMatch[2] || '',
            content: '',
            children: [],
          };
        }
      }
      depth++;
    } else if (char === '}') {
      depth--;
      if (depth === 0 && currentBlock) {
        currentBlock.content = source.slice(startIndex, i);
        blocks.push(currentBlock);
        currentBlock = null;
        startIndex = i + 1;
      }
    }

    if (depth === 0 && !currentBlock) {
      startIndex = i;
    }

    i++;
  }

  return blocks;
}

/**
 * Parse properties from a block content
 */
function parseProperties(content: string): Record<string, unknown> {
  const props: Record<string, unknown> = {};
  const lines = content.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//')) continue;

    const colonIndex = trimmed.indexOf(':');
    if (colonIndex === -1) continue;

    const key = trimmed.slice(0, colonIndex).trim();
    const valueStr = trimmed.slice(colonIndex + 1).trim();
    props[key] = parseValue(valueStr);
  }

  return props;
}

/**
 * Parse a value string into the appropriate type
 */
function parseValue(valueStr: string): unknown {
  // Remove trailing comma if present
  const clean = valueStr.replace(/,\s*$/, '').trim();

  // Boolean
  if (clean === 'true') return true;
  if (clean === 'false') return false;

  // Number
  if (/^-?\d+(\.\d+)?$/.test(clean)) return parseFloat(clean);

  // Array (vector)
  if (clean.startsWith('[') && clean.endsWith(']')) {
    const inner = clean.slice(1, -1);
    return inner.split(',').map(v => parseValue(v.trim()));
  }

  // String
  if ((clean.startsWith('"') && clean.endsWith('"')) ||
      (clean.startsWith("'") && clean.endsWith("'"))) {
    return clean.slice(1, -1);
  }

  // Identifier or expression
  return clean;
}

/**
 * Parse assets block
 */
function parseAssetBlock(content: string): Array<{ type: string; name: string; properties: Record<string, unknown> }> {
  // Simplified - just return empty for now
  // Full implementation would parse asset declarations
  return [];
}

/**
 * Parse logic block
 */
function parseLogicBlock(content: string): HoloScriptASTLogic[] {
  // Simplified - extract event handlers
  const logic: HoloScriptASTLogic[] = [];
  const eventRegex = /(\w+)\s*\{([^}]*)\}/g;
  let match;

  while ((match = eventRegex.exec(content)) !== null) {
    logic.push({
      event: match[1],
      actions: match[2].split('\n').map(l => l.trim()).filter(l => l),
    });
  }

  return logic;
}

/**
 * Parse a node block (object, spatial_group, etc.)
 */
function parseNodeBlock(block: ParsedBlock): HoloScriptASTNode {
  const properties = parseProperties(block.content);

  // Extract nested children (simplified)
  const children: HoloScriptASTNode[] = [];

  return {
    type: block.type,
    name: block.name,
    properties,
    children,
  };
}

// =============================================================================
// AST TO SCENE CONVERSION
// =============================================================================

/**
 * Convert parsed internal AST to a Scene object
 */
function internalAstToScene(ast: HoloScriptAST, idPrefix: string): Scene {
  const generateId = () => `${idPrefix}${Date.now().toString(36)}-${Math.random().toString(36).substr(2, 9)}`;

  const scene: Scene = {
    id: generateId(),
    name: ast.composition?.name || 'Imported Scene',
    nodes: new Map(),
    rootNodes: [],
    scripts: new Map(),
    assets: new Map(),
    settings: {
      ambientLight: { color: '#404040', intensity: 0.5 },
      physics: { gravity: { x: 0, y: -9.81, z: 0 }, enabled: true },
    },
  };

  // Apply settings from AST
  if (ast.composition?.settings) {
    const s = ast.composition.settings;
    if (s.ambient_light) {
      const al = s.ambient_light as Record<string, unknown>;
      scene.settings.ambientLight = {
        color: (al.color as string) || '#404040',
        intensity: (al.intensity as number) || 0.5,
      };
    }
    if (s.physics) {
      const p = s.physics as Record<string, unknown>;
      scene.settings.physics = {
        enabled: (p.enabled as boolean) ?? true,
        gravity: arrayToVector3((p.gravity as number[]) || [0, -9.81, 0]),
      };
    }
    if (s.skybox) {
      scene.settings.skybox = s.skybox as string;
    }
    if (s.fog) {
      const f = s.fog as Record<string, unknown>;
      scene.settings.fog = {
        color: (f.color as string) || '#ffffff',
        near: (f.near as number) || 10,
        far: (f.far as number) || 100,
      };
    }
  }

  // Convert nodes
  for (const astNode of ast.composition?.nodes || []) {
    const node = astNodeToSceneNode(astNode, null, scene, generateId);
    scene.nodes.set(node.id, node);
    scene.rootNodes.push(node.id);
  }

  // Convert logic blocks to visual scripts
  if (ast.composition?.logic) {
    const script: VisualScript = {
      id: generateId(),
      name: 'Imported Script',
      nodes: new Map(),
      connections: [],
      variables: [],
    };

    for (const logicBlock of ast.composition.logic) {
      // Create event node
      const eventNode: VisualScriptNode = {
        id: generateId(),
        type: 'event',
        position: { x: 0, y: script.nodes.size * 100 },
        inputs: [],
        outputs: [{ id: generateId(), name: 'flow', type: 'flow', connected: [] }],
        properties: { eventName: logicBlock.event },
      };
      script.nodes.set(eventNode.id, eventNode);

      // Create action nodes for each action
      let prevNodeId = eventNode.id;
      for (const action of logicBlock.actions) {
        const actionNode: VisualScriptNode = {
          id: generateId(),
          type: 'action',
          position: { x: 200, y: script.nodes.size * 100 },
          inputs: [{ id: generateId(), name: 'flow', type: 'flow', connected: [] }],
          outputs: [{ id: generateId(), name: 'flow', type: 'flow', connected: [] }],
          properties: { action: action },
        };
        script.nodes.set(actionNode.id, actionNode);

        // Connect previous node to this one
        const connection: VisualScriptConnection = {
          id: generateId(),
          from: { nodeId: prevNodeId, portId: 'flow' },
          to: { nodeId: actionNode.id, portId: 'flow' },
        };
        script.connections.push(connection);
        prevNodeId = actionNode.id;
      }
    }

    scene.scripts.set(script.id, script);
  }

  return scene;
}

/**
 * Convert an AST node to a SceneNode
 */
function astNodeToSceneNode(
  astNode: HoloScriptASTNode,
  parent: string | null,
  scene: Scene,
  generateId: () => string
): SceneNode {
  const nodeType = HOLO_TO_NODE_TYPE[astNode.type] || 'mesh';
  const id = generateId();

  // Extract transform from properties
  const position = arrayToVector3((astNode.properties.position as number[]) || [0, 0, 0]);
  const rotationArr = (astNode.properties.rotation as number[]) || [0, 0, 0];
  const rotation = eulerToQuaternion({ x: rotationArr[0], y: rotationArr[1], z: rotationArr[2] });
  const scale = arrayToVector3((astNode.properties.scale as number[]) || [1, 1, 1]);

  // Extract components from traits
  const components: ComponentInstance[] = [];
  const traits = (astNode.properties.traits as string[]) || [];
  for (const trait of traits) {
    components.push({
      id: generateId(),
      componentType: traitToComponent(trait),
      properties: {},
      enabled: true,
    });
  }

  const node: SceneNode = {
    id,
    name: astNode.name || 'Imported Node',
    type: nodeType,
    transform: { position, rotation, scale },
    parent,
    children: [],
    components,
    visible: astNode.properties.visible !== false,
    locked: astNode.properties.locked === true,
    metadata: (astNode.properties.metadata as Record<string, unknown>) || {},
  };

  // Process children
  for (const childAst of astNode.children) {
    const childNode = astNodeToSceneNode(childAst, id, scene, generateId);
    scene.nodes.set(childNode.id, childNode);
    node.children.push(childNode.id);
  }

  return node;
}

/**
 * Map HoloScript traits to component types
 */
function traitToComponent(trait: string): string {
  const componentMap: Record<string, string> = {
    collidable: 'Collider',
    interactive: 'Interactable',
    talkable: 'Talkable',
    patrol: 'Patrol',
    physics: 'Physics',
    audio: 'Audio',
    animated: 'Animation',
    particle: 'Particle',
    emissive: 'Light',
  };
  return componentMap[trait] || trait;
}

/**
 * Validate a scene for common issues
 */
function validateScene(scene: Scene): HoloScriptError[] {
  const errors: HoloScriptError[] = [];

  // Check for orphan nodes
  for (const [id, node] of scene.nodes) {
    if (node.parent && !scene.nodes.has(node.parent)) {
      errors.push({
        line: 0,
        column: 0,
        message: `Node "${node.name}" references non-existent parent`,
        severity: 'warning',
      });
    }
  }

  // Check for empty scene
  if (scene.nodes.size === 0) {
    errors.push({
      line: 0,
      column: 0,
      message: 'Scene contains no nodes',
      severity: 'warning',
    });
  }

  return errors;
}

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function formatValue(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'string') return `"${escapeString(value)}"`;
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    return `[${value.map(formatValue).join(', ')}]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value)
      .map(([k, v]) => `${k}: ${formatValue(v)}`)
      .join(', ');
    return `{ ${entries} }`;
  }
  return String(value);
}

function formatVector3(v: Vector3): string {
  return `[${v.x}, ${v.y}, ${v.z}]`;
}

function isIdentityRotation(q: { x: number; y: number; z: number; w: number }): boolean {
  return q.x === 0 && q.y === 0 && q.z === 0 && q.w === 1;
}

function isUniformScale(s: Vector3): boolean {
  return s.x === 1 && s.y === 1 && s.z === 1;
}

function quaternionToEuler(q: { x: number; y: number; z: number; w: number }): Vector3 {
  // Simplified conversion - production would use proper math
  const sinr_cosp = 2 * (q.w * q.x + q.y * q.z);
  const cosr_cosp = 1 - 2 * (q.x * q.x + q.y * q.y);
  const roll = Math.atan2(sinr_cosp, cosr_cosp);

  const sinp = 2 * (q.w * q.y - q.z * q.x);
  const pitch = Math.abs(sinp) >= 1 ? Math.sign(sinp) * Math.PI / 2 : Math.asin(sinp);

  const siny_cosp = 2 * (q.w * q.z + q.x * q.y);
  const cosy_cosp = 1 - 2 * (q.y * q.y + q.z * q.z);
  const yaw = Math.atan2(siny_cosp, cosy_cosp);

  // Convert to degrees
  const toDeg = 180 / Math.PI;
  return { x: roll * toDeg, y: pitch * toDeg, z: yaw * toDeg };
}

function eulerToQuaternion(euler: Vector3): { x: number; y: number; z: number; w: number } {
  // Convert degrees to radians
  const toRad = Math.PI / 180;
  const roll = euler.x * toRad;
  const pitch = euler.y * toRad;
  const yaw = euler.z * toRad;

  const cr = Math.cos(roll * 0.5);
  const sr = Math.sin(roll * 0.5);
  const cp = Math.cos(pitch * 0.5);
  const sp = Math.sin(pitch * 0.5);
  const cy = Math.cos(yaw * 0.5);
  const sy = Math.sin(yaw * 0.5);

  return {
    w: cr * cp * cy + sr * sp * sy,
    x: sr * cp * cy - cr * sp * sy,
    y: cr * sp * cy + sr * cp * sy,
    z: cr * cp * sy - sr * sp * cy,
  };
}

function arrayToVector3(arr: number[]): Vector3 {
  return { x: arr[0] || 0, y: arr[1] || 0, z: arr[2] || 0 };
}

// =============================================================================
// CONVENIENCE EXPORTS
// =============================================================================

/**
 * Quick export with default options
 */
export function sceneToHoloScript(scene: Scene): string {
  return exportToHoloScript(scene, { includeComments: true, includeMetadata: true });
}

/**
 * Quick import with validation
 */
export function holoScriptToScene(source: string): Scene | null {
  const result = importFromHoloScript(source);
  return result.success ? result.scene! : null;
}
