/**
 * HoloScript I/O Tests
 *
 * Unit tests for HoloScript import/export functionality
 */

import { describe, it, expect, beforeEach } from 'vitest';
import {
  exportToHoloScript,
  importFromHoloScript,
  sceneToHoloScript,
  holoScriptToScene,
} from '../src/HoloScriptIO';
import { SceneManager } from '../src/VisualEditor';
import type { Scene, SceneNode } from '../src/VisualEditor';

describe('HoloScriptIO', () => {
  let sceneManager: SceneManager;

  beforeEach(() => {
    sceneManager = new SceneManager('Test Scene');
  });

  describe('exportToHoloScript', () => {
    it('should export empty scene', () => {
      const scene = sceneManager.getScene();
      const holoScript = exportToHoloScript(scene);

      expect(holoScript).toContain('composition "Test Scene"');
      expect(holoScript).toContain('settings {');
      expect(holoScript).toContain('ambient_light {');
      expect(holoScript).toContain('physics {');
    });

    it('should export scene with nodes', () => {
      sceneManager.createNode('mesh', 'TestCube');
      sceneManager.createNode('light', 'MainLight');

      const scene = sceneManager.getScene();
      const holoScript = exportToHoloScript(scene);

      expect(holoScript).toContain('"TestCube"');
      expect(holoScript).toContain('"MainLight"');
      expect(holoScript).toContain('position:');
    });

    it('should export nested nodes as spatial groups', () => {
      const parent = sceneManager.createNode('group', 'Environment');
      sceneManager.createNode('mesh', 'Floor', parent.id);
      sceneManager.createNode('mesh', 'Wall', parent.id);

      const scene = sceneManager.getScene();
      const holoScript = exportToHoloScript(scene);

      expect(holoScript).toContain('spatial_group "Environment"');
      expect(holoScript).toContain('"Floor"');
      expect(holoScript).toContain('"Wall"');
    });

    it('should export node transforms', () => {
      const node = sceneManager.createNode('mesh', 'MovedObject');
      sceneManager.setNodeTransform(node.id, {
        position: { x: 5, y: 10, z: -3 },
        scale: { x: 2, y: 2, z: 2 },
      });

      const scene = sceneManager.getScene();
      const holoScript = exportToHoloScript(scene);

      expect(holoScript).toContain('position: [5, 10, -3]');
      expect(holoScript).toContain('scale: [2, 2, 2]');
    });

    it('should export components as traits', () => {
      const node = sceneManager.createNode('mesh', 'InteractiveObject');
      sceneManager.addComponent(node.id, 'Interactable', { prompt: 'Click me' });
      sceneManager.addComponent(node.id, 'Collider', { type: 'box' });

      const scene = sceneManager.getScene();
      const holoScript = exportToHoloScript(scene);

      expect(holoScript).toContain('traits:');
      expect(holoScript).toContain('"interactive"');
      expect(holoScript).toContain('"collidable"');
    });

    it('should respect includeComments option', () => {
      const scene = sceneManager.getScene();

      const withComments = exportToHoloScript(scene, { includeComments: true });
      const withoutComments = exportToHoloScript(scene, { includeComments: false });

      expect(withComments).toContain('// ');
      expect(withComments).toContain('Generated by Hololand');
      expect(withoutComments).not.toContain('// ');
    });

    it('should respect includeMetadata option', () => {
      const scene = sceneManager.getScene();

      const withMeta = exportToHoloScript(scene, { includeMetadata: true });
      const withoutMeta = exportToHoloScript(scene, { includeMetadata: false });

      expect(withMeta).toContain('meta {');
      expect(withMeta).toContain('generator: "hololand-builder"');
      expect(withoutMeta).not.toContain('meta {');
    });

    it('should export visibility and locked state', () => {
      const node = sceneManager.createNode('mesh', 'HiddenObject');
      sceneManager.updateNode(node.id, { visible: false, locked: true });

      const scene = sceneManager.getScene();
      const holoScript = exportToHoloScript(scene);

      expect(holoScript).toContain('visible: false');
      expect(holoScript).toContain('locked: true');
    });
  });

  describe('importFromHoloScript', () => {
    it('should import basic composition', () => {
      const source = `
        composition "Imported Scene" {
          settings {
            ambient_light {
              color: "#ffffff"
              intensity: 0.8
            }
            physics {
              enabled: true
              gravity: [0, -9.81, 0]
            }
          }
        }
      `;

      const result = importFromHoloScript(source);

      expect(result.success).toBe(true);
      expect(result.scene).toBeDefined();
      expect(result.scene!.name).toBe('Imported Scene');
    });

    it('should import scene with objects', () => {
      const source = `
        composition "Object Test" {
          settings {
            ambient_light { color: "#404040", intensity: 0.5 }
            physics { enabled: true, gravity: [0, -9.81, 0] }
          }

          object "MyCube" {
            position: [1, 2, 3]
            scale: [2, 2, 2]
          }
        }
      `;

      const result = importFromHoloScript(source);

      // Note: The simplified built-in parser may not fully parse nested objects.
      // In production, use the full @holoscript/core parser.
      expect(result.success).toBe(true);
      expect(result.scene).toBeDefined();
      expect(result.scene!.name).toBe('Object Test');
    });

    it('should report errors for invalid source', () => {
      const source = `not valid holoscript`;

      const result = importFromHoloScript(source);

      expect(result.success).toBe(false);
      expect(result.errors.length).toBeGreaterThan(0);
    });

    it('should handle empty composition', () => {
      const source = `composition "Empty" {}`;

      const result = importFromHoloScript(source);

      expect(result.success).toBe(true);
      expect(result.scene!.name).toBe('Empty');
      expect(result.warnings.length).toBeGreaterThanOrEqual(0);
    });
  });

  describe('sceneToHoloScript', () => {
    it('should be a convenience wrapper for exportToHoloScript', () => {
      const scene = sceneManager.getScene();
      const result = sceneToHoloScript(scene);

      expect(result).toContain('composition');
      expect(result).toContain('meta {');
      expect(result).toContain('// ');
    });
  });

  describe('holoScriptToScene', () => {
    it('should return scene on success', () => {
      const source = `composition "Quick Import" {}`;
      const scene = holoScriptToScene(source);

      expect(scene).toBeDefined();
      expect(scene!.name).toBe('Quick Import');
    });

    it('should return null on failure', () => {
      const source = `invalid`;
      const scene = holoScriptToScene(source);

      expect(scene).toBeNull();
    });
  });

  describe('round-trip', () => {
    it('should preserve scene structure through export/import', () => {
      // Create a scene with various elements
      const group = sceneManager.createNode('group', 'World');
      const floor = sceneManager.createNode('mesh', 'Floor', group.id);
      const light = sceneManager.createNode('light', 'Sun');

      sceneManager.setNodeTransform(floor.id, {
        position: { x: 0, y: 0, z: 0 },
        scale: { x: 10, y: 0.1, z: 10 },
      });

      sceneManager.setNodeTransform(light.id, {
        position: { x: 0, y: 10, z: 0 },
      });

      sceneManager.addComponent(floor.id, 'Collider', { type: 'box' });

      // Export
      const scene = sceneManager.getScene();
      const holoScript = exportToHoloScript(scene);

      // Import
      const result = importFromHoloScript(holoScript);

      expect(result.success).toBe(true);
      expect(result.scene).toBeDefined();
      expect(result.scene!.name).toBe('Test Scene');
    });

    it('should preserve scene settings', () => {
      const scene = sceneManager.getScene();
      scene.settings.skybox = 'sunset.hdr';
      scene.settings.fog = { color: '#aabbcc', near: 5, far: 50 };

      const holoScript = exportToHoloScript(scene);

      expect(holoScript).toContain('skybox: "sunset.hdr"');
      expect(holoScript).toContain('fog {');
      expect(holoScript).toContain('color: "#aabbcc"');
      expect(holoScript).toContain('near: 5');
      expect(holoScript).toContain('far: 50');
    });
  });
});
