/**
 * HoloScript Code Generator Component
 *
 * Generates valid .holo syntax code from the composition state.
 * Provides code preview and export functionality.
 */

import React, { useMemo, useCallback } from 'react';
import type { Composition } from './types';
import styles from './HoloCodeGenerator.module.css';

interface HoloCodeGeneratorProps {
  /** Current composition */
  composition: Composition;
  /** Callback to export code */
  onExport: (code: string, filename: string) => void;
}

/**
 * Generate .holo code from composition
 */
function generateHoloCode(composition: Composition): string {
  const lines: string[] = [];

  // Header comment
  lines.push('/**');
  lines.push(` * ${composition.objectId}`);
  if (composition.metadata.description) {
    lines.push(` * ${composition.metadata.description}`);
  }
  if (composition.vertical) {
    lines.push(` * Vertical: ${composition.vertical}`);
  }
  lines.push(' * Generated by HoloScript Composition Editor');
  lines.push(` * ${new Date().toISOString()}`);
  lines.push(' */');
  lines.push('');

  // Object declaration
  lines.push(`object ${composition.objectId} {`);

  // Traits
  if (composition.traits.length > 0) {
    composition.traits.forEach((trait) => {
      lines.push(`  ${trait.name}`);

      // Trait configuration
      if (Object.keys(trait.config).length > 0) {
        Object.entries(trait.config).forEach(([key, value]) => {
          const formattedValue = formatConfigValue(value);
          lines.push(`    ${key}: ${formattedValue}`);
        });
      }
      lines.push('');
    });
  } else {
    lines.push('  // No traits configured');
    lines.push('');
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Format configuration value for .holo syntax
 */
function formatConfigValue(value: unknown): string {
  if (typeof value === 'string') {
    return `"${value}"`;
  }
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(formatConfigValue).join(', ')}]`;
  }
  if (value === null) {
    return 'null';
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${formatConfigValue(v)}`)
      .join(', ');
    return `{ ${entries} }`;
  }
  return String(value);
}

export const HoloCodeGenerator: React.FC<HoloCodeGeneratorProps> = ({
  composition,
  onExport,
}) => {
  const holoCode = useMemo(
    () => generateHoloCode(composition),
    [composition]
  );

  const handleCopyToClipboard = useCallback(() => {
    navigator.clipboard.writeText(holoCode).then(
      () => {
        alert('Code copied to clipboard!');
      },
      (err) => {
        console.error('Failed to copy code:', err);
        alert('Failed to copy code to clipboard.');
      }
    );
  }, [holoCode]);

  const handleExport = useCallback(() => {
    const filename = `${composition.objectId}.holo`;
    onExport(holoCode, filename);
  }, [holoCode, composition.objectId, onExport]);

  return (
    <div className={styles.generator}>
      <div className={styles.header}>
        <h3 className={styles.title}>Generated HoloScript Code</h3>
        <div className={styles.actions}>
          <button
            className={styles.copyButton}
            onClick={handleCopyToClipboard}
            type="button"
            title="Copy code to clipboard"
          >
            Copy to Clipboard
          </button>
          <button
            className={styles.exportButton}
            onClick={handleExport}
            type="button"
            title="Download as .holo file"
          >
            Export as .holo
          </button>
        </div>
      </div>

      <pre className={styles.codePreview}>
        <code>{holoCode}</code>
      </pre>

      <div className={styles.footer}>
        <span className={styles.lineCount}>
          {holoCode.split('\n').length} lines
        </span>
        <span className={styles.charCount}>
          {holoCode.length} characters
        </span>
      </div>
    </div>
  );
};
