/**
 * file: SpatialBridgeService.ts
 * 
 * Takes high-level user intents from the casual Hololand Spatial Builder UI
 * (Radial Menu, Voice Prompts, Lite Inspector) and safely recompiles them into
 * strictly-typed HoloScript `@packages` and payload JSONs.
 */

export interface CasualTraitIntent {
  targetId: string;
  type: string;
  modifiers: {
    color?: string;
    scale?: number;
    damage?: number;
    [key: string]: any;
  };
}

export interface HoloScriptCompiledPayload {
  nodeId: string;
  engine: 'threejs' | 'rapier' | 'holoscript-core';
  traits: Array<{
    namespace: string;
    properties: Record<string, any>;
  }>;
}

export class SpatialBridgeService {
  
  /**
   * Translates visual casual modifiers into strict HoloScript AST node definitions.
   */
  public static compileIntentToTraits(intent: CasualTraitIntent): HoloScriptCompiledPayload {
    const payload: HoloScriptCompiledPayload = {
      nodeId: intent.targetId,
      engine: 'holoscript-core',
      traits: []
    };

    // 1. Core Rendering Trait
    if (intent.modifiers.color || intent.modifiers.scale) {
      payload.traits.push({
        namespace: '@rendering/material-standard',
        properties: {
          albedo: intent.modifiers.color || '#ffffff',
          roughness: 0.5,
          metalness: intent.type === 'sword' ? 0.8 : 0.1,
          scale: intent.modifiers.scale || 1.0
        }
      });
    }

    // 2. Physics & Collision Trait based on Primitive Type
    payload.traits.push({
      namespace: `@physics/collider-${intent.type === 'sphere' ? 'sphere' : 'box'}`,
      properties: {
        isSensor: false,
        mass: intent.type === 'sword' ? 2.5 : 10.0
      }
    });

    // 3. Specialty Traits (Combat)
    if (intent.type === 'sword' && intent.modifiers.damage !== undefined) {
      payload.traits.push({
        namespace: '@combat/melee-weapon',
        properties: {
          baseDamage: intent.modifiers.damage,
          attackSpeed: 1.2,
          durability: 100
        }
      });

      // Inject VFX Trait if damage is high
      if (intent.modifiers.damage > 50) {
        payload.traits.push({
          namespace: '@vfx/particle-emitter',
          properties: {
            preset: 'fire',
            intensity: (intent.modifiers.damage / 100) * 2.0 // Scale fire intensity by damage
          }
        });
      }
    }

    // 4. Component Behaviors
    if (intent.type === 'light') {
      payload.traits.push({
        namespace: '@rendering/point-light',
        properties: {
          color: intent.modifiers.color || '#ffffff',
          intensity: 5.0,
          range: 20.0,
          castShadows: true
        }
      });
    }

    return payload;
  }

  /**
   * Translates the "Voice" payload generated by the local spatial LLM 
   * into the exact same strict `@traits`.
   */
  public static processVoiceAgentPayload(voicePayload: any): HoloScriptCompiledPayload {
    console.log("[SpatialBridge] Decoding Agent Voice Pipeline:", voicePayload);
    // Directly merge AI-generated traits (assuming the Agent LLM knows HoloScript syntax)
    return {
      nodeId: voicePayload.target,
      engine: 'holoscript-core',
      traits: voicePayload.traits.map((t: any) => ({
        namespace: t.type,
        properties: t.properties
      }))
    };
  }
}
